// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_configs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getAgentConfigByID = `-- name: GetAgentConfigByID :one
SELECT id, name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version
FROM agent_configs
WHERE id = $1
`

func (q *Queries) GetAgentConfigByID(ctx context.Context, id uuid.UUID) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfigByID, id)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Stage,
		&i.IsHuman,
		&i.SystemPrompt,
		&i.Model,
		&i.ToolAllowlist,
		&i.Eligibility,
		&i.Origin,
		&i.Version,
	)
	return i, err
}

const getAgentConfigByNameAndStage = `-- name: GetAgentConfigByNameAndStage :one
SELECT id, name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version
FROM agent_configs
WHERE name = $1 AND stage = $2
`

type GetAgentConfigByNameAndStageParams struct {
	Name  string     `json:"name"`
	Stage AgentStage `json:"stage"`
}

func (q *Queries) GetAgentConfigByNameAndStage(ctx context.Context, arg GetAgentConfigByNameAndStageParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfigByNameAndStage, arg.Name, arg.Stage)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Stage,
		&i.IsHuman,
		&i.SystemPrompt,
		&i.Model,
		&i.ToolAllowlist,
		&i.Eligibility,
		&i.Origin,
		&i.Version,
	)
	return i, err
}

const insertAgentConfig = `-- name: InsertAgentConfig :one
INSERT INTO agent_configs (name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version
`

type InsertAgentConfigParams struct {
	Name          string          `json:"name"`
	Stage         AgentStage      `json:"stage"`
	IsHuman       bool            `json:"is_human"`
	SystemPrompt  *string         `json:"system_prompt"`
	Model         *string         `json:"model"`
	ToolAllowlist json.RawMessage `json:"tool_allowlist"`
	Eligibility   json.RawMessage `json:"eligibility"`
	Origin        ConfigOrigin    `json:"origin"`
	Version       int32           `json:"version"`
}

func (q *Queries) InsertAgentConfig(ctx context.Context, arg InsertAgentConfigParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, insertAgentConfig,
		arg.Name,
		arg.Stage,
		arg.IsHuman,
		arg.SystemPrompt,
		arg.Model,
		arg.ToolAllowlist,
		arg.Eligibility,
		arg.Origin,
		arg.Version,
	)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Stage,
		&i.IsHuman,
		&i.SystemPrompt,
		&i.Model,
		&i.ToolAllowlist,
		&i.Eligibility,
		&i.Origin,
		&i.Version,
	)
	return i, err
}

const listAgentConfigsByStage = `-- name: ListAgentConfigsByStage :many
SELECT id, name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version
FROM agent_configs
WHERE stage = $1
ORDER BY name
`

func (q *Queries) ListAgentConfigsByStage(ctx context.Context, stage AgentStage) ([]AgentConfig, error) {
	rows, err := q.db.Query(ctx, listAgentConfigsByStage, stage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConfig
	for rows.Next() {
		var i AgentConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Stage,
			&i.IsHuman,
			&i.SystemPrompt,
			&i.Model,
			&i.ToolAllowlist,
			&i.Eligibility,
			&i.Origin,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgentConfigs = `-- name: ListAllAgentConfigs :many
SELECT id, name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version
FROM agent_configs
ORDER BY stage, name
`

func (q *Queries) ListAllAgentConfigs(ctx context.Context) ([]AgentConfig, error) {
	rows, err := q.db.Query(ctx, listAllAgentConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConfig
	for rows.Next() {
		var i AgentConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Stage,
			&i.IsHuman,
			&i.SystemPrompt,
			&i.Model,
			&i.ToolAllowlist,
			&i.Eligibility,
			&i.Origin,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentConfigByNameAndStage = `-- name: UpdateAgentConfigByNameAndStage :one
UPDATE agent_configs
SET is_human       = $1,
    system_prompt  = $2,
    model          = $3,
    tool_allowlist = $4,
    eligibility    = $5,
    version        = version + 1
WHERE name = $6 AND stage = $7
RETURNING id, name, stage, is_human, system_prompt, model, tool_allowlist, eligibility, origin, version
`

type UpdateAgentConfigByNameAndStageParams struct {
	IsHuman       bool            `json:"is_human"`
	SystemPrompt  *string         `json:"system_prompt"`
	Model         *string         `json:"model"`
	ToolAllowlist json.RawMessage `json:"tool_allowlist"`
	Eligibility   json.RawMessage `json:"eligibility"`
	Name          string          `json:"name"`
	Stage         AgentStage      `json:"stage"`
}

// Used by the file-driven catalog reconciler to apply an override to an existing
// (name, stage) row. Bumps version so the change is observable.
func (q *Queries) UpdateAgentConfigByNameAndStage(ctx context.Context, arg UpdateAgentConfigByNameAndStageParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, updateAgentConfigByNameAndStage,
		arg.IsHuman,
		arg.SystemPrompt,
		arg.Model,
		arg.ToolAllowlist,
		arg.Eligibility,
		arg.Name,
		arg.Stage,
	)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Stage,
		&i.IsHuman,
		&i.SystemPrompt,
		&i.Model,
		&i.ToolAllowlist,
		&i.Eligibility,
		&i.Origin,
		&i.Version,
	)
	return i, err
}
