// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const findOpenAssignmentForStage = `-- name: FindOpenAssignmentForStage :one
SELECT id, task_id, stage, from_principal, ask, gathered_context, created_at, resolved_at
FROM agent_assignments
WHERE task_id = $1 AND stage = $2 AND resolved_at IS NULL
LIMIT 1
`

type FindOpenAssignmentForStageParams struct {
	TaskID uuid.UUID  `json:"task_id"`
	Stage  ChainStage `json:"stage"`
}

// Deterministic recovery lookup: returns the open assignment for (task, stage),
// used when the chain workflow needs to find "its" current slot after restart.
func (q *Queries) FindOpenAssignmentForStage(ctx context.Context, arg FindOpenAssignmentForStageParams) (AgentAssignment, error) {
	row := q.db.QueryRow(ctx, findOpenAssignmentForStage, arg.TaskID, arg.Stage)
	var i AgentAssignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.FromPrincipal,
		&i.Ask,
		&i.GatheredContext,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const findOpenAssignmentForTask = `-- name: FindOpenAssignmentForTask :one
SELECT id, task_id, stage, from_principal, ask, gathered_context, created_at, resolved_at
FROM agent_assignments
WHERE task_id = $1 AND resolved_at IS NULL
LIMIT 1
`

// Returns the open assignment for a task (at most one — partial-unique index
// idx_assign_open enforces uniqueness on open rows). pgx.ErrNoRows if none.
func (q *Queries) FindOpenAssignmentForTask(ctx context.Context, taskID uuid.UUID) (AgentAssignment, error) {
	row := q.db.QueryRow(ctx, findOpenAssignmentForTask, taskID)
	var i AgentAssignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.FromPrincipal,
		&i.Ask,
		&i.GatheredContext,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertAgentAssignment = `-- name: InsertAgentAssignment :one
INSERT INTO agent_assignments (task_id, stage, from_principal, ask, gathered_context)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, stage, from_principal, ask, gathered_context, created_at, resolved_at
`

type InsertAgentAssignmentParams struct {
	TaskID          uuid.UUID       `json:"task_id"`
	Stage           ChainStage      `json:"stage"`
	FromPrincipal   *string         `json:"from_principal"`
	Ask             string          `json:"ask"`
	GatheredContext json.RawMessage `json:"gathered_context"`
}

// Insert into agent_assignments; trg_assign_notify fires IDs-only pg_notify.
// Returns the full row so callers (chain workflow / audit) don't need a second
// SELECT for created_at, etc.
func (q *Queries) InsertAgentAssignment(ctx context.Context, arg InsertAgentAssignmentParams) (AgentAssignment, error) {
	row := q.db.QueryRow(ctx, insertAgentAssignment,
		arg.TaskID,
		arg.Stage,
		arg.FromPrincipal,
		arg.Ask,
		arg.GatheredContext,
	)
	var i AgentAssignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.FromPrincipal,
		&i.Ask,
		&i.GatheredContext,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const resolveAssignment = `-- name: ResolveAssignment :one
UPDATE agent_assignments
SET resolved_at = $1::timestamptz
WHERE id = $2::uuid
  AND resolved_at IS NULL
RETURNING id, task_id, stage, from_principal, ask, gathered_context, created_at, resolved_at
`

type ResolveAssignmentParams struct {
	ResolvedAt time.Time `json:"resolved_at"`
	ID         uuid.UUID `json:"id"`
}

// Idempotent close: only updates an open row. Returns the closed row, or no
// row (sql.ErrNoRows) if the assignment was already resolved.
func (q *Queries) ResolveAssignment(ctx context.Context, arg ResolveAssignmentParams) (AgentAssignment, error) {
	row := q.db.QueryRow(ctx, resolveAssignment, arg.ResolvedAt, arg.ID)
	var i AgentAssignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.FromPrincipal,
		&i.Ask,
		&i.GatheredContext,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
