// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditMessage = `-- name: InsertAuditMessage :one
INSERT INTO audit_messages (id, task_id, from_principal, to_principal, in_reply_to, kind, payload, at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::uuid,
    $6::text,
    $7::jsonb,
    COALESCE($8::timestamptz, now())
)
RETURNING id, task_id, from_principal, to_principal, in_reply_to, kind, payload, at
`

type InsertAuditMessageParams struct {
	ID            uuid.UUID          `json:"id"`
	TaskID        pgtype.UUID        `json:"task_id"`
	FromPrincipal string             `json:"from_principal"`
	ToPrincipal   *string            `json:"to_principal"`
	InReplyTo     pgtype.UUID        `json:"in_reply_to"`
	Kind          string             `json:"kind"`
	Payload       json.RawMessage    `json:"payload"`
	At            pgtype.Timestamptz `json:"at"`
}

// Write one audit row. The caller passes id (generated client-side so it can
// be referenced by later in_reply_to chains without a round trip) and `at`
// (defaults to now() if zero/null — but we pass it explicitly to keep
// timestamps deterministic when needed).
func (q *Queries) InsertAuditMessage(ctx context.Context, arg InsertAuditMessageParams) (AuditMessage, error) {
	row := q.db.QueryRow(ctx, insertAuditMessage,
		arg.ID,
		arg.TaskID,
		arg.FromPrincipal,
		arg.ToPrincipal,
		arg.InReplyTo,
		arg.Kind,
		arg.Payload,
		arg.At,
	)
	var i AuditMessage
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromPrincipal,
		&i.ToPrincipal,
		&i.InReplyTo,
		&i.Kind,
		&i.Payload,
		&i.At,
	)
	return i, err
}

const latestTransitionForTask = `-- name: LatestTransitionForTask :one
SELECT id, task_id, from_principal, to_principal, in_reply_to, kind, payload, at
FROM audit_messages
WHERE task_id = $1::uuid
  AND kind IN ('state_transition','stage_advance','workflow_started','workflow_cancelled','assignment_created','assignment_resolved')
ORDER BY at DESC, id DESC
LIMIT 1
`

// Returns the most recent audit row for a task whose kind is one of the
// "transition" classes; used to wire in_reply_to on the next transition.
func (q *Queries) LatestTransitionForTask(ctx context.Context, taskID uuid.UUID) (AuditMessage, error) {
	row := q.db.QueryRow(ctx, latestTransitionForTask, taskID)
	var i AuditMessage
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromPrincipal,
		&i.ToPrincipal,
		&i.InReplyTo,
		&i.Kind,
		&i.Payload,
		&i.At,
	)
	return i, err
}

const listAuditForTask = `-- name: ListAuditForTask :many
SELECT id, task_id, from_principal, to_principal, in_reply_to, kind, payload, at
FROM audit_messages
WHERE task_id = $1::uuid
ORDER BY at ASC, id ASC
`

// Full audit DAG for a task, in chronological order. Used by tests that
// assert per-transition rows and in_reply_to wiring.
func (q *Queries) ListAuditForTask(ctx context.Context, taskID uuid.UUID) ([]AuditMessage, error) {
	rows, err := q.db.Query(ctx, listAuditForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditMessage
	for rows.Next() {
		var i AuditMessage
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FromPrincipal,
			&i.ToPrincipal,
			&i.InReplyTo,
			&i.Kind,
			&i.Payload,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
