// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calibration.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const candidateRoutinesForSweep = `-- name: CandidateRoutinesForSweep :many
SELECT tool_id, routine_fingerprint
FROM tool_outcomes
WHERE routine_fingerprint IS NOT NULL
  AND matured_at IS NOT NULL
  AND matured_at <= now()
GROUP BY tool_id, routine_fingerprint
`

type CandidateRoutinesForSweepRow struct {
	ToolID             uuid.UUID `json:"tool_id"`
	RoutineFingerprint *string   `json:"routine_fingerprint"`
}

// Distinct (tool, fingerprint) groups with at least one matured outcome — the
// sweep's work-list. Bounded by O(tools × routines).
func (q *Queries) CandidateRoutinesForSweep(ctx context.Context) ([]CandidateRoutinesForSweepRow, error) {
	rows, err := q.db.Query(ctx, candidateRoutinesForSweep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateRoutinesForSweepRow
	for rows.Next() {
		var i CandidateRoutinesForSweepRow
		if err := rows.Scan(&i.ToolID, &i.RoutineFingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenPromotionProposals = `-- name: CountOpenPromotionProposals :one
SELECT COUNT(*)::int AS n
FROM pending_decisions
WHERE kind = 'promotion_proposal' AND resolved_at IS NULL
`

func (q *Queries) CountOpenPromotionProposals(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOpenPromotionProposals)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const dismissalsByConnector = `-- name: DismissalsByConnector :many
SELECT t.id AS task_id,
       am.payload->>'reason' AS reason,
       am.at AS dismissed_at
FROM tasks t
JOIN intake_signals s ON t.intake_signal_id = s.id
JOIN audit_messages am ON am.task_id = t.id
  AND am.kind = 'state_transition'
  AND am.payload->>'to' = 'dismissed'
WHERE s.connector_id = $1
  AND am.at >= $2
ORDER BY am.at DESC
`

type DismissalsByConnectorParams struct {
	ConnectorID pgtype.UUID `json:"connector_id"`
	At          time.Time   `json:"at"`
}

type DismissalsByConnectorRow struct {
	TaskID      uuid.UUID   `json:"task_id"`
	Reason      interface{} `json:"reason"`
	DismissedAt time.Time   `json:"dismissed_at"`
}

// Dismissed intake-origin tasks attributable to a connector, newest first, with
// the owner-supplied dismissal reason (from the state_transition audit). Backs
// intake threshold-tightening + the [DISMISSAL_HISTORY] triage section.
func (q *Queries) DismissalsByConnector(ctx context.Context, arg DismissalsByConnectorParams) ([]DismissalsByConnectorRow, error) {
	rows, err := q.db.Query(ctx, dismissalsByConnector, arg.ConnectorID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DismissalsByConnectorRow
	for rows.Next() {
		var i DismissalsByConnectorRow
		if err := rows.Scan(&i.TaskID, &i.Reason, &i.DismissedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolForUpdate = `-- name: GetToolForUpdate :one

SELECT id, global_uri, name, rung, permissions, overseer_instructions, active_script_version, trust_score, mcp_server_id, input_schema, mcp_annotations, retired_at
FROM tools
WHERE id = $1
FOR UPDATE
`

// Phase 8 calibration queries. The trust-score + grant mutations are serialized
// via GetToolForUpdate (row lock) so concurrent outcomes near a band boundary
// never lose an update.
// Row-lock a tool for a serialized read-modify-write of trust_score / grants.
func (q *Queries) GetToolForUpdate(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolForUpdate, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
		&i.TrustScore,
		&i.McpServerID,
		&i.InputSchema,
		&i.McpAnnotations,
		&i.RetiredAt,
	)
	return i, err
}

const getTrustScore = `-- name: GetTrustScore :one
SELECT trust_score FROM tools WHERE id = $1
`

func (q *Queries) GetTrustScore(ctx context.Context, id uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTrustScore, id)
	var trust_score float64
	err := row.Scan(&trust_score)
	return trust_score, err
}

const insertPromotionProposal = `-- name: InsertPromotionProposal :one
INSERT INTO pending_decisions (id, task_id, tool_id, kind, payload)
VALUES ($1, $2, $3, 'promotion_proposal', $4)
RETURNING id, task_id, tool_id, kind, payload, created_at
`

type InsertPromotionProposalParams struct {
	ID      uuid.UUID       `json:"id"`
	TaskID  uuid.UUID       `json:"task_id"`
	ToolID  pgtype.UUID     `json:"tool_id"`
	Payload json.RawMessage `json:"payload"`
}

type InsertPromotionProposalRow struct {
	ID        uuid.UUID       `json:"id"`
	TaskID    uuid.UUID       `json:"task_id"`
	ToolID    pgtype.UUID     `json:"tool_id"`
	Kind      DecisionKind    `json:"kind"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

// The sweep writes a promotion_proposal pending_decisions row at a caller-
// supplied id (so the audit can reference it). The AFTER INSERT trigger
// pg_notify's tendant_events so the inbox surfaces it.
func (q *Queries) InsertPromotionProposal(ctx context.Context, arg InsertPromotionProposalParams) (InsertPromotionProposalRow, error) {
	row := q.db.QueryRow(ctx, insertPromotionProposal,
		arg.ID,
		arg.TaskID,
		arg.ToolID,
		arg.Payload,
	)
	var i InsertPromotionProposalRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ToolID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertRoutineGrant = `-- name: InsertRoutineGrant :one
INSERT INTO tool_routine_grants (tool_id, routine_fingerprint, evidence, granted_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tool_id, routine_fingerprint, evidence, granted_by, granted_at, revoked_at
`

type InsertRoutineGrantParams struct {
	ToolID             uuid.UUID       `json:"tool_id"`
	RoutineFingerprint string          `json:"routine_fingerprint"`
	Evidence           json.RawMessage `json:"evidence"`
	GrantedBy          string          `json:"granted_by"`
}

func (q *Queries) InsertRoutineGrant(ctx context.Context, arg InsertRoutineGrantParams) (ToolRoutineGrant, error) {
	row := q.db.QueryRow(ctx, insertRoutineGrant,
		arg.ToolID,
		arg.RoutineFingerprint,
		arg.Evidence,
		arg.GrantedBy,
	)
	var i ToolRoutineGrant
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.RoutineFingerprint,
		&i.Evidence,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const latestDeclinedPromotionAt = `-- name: LatestDeclinedPromotionAt :one
SELECT resolved_at
FROM pending_decisions
WHERE tool_id = $1
  AND kind = 'promotion_proposal'
  AND resolved_at IS NOT NULL
  AND resolution->>'accepted' = 'false'
  AND payload->>'routine_fingerprint' = $2::text
ORDER BY resolved_at DESC
LIMIT 1
`

type LatestDeclinedPromotionAtParams struct {
	ToolID             pgtype.UUID `json:"tool_id"`
	RoutineFingerprint string      `json:"routine_fingerprint"`
}

// The most-recent declined proposal's resolution time for a (tool, fingerprint)
// — backs the decline-cooldown (no re-propose until a NEW matured outcome).
func (q *Queries) LatestDeclinedPromotionAt(ctx context.Context, arg LatestDeclinedPromotionAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestDeclinedPromotionAt, arg.ToolID, arg.RoutineFingerprint)
	var resolved_at pgtype.Timestamptz
	err := row.Scan(&resolved_at)
	return resolved_at, err
}

const latestMaturedOutcomeForRoutine = `-- name: LatestMaturedOutcomeForRoutine :one
SELECT task_id, at, matured_at
FROM tool_outcomes
WHERE tool_id = $1
  AND routine_fingerprint = $2
  AND matured_at IS NOT NULL
  AND matured_at <= now()
  AND outcome = 'clean'
ORDER BY at DESC
LIMIT 1
`

type LatestMaturedOutcomeForRoutineParams struct {
	ToolID             uuid.UUID `json:"tool_id"`
	RoutineFingerprint *string   `json:"routine_fingerprint"`
}

type LatestMaturedOutcomeForRoutineRow struct {
	TaskID    uuid.UUID          `json:"task_id"`
	At        time.Time          `json:"at"`
	MaturedAt pgtype.Timestamptz `json:"matured_at"`
}

// The representative task (most-recent matured-clean outcome's task) + its
// maturation timestamp (used for the decline-cooldown check).
func (q *Queries) LatestMaturedOutcomeForRoutine(ctx context.Context, arg LatestMaturedOutcomeForRoutineParams) (LatestMaturedOutcomeForRoutineRow, error) {
	row := q.db.QueryRow(ctx, latestMaturedOutcomeForRoutine, arg.ToolID, arg.RoutineFingerprint)
	var i LatestMaturedOutcomeForRoutineRow
	err := row.Scan(&i.TaskID, &i.At, &i.MaturedAt)
	return i, err
}

const latestOutcomeForToolTask = `-- name: LatestOutcomeForToolTask :one
SELECT routine_fingerprint
FROM tool_outcomes
WHERE tool_id = $1 AND task_id = $2
ORDER BY at DESC
LIMIT 1
`

type LatestOutcomeForToolTaskParams struct {
	ToolID uuid.UUID `json:"tool_id"`
	TaskID uuid.UUID `json:"task_id"`
}

// The routine fingerprint of the most-recent outcome a tool recorded under a
// task — the "affected routine" for owner flagOutcome.
func (q *Queries) LatestOutcomeForToolTask(ctx context.Context, arg LatestOutcomeForToolTaskParams) (*string, error) {
	row := q.db.QueryRow(ctx, latestOutcomeForToolTask, arg.ToolID, arg.TaskID)
	var routine_fingerprint *string
	err := row.Scan(&routine_fingerprint)
	return routine_fingerprint, err
}

const liveGrantExists = `-- name: LiveGrantExists :one
SELECT EXISTS (
  SELECT 1 FROM tool_routine_grants
  WHERE tool_id = $1
    AND routine_fingerprint = $2
    AND revoked_at IS NULL
) AS exists
`

type LiveGrantExistsParams struct {
	ToolID             uuid.UUID `json:"tool_id"`
	RoutineFingerprint string    `json:"routine_fingerprint"`
}

func (q *Queries) LiveGrantExists(ctx context.Context, arg LiveGrantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, liveGrantExists, arg.ToolID, arg.RoutineFingerprint)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const maturedCleanRatioByRoutine = `-- name: MaturedCleanRatioByRoutine :one
WITH recent AS (
  SELECT outcome
  FROM tool_outcomes
  WHERE tool_id = $1
    AND routine_fingerprint = $2
    AND matured_at IS NOT NULL
    AND matured_at <= now()
  ORDER BY at DESC
  LIMIT $3::int
)
SELECT
  COUNT(*)::int AS total,
  COUNT(*) FILTER (WHERE outcome = 'clean')::int AS clean
FROM recent
`

type MaturedCleanRatioByRoutineParams struct {
	ToolID             uuid.UUID `json:"tool_id"`
	RoutineFingerprint *string   `json:"routine_fingerprint"`
	WindowN            int32     `json:"window_n"`
}

type MaturedCleanRatioByRoutineRow struct {
	Total int32 `json:"total"`
	Clean int32 `json:"clean"`
}

// Over the last N matured outcomes for a (tool, fingerprint): clean and total.
func (q *Queries) MaturedCleanRatioByRoutine(ctx context.Context, arg MaturedCleanRatioByRoutineParams) (MaturedCleanRatioByRoutineRow, error) {
	row := q.db.QueryRow(ctx, maturedCleanRatioByRoutine, arg.ToolID, arg.RoutineFingerprint, arg.WindowN)
	var i MaturedCleanRatioByRoutineRow
	err := row.Scan(&i.Total, &i.Clean)
	return i, err
}

const openPromotionProposal = `-- name: OpenPromotionProposal :one
SELECT id, task_id, tool_id, kind, payload, created_at
FROM pending_decisions
WHERE tool_id = $1
  AND kind = 'promotion_proposal'
  AND resolved_at IS NULL
  AND payload->>'routine_fingerprint' = $2::text
ORDER BY created_at DESC
LIMIT 1
`

type OpenPromotionProposalParams struct {
	ToolID             pgtype.UUID `json:"tool_id"`
	RoutineFingerprint string      `json:"routine_fingerprint"`
}

type OpenPromotionProposalRow struct {
	ID        uuid.UUID       `json:"id"`
	TaskID    uuid.UUID       `json:"task_id"`
	ToolID    pgtype.UUID     `json:"tool_id"`
	Kind      DecisionKind    `json:"kind"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

// The open (unresolved) promotion_proposal for a (tool, fingerprint), if any.
// The fingerprint is matched against the frozen payload's routine_fingerprint.
func (q *Queries) OpenPromotionProposal(ctx context.Context, arg OpenPromotionProposalParams) (OpenPromotionProposalRow, error) {
	row := q.db.QueryRow(ctx, openPromotionProposal, arg.ToolID, arg.RoutineFingerprint)
	var i OpenPromotionProposalRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ToolID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const openPromotionProposalsForTool = `-- name: OpenPromotionProposalsForTool :many
SELECT id, task_id, tool_id, kind, payload, created_at
FROM pending_decisions
WHERE tool_id = $1
  AND kind = 'promotion_proposal'
  AND resolved_at IS NULL
`

type OpenPromotionProposalsForToolRow struct {
	ID        uuid.UUID       `json:"id"`
	TaskID    uuid.UUID       `json:"task_id"`
	ToolID    pgtype.UUID     `json:"tool_id"`
	Kind      DecisionKind    `json:"kind"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

// All open promotion proposals for a tool — withdrawn on demotion (FR-014).
func (q *Queries) OpenPromotionProposalsForTool(ctx context.Context, toolID pgtype.UUID) ([]OpenPromotionProposalsForToolRow, error) {
	rows, err := q.db.Query(ctx, openPromotionProposalsForTool, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenPromotionProposalsForToolRow
	for rows.Next() {
		var i OpenPromotionProposalsForToolRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ToolID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllGrantsForTool = `-- name: RevokeAllGrantsForTool :exec
UPDATE tool_routine_grants
   SET revoked_at = now()
 WHERE tool_id = $1
   AND revoked_at IS NULL
`

func (q *Queries) RevokeAllGrantsForTool(ctx context.Context, toolID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllGrantsForTool, toolID)
	return err
}

const revokeRoutineGrant = `-- name: RevokeRoutineGrant :exec
UPDATE tool_routine_grants
   SET revoked_at = now()
 WHERE tool_id = $1
   AND routine_fingerprint = $2
   AND revoked_at IS NULL
`

type RevokeRoutineGrantParams struct {
	ToolID             uuid.UUID `json:"tool_id"`
	RoutineFingerprint string    `json:"routine_fingerprint"`
}

func (q *Queries) RevokeRoutineGrant(ctx context.Context, arg RevokeRoutineGrantParams) error {
	_, err := q.db.Exec(ctx, revokeRoutineGrant, arg.ToolID, arg.RoutineFingerprint)
	return err
}

const setTrustScore = `-- name: SetTrustScore :one
UPDATE tools
   SET trust_score = $2,
       rung        = $3
 WHERE id = $1
RETURNING id, global_uri, name, rung, permissions, overseer_instructions, active_script_version, trust_score, mcp_server_id, input_schema, mcp_annotations, retired_at
`

type SetTrustScoreParams struct {
	ID         uuid.UUID `json:"id"`
	TrustScore float64   `json:"trust_score"`
	Rung       string    `json:"rung"`
}

// Set the continuous score and keep the rung text cache in sync (band string).
func (q *Queries) SetTrustScore(ctx context.Context, arg SetTrustScoreParams) (Tool, error) {
	row := q.db.QueryRow(ctx, setTrustScore, arg.ID, arg.TrustScore, arg.Rung)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
		&i.TrustScore,
		&i.McpServerID,
		&i.InputSchema,
		&i.McpAnnotations,
		&i.RetiredAt,
	)
	return i, err
}

const toolsActedUnderTask = `-- name: ToolsActedUnderTask :many
SELECT DISTINCT tool_id
FROM tool_outcomes
WHERE task_id = $1
`

// Distinct tools that recorded an outcome under a task — the cancel-demotion
// work-list.
func (q *Queries) ToolsActedUnderTask(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, toolsActedUnderTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tool_id uuid.UUID
		if err := rows.Scan(&tool_id); err != nil {
			return nil, err
		}
		items = append(items, tool_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
