// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chains.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const endChainWorkflow = `-- name: EndChainWorkflow :exec
UPDATE chain_workflows
SET status = $1::text,
    ended_at = $2::timestamptz
WHERE task_id = $3::uuid
  AND ended_at IS NULL
`

type EndChainWorkflowParams struct {
	Status  string    `json:"status"`
	EndedAt time.Time `json:"ended_at"`
	TaskID  uuid.UUID `json:"task_id"`
}

// Close the live chain workflow row for a task. Idempotent against an
// already-closed row — UPDATE simply matches no rows on retry.
func (q *Queries) EndChainWorkflow(ctx context.Context, arg EndChainWorkflowParams) error {
	_, err := q.db.Exec(ctx, endChainWorkflow, arg.Status, arg.EndedAt, arg.TaskID)
	return err
}

const getLiveWorkflowForTask = `-- name: GetLiveWorkflowForTask :one
SELECT id, task_id, dbos_workflow_id, status, started_at, ended_at
FROM chain_workflows
WHERE task_id = $1 AND ended_at IS NULL
LIMIT 1
`

// Returns the still-live chain workflow row for a task. pgx.ErrNoRows when
// nothing is live (task hasn't been kicked off yet or already terminated).
func (q *Queries) GetLiveWorkflowForTask(ctx context.Context, taskID uuid.UUID) (ChainWorkflow, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowForTask, taskID)
	var i ChainWorkflow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DbosWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertChainWorkflow = `-- name: InsertChainWorkflow :one
INSERT INTO chain_workflows (task_id, dbos_workflow_id, status, started_at)
VALUES ($1, $2, 'pending', now())
RETURNING id, task_id, dbos_workflow_id, status, started_at, ended_at
`

type InsertChainWorkflowParams struct {
	TaskID         uuid.UUID `json:"task_id"`
	DbosWorkflowID string    `json:"dbos_workflow_id"`
}

// Pre-creates the chain_workflows row before dbos.RunWorkflow attaches. The
// partial-unique index idx_chainwf_task_live keeps one live row per task.
func (q *Queries) InsertChainWorkflow(ctx context.Context, arg InsertChainWorkflowParams) (ChainWorkflow, error) {
	row := q.db.QueryRow(ctx, insertChainWorkflow, arg.TaskID, arg.DbosWorkflowID)
	var i ChainWorkflow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DbosWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}
