// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config_entries.sql

package db

import (
	"context"
	"encoding/json"
)

const deleteConfigEntry = `-- name: DeleteConfigEntry :exec
DELETE FROM config_entries WHERE key = $1
`

func (q *Queries) DeleteConfigEntry(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteConfigEntry, key)
	return err
}

const getConfigEntry = `-- name: GetConfigEntry :one
SELECT key, value, updated_at FROM config_entries WHERE key = $1
`

func (q *Queries) GetConfigEntry(ctx context.Context, key string) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, getConfigEntry, key)
	var i ConfigEntry
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listConfigEntries = `-- name: ListConfigEntries :many
SELECT key, value, updated_at FROM config_entries ORDER BY key
`

func (q *Queries) ListConfigEntries(ctx context.Context) ([]ConfigEntry, error) {
	rows, err := q.db.Query(ctx, listConfigEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigEntry
	for rows.Next() {
		var i ConfigEntry
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigEntry = `-- name: UpsertConfigEntry :one
INSERT INTO config_entries (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING key, value, updated_at
`

type UpsertConfigEntryParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) UpsertConfigEntry(ctx context.Context, arg UpsertConfigEntryParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, upsertConfigEntry, arg.Key, arg.Value)
	var i ConfigEntry
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
