// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectors.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getConnectorConfig = `-- name: GetConnectorConfig :one
SELECT id, connector_type, filter, schedule, disposition_rules, enabled, created_at FROM connector_configs WHERE id = $1
`

func (q *Queries) GetConnectorConfig(ctx context.Context, id uuid.UUID) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, getConnectorConfig, id)
	var i ConnectorConfig
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Filter,
		&i.Schedule,
		&i.DispositionRules,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceCredential = `-- name: GetSourceCredential :one
SELECT connector_id, encrypted, expires_at FROM source_credentials WHERE connector_id = $1
`

func (q *Queries) GetSourceCredential(ctx context.Context, connectorID uuid.UUID) (SourceCredential, error) {
	row := q.db.QueryRow(ctx, getSourceCredential, connectorID)
	var i SourceCredential
	err := row.Scan(&i.ConnectorID, &i.Encrypted, &i.ExpiresAt)
	return i, err
}

const listConnectorConfigs = `-- name: ListConnectorConfigs :many
SELECT id, connector_type, filter, schedule, disposition_rules, enabled, created_at FROM connector_configs ORDER BY created_at
`

// Backs the owner-only `connectors` query.
func (q *Queries) ListConnectorConfigs(ctx context.Context) ([]ConnectorConfig, error) {
	rows, err := q.db.Query(ctx, listConnectorConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectorConfig
	for rows.Next() {
		var i ConnectorConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorType,
			&i.Filter,
			&i.Schedule,
			&i.DispositionRules,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledConnectorConfigs = `-- name: ListEnabledConnectorConfigs :many
SELECT id, connector_type, filter, schedule, disposition_rules, enabled, created_at FROM connector_configs WHERE enabled = true ORDER BY created_at
`

// Boot rehydration: re-create a DBOS schedule for every enabled connector.
func (q *Queries) ListEnabledConnectorConfigs(ctx context.Context) ([]ConnectorConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledConnectorConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectorConfig
	for rows.Next() {
		var i ConnectorConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorType,
			&i.Filter,
			&i.Schedule,
			&i.DispositionRules,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectorEnabled = `-- name: SetConnectorEnabled :one
UPDATE connector_configs SET enabled = $2 WHERE id = $1 RETURNING id, connector_type, filter, schedule, disposition_rules, enabled, created_at
`

type SetConnectorEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

// enableConnector (owner-only). Flips the enabled flag; the resolver pairs this
// with scheduler.CreateSchedule / DeleteSchedule.
func (q *Queries) SetConnectorEnabled(ctx context.Context, arg SetConnectorEnabledParams) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, setConnectorEnabled, arg.ID, arg.Enabled)
	var i ConnectorConfig
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Filter,
		&i.Schedule,
		&i.DispositionRules,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const upsertConnectorConfig = `-- name: UpsertConnectorConfig :one
INSERT INTO connector_configs (id, connector_type, filter, schedule, disposition_rules, enabled)
VALUES ($1, $2, $3, $4, $5, false)
ON CONFLICT (id) DO UPDATE
  SET connector_type    = EXCLUDED.connector_type,
      filter            = EXCLUDED.filter,
      schedule          = EXCLUDED.schedule,
      disposition_rules = EXCLUDED.disposition_rules
RETURNING id, connector_type, filter, schedule, disposition_rules, enabled, created_at
`

type UpsertConnectorConfigParams struct {
	ID               uuid.UUID       `json:"id"`
	ConnectorType    string          `json:"connector_type"`
	Filter           json.RawMessage `json:"filter"`
	Schedule         *string         `json:"schedule"`
	DispositionRules json.RawMessage `json:"disposition_rules"`
}

// setConnectorConfig (owner-only). Upserts the integration's config; `enabled`
// is left untouched on update and defaults false on insert — enable/disable is
// the separate enableConnector mutation (which (de)registers the DBOS schedule).
func (q *Queries) UpsertConnectorConfig(ctx context.Context, arg UpsertConnectorConfigParams) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, upsertConnectorConfig,
		arg.ID,
		arg.ConnectorType,
		arg.Filter,
		arg.Schedule,
		arg.DispositionRules,
	)
	var i ConnectorConfig
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Filter,
		&i.Schedule,
		&i.DispositionRules,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSourceCredential = `-- name: UpsertSourceCredential :exec
INSERT INTO source_credentials (connector_id, encrypted, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (connector_id) DO UPDATE
  SET encrypted = EXCLUDED.encrypted, expires_at = EXCLUDED.expires_at
`

type UpsertSourceCredentialParams struct {
	ConnectorID uuid.UUID          `json:"connector_id"`
	Encrypted   []byte             `json:"encrypted"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Seal-at-rest (research R7): `encrypted` is crypto.Seal(token bundle JSON).
func (q *Queries) UpsertSourceCredential(ctx context.Context, arg UpsertSourceCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertSourceCredential, arg.ConnectorID, arg.Encrypted, arg.ExpiresAt)
	return err
}
