// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingDecisionByID = `-- name: GetPendingDecisionByID :one
SELECT id, task_id, tool_id, kind, payload, disclosure_class, created_at,
       resolved_at, resolution, frozen_payload, workflow_id, decision_topic,
       notify_workflow_id
FROM pending_decisions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPendingDecisionByID(ctx context.Context, id uuid.UUID) (PendingDecision, error) {
	row := q.db.QueryRow(ctx, getPendingDecisionByID, id)
	var i PendingDecision
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ToolID,
		&i.Kind,
		&i.Payload,
		&i.DisclosureClass,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Resolution,
		&i.FrozenPayload,
		&i.WorkflowID,
		&i.DecisionTopic,
		&i.NotifyWorkflowID,
	)
	return i, err
}

const insertApprovalDecision = `-- name: InsertApprovalDecision :exec
INSERT INTO pending_decisions
  (id, task_id, tool_id, kind, payload, frozen_payload, workflow_id, decision_topic, notify_workflow_id)
VALUES ($1, $2, $3, 'approval_request', $4, $4, $5, $6, $7)
`

type InsertApprovalDecisionParams struct {
	ID               uuid.UUID       `json:"id"`
	TaskID           uuid.UUID       `json:"task_id"`
	ToolID           pgtype.UUID     `json:"tool_id"`
	Payload          json.RawMessage `json:"payload"`
	WorkflowID       *string         `json:"workflow_id"`
	DecisionTopic    *string         `json:"decision_topic"`
	NotifyWorkflowID *string         `json:"notify_workflow_id"`
}

// Compose an agent-initiated approval_request with a deterministic id and the
// back-channel target (notify_workflow_id) the tool-call workflow Sends its
// outcome to. frozen_payload is the byte-for-byte call that will dispatch.
func (q *Queries) InsertApprovalDecision(ctx context.Context, arg InsertApprovalDecisionParams) error {
	_, err := q.db.Exec(ctx, insertApprovalDecision,
		arg.ID,
		arg.TaskID,
		arg.ToolID,
		arg.Payload,
		arg.WorkflowID,
		arg.DecisionTopic,
		arg.NotifyWorkflowID,
	)
	return err
}

const listOpenPendingDecisions = `-- name: ListOpenPendingDecisions :many
SELECT id, task_id, tool_id, kind, payload, disclosure_class, created_at,
       resolved_at, resolution, frozen_payload, workflow_id, decision_topic,
       notify_workflow_id
FROM pending_decisions
WHERE resolved_at IS NULL
ORDER BY created_at DESC, id DESC
`

// Phase 2 owner-only: returns every open pending_decision. Phase 3 will
// tighten the viewer scope rules.
func (q *Queries) ListOpenPendingDecisions(ctx context.Context) ([]PendingDecision, error) {
	rows, err := q.db.Query(ctx, listOpenPendingDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingDecision
	for rows.Next() {
		var i PendingDecision
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ToolID,
			&i.Kind,
			&i.Payload,
			&i.DisclosureClass,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Resolution,
			&i.FrozenPayload,
			&i.WorkflowID,
			&i.DecisionTopic,
			&i.NotifyWorkflowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePendingDecision = `-- name: ResolvePendingDecision :one
UPDATE pending_decisions
   SET resolved_at = $2,
       resolution  = $3
 WHERE id = $1
   AND resolved_at IS NULL
RETURNING id, task_id, tool_id, kind, payload, disclosure_class, created_at,
          resolved_at, resolution, frozen_payload, workflow_id, decision_topic,
          notify_workflow_id
`

type ResolvePendingDecisionParams struct {
	ID         uuid.UUID          `json:"id"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	Resolution []byte             `json:"resolution"`
}

// Phase 3: called by approveArtifact / rejectApproval. First-write-wins on
// resolved_at — the row is only updated if it hasn't already been resolved.
// Returns the row regardless (the caller compares pre-state to detect a
// no-op).
func (q *Queries) ResolvePendingDecision(ctx context.Context, arg ResolvePendingDecisionParams) (PendingDecision, error) {
	row := q.db.QueryRow(ctx, resolvePendingDecision, arg.ID, arg.ResolvedAt, arg.Resolution)
	var i PendingDecision
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ToolID,
		&i.Kind,
		&i.Payload,
		&i.DisclosureClass,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Resolution,
		&i.FrozenPayload,
		&i.WorkflowID,
		&i.DecisionTopic,
		&i.NotifyWorkflowID,
	)
	return i, err
}
