// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPendingDecisionByID = `-- name: GetPendingDecisionByID :one
SELECT id, task_id, tool_id, kind, payload, disclosure_class, created_at, resolved_at, resolution
FROM pending_decisions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPendingDecisionByID(ctx context.Context, id uuid.UUID) (PendingDecision, error) {
	row := q.db.QueryRow(ctx, getPendingDecisionByID, id)
	var i PendingDecision
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ToolID,
		&i.Kind,
		&i.Payload,
		&i.DisclosureClass,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const listOpenPendingDecisions = `-- name: ListOpenPendingDecisions :many
SELECT id, task_id, tool_id, kind, payload, disclosure_class, created_at, resolved_at, resolution
FROM pending_decisions
WHERE resolved_at IS NULL
ORDER BY created_at DESC, id DESC
`

// Phase 2 owner-only: returns every open pending_decision. Phase 3 will
// tighten the viewer scope rules.
func (q *Queries) ListOpenPendingDecisions(ctx context.Context) ([]PendingDecision, error) {
	rows, err := q.db.Query(ctx, listOpenPendingDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingDecision
	for rows.Next() {
		var i PendingDecision
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ToolID,
			&i.Kind,
			&i.Payload,
			&i.DisclosureClass,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
