// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1 AND owner_id = $2
`

type DeleteDeviceTokenParams struct {
	Token   string    `json:"token"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.OwnerID)
	return err
}

const deleteDeviceTokensByValue = `-- name: DeleteDeviceTokensByValue :exec
DELETE FROM device_tokens WHERE token = ANY($1::text[])
`

func (q *Queries) DeleteDeviceTokensByValue(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokensByValue, dollar_1)
	return err
}

const listDeviceTokensForPrincipal = `-- name: ListDeviceTokensForPrincipal :many
SELECT token, owner_id, platform, created_at
FROM device_tokens
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeviceTokensForPrincipal(ctx context.Context, ownerID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForPrincipal, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.Token,
			&i.OwnerID,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTokensForPrincipalByGlobalURI = `-- name: ListDeviceTokensForPrincipalByGlobalURI :many
SELECT dt.token, dt.owner_id, dt.platform, dt.created_at
FROM device_tokens dt
JOIN principals p ON p.id = dt.owner_id
WHERE p.global_uri = $1
ORDER BY dt.created_at DESC
`

func (q *Queries) ListDeviceTokensForPrincipalByGlobalURI(ctx context.Context, globalUri string) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForPrincipalByGlobalURI, globalUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.Token,
			&i.OwnerID,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (token, owner_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
  SET owner_id = EXCLUDED.owner_id,
      platform = EXCLUDED.platform
RETURNING token, owner_id, platform, created_at
`

type UpsertDeviceTokenParams struct {
	Token    string         `json:"token"`
	OwnerID  uuid.UUID      `json:"owner_id"`
	Platform DevicePlatform `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.Token, arg.OwnerID, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.Token,
		&i.OwnerID,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}
