// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const acquireEmbeddingTransitionLock = `-- name: AcquireEmbeddingTransitionLock :exec

SELECT pg_advisory_xact_lock(7180294615)
`

// Embedding subsystem queries. The registry (embedding_versions) and the
// dimension-agnostic vector writes live here as sqlc; only the KNN similarity
// search is hand-written pgx (its ::vector(dim) cast puts a runtime dimension in
// the type, which sqlc cannot parameterize). See internal/embedding/store.go.
// Serializes every version transition (a fixed advisory-lock key) so the
// single-active / single-building invariants can't race under rapid changes.
func (q *Queries) AcquireEmbeddingTransitionLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireEmbeddingTransitionLock)
	return err
}

const activateEmbeddingVersion = `-- name: ActivateEmbeddingVersion :exec
UPDATE embedding_versions
SET status = 'active', activated_at = now()
WHERE version = $1
`

func (q *Queries) ActivateEmbeddingVersion(ctx context.Context, version int32) error {
	_, err := q.db.Exec(ctx, activateEmbeddingVersion, version)
	return err
}

const clearEmbeddingBlue = `-- name: ClearEmbeddingBlue :exec
UPDATE embeddings SET embedding_blue = NULL WHERE embedding_blue IS NOT NULL
`

func (q *Queries) ClearEmbeddingBlue(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearEmbeddingBlue)
	return err
}

const clearEmbeddingGreen = `-- name: ClearEmbeddingGreen :exec
UPDATE embeddings SET embedding_green = NULL WHERE embedding_green IS NOT NULL
`

func (q *Queries) ClearEmbeddingGreen(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearEmbeddingGreen)
	return err
}

const countEmbeddedBlue = `-- name: CountEmbeddedBlue :one
SELECT count(*) FROM embeddings
WHERE source_type = $1 AND embedding_blue IS NOT NULL
`

func (q *Queries) CountEmbeddedBlue(ctx context.Context, sourceType string) (int64, error) {
	row := q.db.QueryRow(ctx, countEmbeddedBlue, sourceType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmbeddedGreen = `-- name: CountEmbeddedGreen :one
SELECT count(*) FROM embeddings
WHERE source_type = $1 AND embedding_green IS NOT NULL
`

func (q *Queries) CountEmbeddedGreen(ctx context.Context, sourceType string) (int64, error) {
	row := q.db.QueryRow(ctx, countEmbeddedGreen, sourceType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveEmbeddingVersion = `-- name: GetActiveEmbeddingVersion :one
SELECT version, slot, provider, model, dimension, config_hash, status, workflow_id, created_at, activated_at FROM embedding_versions WHERE status = 'active'
`

func (q *Queries) GetActiveEmbeddingVersion(ctx context.Context) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, getActiveEmbeddingVersion)
	var i EmbeddingVersion
	err := row.Scan(
		&i.Version,
		&i.Slot,
		&i.Provider,
		&i.Model,
		&i.Dimension,
		&i.ConfigHash,
		&i.Status,
		&i.WorkflowID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getBuildingEmbeddingVersion = `-- name: GetBuildingEmbeddingVersion :one
SELECT version, slot, provider, model, dimension, config_hash, status, workflow_id, created_at, activated_at FROM embedding_versions WHERE status = 'building'
`

func (q *Queries) GetBuildingEmbeddingVersion(ctx context.Context) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, getBuildingEmbeddingVersion)
	var i EmbeddingVersion
	err := row.Scan(
		&i.Version,
		&i.Slot,
		&i.Provider,
		&i.Model,
		&i.Dimension,
		&i.ConfigHash,
		&i.Status,
		&i.WorkflowID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getEmbeddingContentHash = `-- name: GetEmbeddingContentHash :one
SELECT content_hash FROM embeddings
WHERE source_type = $1 AND source_id = $2
`

type GetEmbeddingContentHashParams struct {
	SourceType string    `json:"source_type"`
	SourceID   uuid.UUID `json:"source_id"`
}

// Used to skip recompute when the source text hasn't changed.
func (q *Queries) GetEmbeddingContentHash(ctx context.Context, arg GetEmbeddingContentHashParams) (string, error) {
	row := q.db.QueryRow(ctx, getEmbeddingContentHash, arg.SourceType, arg.SourceID)
	var content_hash string
	err := row.Scan(&content_hash)
	return content_hash, err
}

const getEmbeddingVersion = `-- name: GetEmbeddingVersion :one
SELECT version, slot, provider, model, dimension, config_hash, status, workflow_id, created_at, activated_at FROM embedding_versions WHERE version = $1
`

func (q *Queries) GetEmbeddingVersion(ctx context.Context, version int32) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, getEmbeddingVersion, version)
	var i EmbeddingVersion
	err := row.Scan(
		&i.Version,
		&i.Slot,
		&i.Provider,
		&i.Model,
		&i.Dimension,
		&i.ConfigHash,
		&i.Status,
		&i.WorkflowID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getEmbeddingVersionForUpdate = `-- name: GetEmbeddingVersionForUpdate :one
SELECT version, slot, provider, model, dimension, config_hash, status, workflow_id, created_at, activated_at FROM embedding_versions WHERE version = $1 FOR UPDATE
`

// Re-read at flip time to confirm the build is still 'building' before going live.
func (q *Queries) GetEmbeddingVersionForUpdate(ctx context.Context, version int32) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, getEmbeddingVersionForUpdate, version)
	var i EmbeddingVersion
	err := row.Scan(
		&i.Version,
		&i.Slot,
		&i.Provider,
		&i.Model,
		&i.Dimension,
		&i.ConfigHash,
		&i.Status,
		&i.WorkflowID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const insertEmbeddingVersion = `-- name: InsertEmbeddingVersion :one
INSERT INTO embedding_versions (version, slot, provider, model, dimension, config_hash, status)
VALUES ($1, $2, $3, $4, $5, $6, 'building')
RETURNING version, slot, provider, model, dimension, config_hash, status, workflow_id, created_at, activated_at
`

type InsertEmbeddingVersionParams struct {
	Version    int32  `json:"version"`
	Slot       string `json:"slot"`
	Provider   string `json:"provider"`
	Model      string `json:"model"`
	Dimension  int32  `json:"dimension"`
	ConfigHash string `json:"config_hash"`
}

func (q *Queries) InsertEmbeddingVersion(ctx context.Context, arg InsertEmbeddingVersionParams) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, insertEmbeddingVersion,
		arg.Version,
		arg.Slot,
		arg.Provider,
		arg.Model,
		arg.Dimension,
		arg.ConfigHash,
	)
	var i EmbeddingVersion
	err := row.Scan(
		&i.Version,
		&i.Slot,
		&i.Provider,
		&i.Model,
		&i.Dimension,
		&i.ConfigHash,
		&i.Status,
		&i.WorkflowID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const listRetiredEmbeddingVersionsForSlot = `-- name: ListRetiredEmbeddingVersionsForSlot :many
SELECT version, slot, provider, model, dimension, config_hash, status, workflow_id, created_at, activated_at FROM embedding_versions WHERE status = 'retired' AND slot = $1
`

func (q *Queries) ListRetiredEmbeddingVersionsForSlot(ctx context.Context, slot string) ([]EmbeddingVersion, error) {
	rows, err := q.db.Query(ctx, listRetiredEmbeddingVersionsForSlot, slot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmbeddingVersion
	for rows.Next() {
		var i EmbeddingVersion
		if err := rows.Scan(
			&i.Version,
			&i.Slot,
			&i.Provider,
			&i.Model,
			&i.Dimension,
			&i.ConfigHash,
			&i.Status,
			&i.WorkflowID,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEmbeddingVersion = `-- name: MaxEmbeddingVersion :one
SELECT COALESCE(MAX(version), 0)::int AS max FROM embedding_versions
`

func (q *Queries) MaxEmbeddingVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, maxEmbeddingVersion)
	var max int32
	err := row.Scan(&max)
	return max, err
}

const retireActiveEmbeddingVersionExcept = `-- name: RetireActiveEmbeddingVersionExcept :exec
UPDATE embedding_versions
SET status = 'retired'
WHERE status = 'active' AND version <> $1
`

// Demote the current active version (other than @keep) to retired during a flip.
func (q *Queries) RetireActiveEmbeddingVersionExcept(ctx context.Context, keep int32) error {
	_, err := q.db.Exec(ctx, retireActiveEmbeddingVersionExcept, keep)
	return err
}

const setEmbeddingVersionDimension = `-- name: SetEmbeddingVersionDimension :exec
UPDATE embedding_versions SET dimension = $1 WHERE version = $2
`

type SetEmbeddingVersionDimensionParams struct {
	Dimension int32 `json:"dimension"`
	Version   int32 `json:"version"`
}

// The actual vector length is known only after the first embed call.
func (q *Queries) SetEmbeddingVersionDimension(ctx context.Context, arg SetEmbeddingVersionDimensionParams) error {
	_, err := q.db.Exec(ctx, setEmbeddingVersionDimension, arg.Dimension, arg.Version)
	return err
}

const setEmbeddingVersionStatus = `-- name: SetEmbeddingVersionStatus :exec
UPDATE embedding_versions SET status = $1 WHERE version = $2
`

type SetEmbeddingVersionStatusParams struct {
	Status  string `json:"status"`
	Version int32  `json:"version"`
}

func (q *Queries) SetEmbeddingVersionStatus(ctx context.Context, arg SetEmbeddingVersionStatusParams) error {
	_, err := q.db.Exec(ctx, setEmbeddingVersionStatus, arg.Status, arg.Version)
	return err
}

const setEmbeddingVersionWorkflowID = `-- name: SetEmbeddingVersionWorkflowID :exec
UPDATE embedding_versions SET workflow_id = $1 WHERE version = $2
`

type SetEmbeddingVersionWorkflowIDParams struct {
	WorkflowID *string `json:"workflow_id"`
	Version    int32   `json:"version"`
}

func (q *Queries) SetEmbeddingVersionWorkflowID(ctx context.Context, arg SetEmbeddingVersionWorkflowIDParams) error {
	_, err := q.db.Exec(ctx, setEmbeddingVersionWorkflowID, arg.WorkflowID, arg.Version)
	return err
}

const upsertEmbeddingBlue = `-- name: UpsertEmbeddingBlue :exec

INSERT INTO embeddings (source_type, source_id, source_text, content_hash, embedding_blue, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (source_type, source_id) DO UPDATE
  SET source_text    = EXCLUDED.source_text,
      content_hash   = EXCLUDED.content_hash,
      embedding_blue = EXCLUDED.embedding_blue,
      updated_at     = now()
`

type UpsertEmbeddingBlueParams struct {
	SourceType  string           `json:"source_type"`
	SourceID    uuid.UUID        `json:"source_id"`
	SourceText  string           `json:"source_text"`
	ContentHash string           `json:"content_hash"`
	Embedding   *pgvector.Vector `json:"embedding"`
}

// Dimension-agnostic vector writes. Blue/green are a fixed pair (sqlc cannot
// parameterize a column identifier); the Store dispatches by active/idle slot.
func (q *Queries) UpsertEmbeddingBlue(ctx context.Context, arg UpsertEmbeddingBlueParams) error {
	_, err := q.db.Exec(ctx, upsertEmbeddingBlue,
		arg.SourceType,
		arg.SourceID,
		arg.SourceText,
		arg.ContentHash,
		arg.Embedding,
	)
	return err
}

const upsertEmbeddingGreen = `-- name: UpsertEmbeddingGreen :exec
INSERT INTO embeddings (source_type, source_id, source_text, content_hash, embedding_green, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (source_type, source_id) DO UPDATE
  SET source_text     = EXCLUDED.source_text,
      content_hash    = EXCLUDED.content_hash,
      embedding_green = EXCLUDED.embedding_green,
      updated_at      = now()
`

type UpsertEmbeddingGreenParams struct {
	SourceType  string           `json:"source_type"`
	SourceID    uuid.UUID        `json:"source_id"`
	SourceText  string           `json:"source_text"`
	ContentHash string           `json:"content_hash"`
	Embedding   *pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpsertEmbeddingGreen(ctx context.Context, arg UpsertEmbeddingGreenParams) error {
	_, err := q.db.Exec(ctx, upsertEmbeddingGreen,
		arg.SourceType,
		arg.SourceID,
		arg.SourceText,
		arg.ContentHash,
		arg.Embedding,
	)
	return err
}
