// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertFeedbackMessage = `-- name: InsertFeedbackMessage :one
INSERT INTO feedback_messages (decision_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, decision_id, role, content, created_at
`

type InsertFeedbackMessageParams struct {
	DecisionID uuid.UUID `json:"decision_id"`
	Role       string    `json:"role"`
	Content    string    `json:"content"`
}

// Append one turn to a feedback conversation. role is 'agent' or 'user'.
func (q *Queries) InsertFeedbackMessage(ctx context.Context, arg InsertFeedbackMessageParams) (FeedbackMessage, error) {
	row := q.db.QueryRow(ctx, insertFeedbackMessage, arg.DecisionID, arg.Role, arg.Content)
	var i FeedbackMessage
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedbackMessages = `-- name: ListFeedbackMessages :many
SELECT id, decision_id, role, content, created_at
FROM feedback_messages
WHERE decision_id = $1
ORDER BY created_at ASC, id ASC
`

// The full thread for a FeedbackRequest, oldest-first.
func (q *Queries) ListFeedbackMessages(ctx context.Context, decisionID uuid.UUID) ([]FeedbackMessage, error) {
	rows, err := q.db.Query(ctx, listFeedbackMessages, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackMessage
	for rows.Next() {
		var i FeedbackMessage
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedbackDecisionPayload = `-- name: SetFeedbackDecisionPayload :exec
UPDATE pending_decisions
   SET payload = $2
 WHERE id = $1
   AND kind = 'feedback_request'
   AND resolved_at IS NULL
`

type SetFeedbackDecisionPayloadParams struct {
	ID      uuid.UUID       `json:"id"`
	Payload json.RawMessage `json:"payload"`
}

// Overwrite a feedback_request decision's payload (carries draft_guidance +
// task_summary). Only touches an unresolved feedback decision.
func (q *Queries) SetFeedbackDecisionPayload(ctx context.Context, arg SetFeedbackDecisionPayloadParams) error {
	_, err := q.db.Exec(ctx, setFeedbackDecisionPayload, arg.ID, arg.Payload)
	return err
}
