// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gate_scripts.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const clearActiveScriptVersion = `-- name: ClearActiveScriptVersion :one
UPDATE tools
SET active_script_version = NULL
WHERE id = $1
RETURNING id, global_uri, name, rung, permissions, overseer_instructions, active_script_version, trust_score
`

// disableGateScript (FR-024): clear the pointer. Returns the prior value so
// the resolver can mark the right row disabled and audit prior_active_version.
func (q *Queries) ClearActiveScriptVersion(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, clearActiveScriptVersion, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
		&i.TrustScore,
	)
	return i, err
}

const createGateScript = `-- name: CreateGateScript :one
INSERT INTO gate_scripts (
  tool_id, version, manifest, manifest_hash, wasm, source, tier, attached_by_principal
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tool_id, version, manifest, manifest_hash, wasm, source, tier, status, attached_by_principal, attached_at
`

type CreateGateScriptParams struct {
	ToolID              uuid.UUID       `json:"tool_id"`
	Version             int32           `json:"version"`
	Manifest            json.RawMessage `json:"manifest"`
	ManifestHash        string          `json:"manifest_hash"`
	Wasm                []byte          `json:"wasm"`
	Source              *string         `json:"source"`
	Tier                string          `json:"tier"`
	AttachedByPrincipal string          `json:"attached_by_principal"`
}

type CreateGateScriptRow struct {
	ID                  uuid.UUID       `json:"id"`
	ToolID              uuid.UUID       `json:"tool_id"`
	Version             int32           `json:"version"`
	Manifest            json.RawMessage `json:"manifest"`
	ManifestHash        string          `json:"manifest_hash"`
	Wasm                []byte          `json:"wasm"`
	Source              *string         `json:"source"`
	Tier                string          `json:"tier"`
	Status              string          `json:"status"`
	AttachedByPrincipal string          `json:"attached_by_principal"`
	AttachedAt          time.Time       `json:"attached_at"`
}

// Append-only insert (FR-021/FR-022). Caller computes version via
// NextGateScriptVersion and advances tools.active_script_version separately.
func (q *Queries) CreateGateScript(ctx context.Context, arg CreateGateScriptParams) (CreateGateScriptRow, error) {
	row := q.db.QueryRow(ctx, createGateScript,
		arg.ToolID,
		arg.Version,
		arg.Manifest,
		arg.ManifestHash,
		arg.Wasm,
		arg.Source,
		arg.Tier,
		arg.AttachedByPrincipal,
	)
	var i CreateGateScriptRow
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.Manifest,
		&i.ManifestHash,
		&i.Wasm,
		&i.Source,
		&i.Tier,
		&i.Status,
		&i.AttachedByPrincipal,
		&i.AttachedAt,
	)
	return i, err
}

const disableGateScriptVersion = `-- name: DisableGateScriptVersion :exec
UPDATE gate_scripts
SET status = 'disabled'
WHERE tool_id = $1 AND version = $2
`

type DisableGateScriptVersionParams struct {
	ToolID  uuid.UUID `json:"tool_id"`
	Version int32     `json:"version"`
}

// Mark a specific (tool_id, version) row disabled (the only legal UPDATE per
// the append-only trigger). Called by disableGateScript after clearing the
// pointer.
func (q *Queries) DisableGateScriptVersion(ctx context.Context, arg DisableGateScriptVersionParams) error {
	_, err := q.db.Exec(ctx, disableGateScriptVersion, arg.ToolID, arg.Version)
	return err
}

const gateScriptEvaluatedForDecision = `-- name: GateScriptEvaluatedForDecision :one
SELECT id, task_id, from_principal, to_principal, in_reply_to, kind, payload, at
FROM audit_messages
WHERE kind = 'gate_script_evaluated'
  AND payload->>'decision_id' = $1::text
ORDER BY at DESC, id DESC
LIMIT 1
`

// Resolves ApprovalRequest.gateScriptEvaluation: the gate_script_evaluated row
// whose payload references this decision id (stamped when a script's
// RequestDecision raised the approval). pgx.ErrNoRows when floor/overseer-raised.
func (q *Queries) GateScriptEvaluatedForDecision(ctx context.Context, dollar_1 string) (AuditMessage, error) {
	row := q.db.QueryRow(ctx, gateScriptEvaluatedForDecision, dollar_1)
	var i AuditMessage
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromPrincipal,
		&i.ToPrincipal,
		&i.InReplyTo,
		&i.Kind,
		&i.Payload,
		&i.At,
	)
	return i, err
}

const getActiveGateScript = `-- name: GetActiveGateScript :one
SELECT gs.id, gs.tool_id, gs.version, gs.manifest, gs.manifest_hash, gs.wasm, gs.source,
       gs.tier, gs.status, gs.attached_by_principal, gs.attached_at
FROM gate_scripts gs
JOIN tools t ON t.id = gs.tool_id AND t.active_script_version = gs.version
WHERE gs.tool_id = $1
  AND gs.status = 'active'
LIMIT 1
`

type GetActiveGateScriptRow struct {
	ID                  uuid.UUID       `json:"id"`
	ToolID              uuid.UUID       `json:"tool_id"`
	Version             int32           `json:"version"`
	Manifest            json.RawMessage `json:"manifest"`
	ManifestHash        string          `json:"manifest_hash"`
	Wasm                []byte          `json:"wasm"`
	Source              *string         `json:"source"`
	Tier                string          `json:"tier"`
	Status              string          `json:"status"`
	AttachedByPrincipal string          `json:"attached_by_principal"`
	AttachedAt          time.Time       `json:"attached_at"`
}

// The row pointed at by tools.active_script_version. Returns pgx.ErrNoRows
// when no script is attached (pointer NULL) or the active version was cleared.
func (q *Queries) GetActiveGateScript(ctx context.Context, toolID uuid.UUID) (GetActiveGateScriptRow, error) {
	row := q.db.QueryRow(ctx, getActiveGateScript, toolID)
	var i GetActiveGateScriptRow
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.Manifest,
		&i.ManifestHash,
		&i.Wasm,
		&i.Source,
		&i.Tier,
		&i.Status,
		&i.AttachedByPrincipal,
		&i.AttachedAt,
	)
	return i, err
}

const getGateScriptByID = `-- name: GetGateScriptByID :one
SELECT id, tool_id, version, manifest, manifest_hash, wasm, source, tier, status, attached_by_principal, attached_at
FROM gate_scripts
WHERE id = $1
LIMIT 1
`

type GetGateScriptByIDRow struct {
	ID                  uuid.UUID       `json:"id"`
	ToolID              uuid.UUID       `json:"tool_id"`
	Version             int32           `json:"version"`
	Manifest            json.RawMessage `json:"manifest"`
	ManifestHash        string          `json:"manifest_hash"`
	Wasm                []byte          `json:"wasm"`
	Source              *string         `json:"source"`
	Tier                string          `json:"tier"`
	Status              string          `json:"status"`
	AttachedByPrincipal string          `json:"attached_by_principal"`
	AttachedAt          time.Time       `json:"attached_at"`
}

func (q *Queries) GetGateScriptByID(ctx context.Context, id uuid.UUID) (GetGateScriptByIDRow, error) {
	row := q.db.QueryRow(ctx, getGateScriptByID, id)
	var i GetGateScriptByIDRow
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.Manifest,
		&i.ManifestHash,
		&i.Wasm,
		&i.Source,
		&i.Tier,
		&i.Status,
		&i.AttachedByPrincipal,
		&i.AttachedAt,
	)
	return i, err
}

const listGateScriptsByTool = `-- name: ListGateScriptsByTool :many
SELECT id, tool_id, version, manifest, manifest_hash, wasm, source, tier, status, attached_by_principal, attached_at
FROM gate_scripts
WHERE tool_id = $1
ORDER BY version DESC
LIMIT $2 OFFSET $3
`

type ListGateScriptsByToolParams struct {
	ToolID uuid.UUID `json:"tool_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListGateScriptsByToolRow struct {
	ID                  uuid.UUID       `json:"id"`
	ToolID              uuid.UUID       `json:"tool_id"`
	Version             int32           `json:"version"`
	Manifest            json.RawMessage `json:"manifest"`
	ManifestHash        string          `json:"manifest_hash"`
	Wasm                []byte          `json:"wasm"`
	Source              *string         `json:"source"`
	Tier                string          `json:"tier"`
	Status              string          `json:"status"`
	AttachedByPrincipal string          `json:"attached_by_principal"`
	AttachedAt          time.Time       `json:"attached_at"`
}

// Version history newest-first (Tool.gateScripts). limit/offset clamped by
// the resolver to a server-side max of 100.
func (q *Queries) ListGateScriptsByTool(ctx context.Context, arg ListGateScriptsByToolParams) ([]ListGateScriptsByToolRow, error) {
	rows, err := q.db.Query(ctx, listGateScriptsByTool, arg.ToolID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGateScriptsByToolRow
	for rows.Next() {
		var i ListGateScriptsByToolRow
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.Version,
			&i.Manifest,
			&i.ManifestHash,
			&i.Wasm,
			&i.Source,
			&i.Tier,
			&i.Status,
			&i.AttachedByPrincipal,
			&i.AttachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGateScriptVersion = `-- name: NextGateScriptVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM gate_scripts
WHERE tool_id = $1
`

// Monotonic per-tool version allocator. Returns 1 for the first attach.
func (q *Queries) NextGateScriptVersion(ctx context.Context, toolID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextGateScriptVersion, toolID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const updateActiveScriptVersion = `-- name: UpdateActiveScriptVersion :one
UPDATE tools
SET active_script_version = $2
WHERE id = $1
RETURNING id, global_uri, name, rung, permissions, overseer_instructions, active_script_version, trust_score
`

type UpdateActiveScriptVersionParams struct {
	ID                  uuid.UUID `json:"id"`
	ActiveScriptVersion *int32    `json:"active_script_version"`
}

// Advance the pointer to the newly-attached version. Owner-only at resolver.
func (q *Queries) UpdateActiveScriptVersion(ctx context.Context, arg UpdateActiveScriptVersionParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateActiveScriptVersion, arg.ID, arg.ActiveScriptVersion)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
		&i.TrustScore,
	)
	return i, err
}
