// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guidance.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeGuidanceForAgent = `-- name: ActiveGuidanceForAgent :many
SELECT note
FROM agent_guidance
WHERE status = 'active'
  AND (scope = 'global' OR agent_config_id = $1)
ORDER BY created_at ASC, id ASC
`

// Hot path: the agent runner loads global + this-agent active notes to inject
// into the system prompt. Oldest-first so guidance reads chronologically.
func (q *Queries) ActiveGuidanceForAgent(ctx context.Context, agentConfigID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, activeGuidanceForAgent, agentConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var note string
		if err := rows.Scan(&note); err != nil {
			return nil, err
		}
		items = append(items, note)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateAgentGuidance = `-- name: DeactivateAgentGuidance :one
UPDATE agent_guidance
   SET status = 'dismissed'
 WHERE id = $1 AND status = 'active'
RETURNING id, note, status, scope, agent_config_id, source_decision_id,
          source_task_id, created_at, activated_at
`

// Owner retires an active guidance note.
func (q *Queries) DeactivateAgentGuidance(ctx context.Context, id uuid.UUID) (AgentGuidance, error) {
	row := q.db.QueryRow(ctx, deactivateAgentGuidance, id)
	var i AgentGuidance
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Status,
		&i.Scope,
		&i.AgentConfigID,
		&i.SourceDecisionID,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getAgentGuidanceByID = `-- name: GetAgentGuidanceByID :one
SELECT id, note, status, scope, agent_config_id, source_decision_id,
       source_task_id, created_at, activated_at
FROM agent_guidance
WHERE id = $1
`

func (q *Queries) GetAgentGuidanceByID(ctx context.Context, id uuid.UUID) (AgentGuidance, error) {
	row := q.db.QueryRow(ctx, getAgentGuidanceByID, id)
	var i AgentGuidance
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Status,
		&i.Scope,
		&i.AgentConfigID,
		&i.SourceDecisionID,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const insertActiveAgentGuidance = `-- name: InsertActiveAgentGuidance :one
INSERT INTO agent_guidance (
  note, status, scope, agent_config_id, source_decision_id, source_task_id, activated_at
)
VALUES ($1, 'active', $2, $3, $4, $5, now())
RETURNING id, note, status, scope, agent_config_id, source_decision_id,
          source_task_id, created_at, activated_at
`

type InsertActiveAgentGuidanceParams struct {
	Note             string      `json:"note"`
	Scope            string      `json:"scope"`
	AgentConfigID    pgtype.UUID `json:"agent_config_id"`
	SourceDecisionID pgtype.UUID `json:"source_decision_id"`
	SourceTaskID     pgtype.UUID `json:"source_task_id"`
}

// Called by acceptFeedbackGuidance: the owner-accepted final text is stored
// VERBATIM and active immediately (no review/distillation step). scope is
// 'global' or 'agent' (agent_config_id required for 'agent').
func (q *Queries) InsertActiveAgentGuidance(ctx context.Context, arg InsertActiveAgentGuidanceParams) (AgentGuidance, error) {
	row := q.db.QueryRow(ctx, insertActiveAgentGuidance,
		arg.Note,
		arg.Scope,
		arg.AgentConfigID,
		arg.SourceDecisionID,
		arg.SourceTaskID,
	)
	var i AgentGuidance
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Status,
		&i.Scope,
		&i.AgentConfigID,
		&i.SourceDecisionID,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const listAgentGuidanceByStatus = `-- name: ListAgentGuidanceByStatus :many
SELECT id, note, status, scope, agent_config_id, source_decision_id,
       source_task_id, created_at, activated_at
FROM agent_guidance
WHERE status = $1
ORDER BY created_at DESC, id DESC
`

// Owner management list (e.g. an "active guidance" settings screen).
func (q *Queries) ListAgentGuidanceByStatus(ctx context.Context, status string) ([]AgentGuidance, error) {
	rows, err := q.db.Query(ctx, listAgentGuidanceByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGuidance
	for rows.Next() {
		var i AgentGuidance
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Status,
			&i.Scope,
			&i.AgentConfigID,
			&i.SourceDecisionID,
			&i.SourceTaskID,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveGuidance = `-- name: ListAllActiveGuidance :many
SELECT id, note, status, scope, agent_config_id, source_decision_id,
       source_task_id, created_at, activated_at
FROM agent_guidance
WHERE status = 'active'
ORDER BY created_at ASC, id ASC
`

// Every active guidance note regardless of scope (global + all agent-scoped),
// oldest-first. Read by the post-completion feedback agent so it can build on —
// and avoid duplicating — standing guidance that already exists.
func (q *Queries) ListAllActiveGuidance(ctx context.Context) ([]AgentGuidance, error) {
	rows, err := q.db.Query(ctx, listAllActiveGuidance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGuidance
	for rows.Next() {
		var i AgentGuidance
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Status,
			&i.Scope,
			&i.AgentConfigID,
			&i.SourceDecisionID,
			&i.SourceTaskID,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
