// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertPendingDecision = `-- name: InsertPendingDecision :one
INSERT INTO pending_decisions (
  task_id, tool_id, kind, payload, disclosure_class,
  frozen_payload, workflow_id, decision_topic
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertPendingDecisionParams struct {
	TaskID          uuid.UUID       `json:"task_id"`
	ToolID          pgtype.UUID     `json:"tool_id"`
	Kind            DecisionKind    `json:"kind"`
	Payload         json.RawMessage `json:"payload"`
	DisclosureClass *string         `json:"disclosure_class"`
	FrozenPayload   []byte          `json:"frozen_payload"`
	WorkflowID      *string         `json:"workflow_id"`
	DecisionTopic   *string         `json:"decision_topic"`
}

// Insert into pending_decisions; trg_pending_notify fires IDs-only pg_notify.
// Phase 3 adds frozen_payload / workflow_id / decision_topic — populated for
// kind=approval_request, left null for agent_question / promotion_proposal.
func (q *Queries) InsertPendingDecision(ctx context.Context, arg InsertPendingDecisionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPendingDecision,
		arg.TaskID,
		arg.ToolID,
		arg.Kind,
		arg.Payload,
		arg.DisclosureClass,
		arg.FrozenPayload,
		arg.WorkflowID,
		arg.DecisionTopic,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listInbox = `-- name: ListInbox :many
SELECT id, kind, task_id, created_at FROM (
  SELECT id, 'pending_decision'::text AS kind, task_id, created_at
    FROM pending_decisions
    WHERE resolved_at IS NULL
  UNION ALL
  SELECT id, 'agent_assignment'::text AS kind, task_id, created_at
    FROM agent_assignments
    WHERE resolved_at IS NULL AND to_principal = $1
) AS i
WHERE (i.created_at, i.id) < ($2::timestamptz, $3::uuid)
ORDER BY i.created_at DESC, i.id DESC
LIMIT $4
`

type ListInboxParams struct {
	ToPrincipal *string   `json:"to_principal"`
	Column2     time.Time `json:"column_2"`
	Column3     uuid.UUID `json:"column_3"`
	Limit       int32     `json:"limit"`
}

type ListInboxRow struct {
	ID        uuid.UUID `json:"id"`
	Kind      string    `json:"kind"`
	TaskID    uuid.UUID `json:"task_id"`
	CreatedAt time.Time `json:"created_at"`
}

// Phase 2 viewer-scoped unified inbox over open pending_decisions and open
// agent_assignments routed to the viewer. Keyset-paginated by
// (created_at DESC, id DESC). $1 = viewer globalUri, $2/$3 = cursor
// (timestamp + uuid), $4 = limit. For an unset cursor pass max-timestamp.
func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error) {
	rows, err := q.db.Query(ctx, listInbox,
		arg.ToPrincipal,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxRow
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxFeed = `-- name: ListInboxFeed :many
WITH feed AS (
  SELECT pd.id, 'pending_decision'::text AS kind, pd.task_id, pd.created_at,
         t.priority, t.due_at, t.intake_signal_id
    FROM pending_decisions pd
    JOIN tasks t ON t.id = pd.task_id
   WHERE pd.resolved_at IS NULL
     AND t.state NOT IN ('done', 'dismissed', 'halted')
  UNION ALL
  SELECT aa.id, 'agent_assignment'::text AS kind, aa.task_id, aa.created_at,
         t.priority, t.due_at, t.intake_signal_id
    FROM agent_assignments aa
    JOIN tasks t ON t.id = aa.task_id
   WHERE aa.resolved_at IS NULL
     AND aa.to_principal = $4::text
     AND t.state NOT IN ('done', 'dismissed', 'halted')
  UNION ALL
  SELECT t.id, 'task'::text AS kind, t.id AS task_id, t.created_at,
         t.priority, t.due_at, t.intake_signal_id
    FROM tasks t
   WHERE t.state = 'proposed'
),
scored AS (
  SELECT f.id, f.kind, f.task_id, f.created_at,
         (
           CASE f.priority
             WHEN 'urgent' THEN 400.0
             WHEN 'high'   THEN 300.0
             WHEN 'normal' THEN 200.0
             WHEN 'low'    THEN 100.0
             ELSE 200.0
           END
           + CASE
               WHEN f.due_at IS NULL THEN 0.0
               WHEN f.due_at <  $5::timestamptz THEN 250.0
               WHEN f.due_at <  $5::timestamptz + interval '24 hours' THEN 150.0
               WHEN f.due_at <  $5::timestamptz + interval '7 days'   THEN 75.0
               ELSE 0.0
             END
           + COALESCE(s.stakes_hint, 0.0) * 100.0
           + LEAST(GREATEST(EXTRACT(EPOCH FROM ($5::timestamptz - f.created_at)) / 3600.0, 0.0), 48.0)
         )::double precision AS score
    FROM feed f
    LEFT JOIN intake_signals s ON s.id = f.intake_signal_id
)
SELECT id, kind, task_id, created_at, score
  FROM scored
 WHERE (score, id) < ($1::double precision, $2::uuid)
 ORDER BY score DESC, id DESC
 LIMIT $3::int
`

type ListInboxFeedParams struct {
	CursorScore float64   `json:"cursor_score"`
	CursorID    uuid.UUID `json:"cursor_id"`
	PageLimit   int32     `json:"page_limit"`
	Viewer      string    `json:"viewer"`
	Now         time.Time `json:"now"`
}

type ListInboxFeedRow struct {
	ID        uuid.UUID `json:"id"`
	Kind      string    `json:"kind"`
	TaskID    uuid.UUID `json:"task_id"`
	CreatedAt time.Time `json:"created_at"`
	Score     float64   `json:"score"`
}

// Ranked, keyset-paginated action feed. Three actionable sources are unioned:
//   - open pending_decisions whose task is non-terminal
//   - open agent_assignments routed to the viewer whose task is non-terminal
//   - PROPOSED tasks (the owner accept/dismiss action item itself)
//
// Each row carries a blended urgency `score` over the PINNED clock @now
// (owner priority + deadline proximity + intake stakes + age). The clock is
// pinned in the cursor so a whole scroll session ranks against one fixed @now,
// keeping the (score, id) keyset stable; the next page passes the last row's
// SQL-returned score as @cursor_score. Weights are first-guess constants — a
// candidate to move into config_entries later. Visibility filtering (the
// actionable-only NOT IN (terminal) clause + to_principal scope) is SQL-side.
func (q *Queries) ListInboxFeed(ctx context.Context, arg ListInboxFeedParams) ([]ListInboxFeedRow, error) {
	rows, err := q.db.Query(ctx, listInboxFeed,
		arg.CursorScore,
		arg.CursorID,
		arg.PageLimit,
		arg.Viewer,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxFeedRow
	for rows.Next() {
		var i ListInboxFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TaskID,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
