// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intake_signals.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSignal = `-- name: GetSignal :one
SELECT id, signal_version, connector_id, idempotency_key, provenance, payload, disposition, confidence, stakes_hint, created_at, processed_at FROM intake_signals WHERE id = $1
`

func (q *Queries) GetSignal(ctx context.Context, id uuid.UUID) (IntakeSignal, error) {
	row := q.db.QueryRow(ctx, getSignal, id)
	var i IntakeSignal
	err := row.Scan(
		&i.ID,
		&i.SignalVersion,
		&i.ConnectorID,
		&i.IdempotencyKey,
		&i.Provenance,
		&i.Payload,
		&i.Disposition,
		&i.Confidence,
		&i.StakesHint,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getUnprocessedSignals = `-- name: GetUnprocessedSignals :many
SELECT id, signal_version, connector_id, idempotency_key, provenance, payload, disposition, confidence, stakes_hint, created_at, processed_at FROM intake_signals
WHERE connector_id = $1 AND processed_at IS NULL
ORDER BY created_at
`

// Bounded by the partial index idx_intake_signals_unprocessed (migration 00006).
func (q *Queries) GetUnprocessedSignals(ctx context.Context, connectorID pgtype.UUID) ([]IntakeSignal, error) {
	rows, err := q.db.Query(ctx, getUnprocessedSignals, connectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntakeSignal
	for rows.Next() {
		var i IntakeSignal
		if err := rows.Scan(
			&i.ID,
			&i.SignalVersion,
			&i.ConnectorID,
			&i.IdempotencyKey,
			&i.Provenance,
			&i.Payload,
			&i.Disposition,
			&i.Confidence,
			&i.StakesHint,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const idempotentInsertSignal = `-- name: IdempotentInsertSignal :one
INSERT INTO intake_signals (
  signal_version, connector_id, idempotency_key, provenance, payload,
  disposition, confidence, stakes_hint
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (connector_id, idempotency_key) DO NOTHING
RETURNING id, signal_version, connector_id, idempotency_key, provenance, payload, disposition, confidence, stakes_hint, created_at, processed_at
`

type IdempotentInsertSignalParams struct {
	SignalVersion  string            `json:"signal_version"`
	ConnectorID    pgtype.UUID       `json:"connector_id"`
	IdempotencyKey string            `json:"idempotency_key"`
	Provenance     json.RawMessage   `json:"provenance"`
	Payload        json.RawMessage   `json:"payload"`
	Disposition    SignalDisposition `json:"disposition"`
	Confidence     *float64          `json:"confidence"`
	StakesHint     *float64          `json:"stakes_hint"`
}

// The single dedupe point (research R6 / SC-004). ON CONFLICT DO NOTHING means
// a re-emission of an already-seen (connector_id, idempotency_key) returns no
// rows (pgx.ErrNoRows) — the ingest layer treats that as the dedupe branch.
func (q *Queries) IdempotentInsertSignal(ctx context.Context, arg IdempotentInsertSignalParams) (IntakeSignal, error) {
	row := q.db.QueryRow(ctx, idempotentInsertSignal,
		arg.SignalVersion,
		arg.ConnectorID,
		arg.IdempotencyKey,
		arg.Provenance,
		arg.Payload,
		arg.Disposition,
		arg.Confidence,
		arg.StakesHint,
	)
	var i IntakeSignal
	err := row.Scan(
		&i.ID,
		&i.SignalVersion,
		&i.ConnectorID,
		&i.IdempotencyKey,
		&i.Provenance,
		&i.Payload,
		&i.Disposition,
		&i.Confidence,
		&i.StakesHint,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markSignalProcessed = `-- name: MarkSignalProcessed :exec
UPDATE intake_signals SET processed_at = now() WHERE id = $1
`

// Set processed_at once the disposition router has handled the signal.
func (q *Queries) MarkSignalProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSignalProcessed, id)
	return err
}
