// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMcpServer = `-- name: DeleteMcpServer :exec
DELETE FROM mcp_servers WHERE id = $1
`

// removeMcpServer (owner-only). Tool rows are ON DELETE SET NULL (retired first
// by the resolver), credentials cascade.
func (q *Queries) DeleteMcpServer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMcpServer, id)
	return err
}

const deleteMcpServerCredential = `-- name: DeleteMcpServerCredential :exec
DELETE FROM mcp_server_credentials WHERE mcp_server_id = $1
`

func (q *Queries) DeleteMcpServerCredential(ctx context.Context, mcpServerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMcpServerCredential, mcpServerID)
	return err
}

const getMcpServer = `-- name: GetMcpServer :one
SELECT id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at FROM mcp_servers WHERE id = $1
`

func (q *Queries) GetMcpServer(ctx context.Context, id uuid.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMcpServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EndpointUrl,
		&i.Enabled,
		&i.ProtocolVersion,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMcpServerBySlug = `-- name: GetMcpServerBySlug :one
SELECT id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at FROM mcp_servers WHERE slug = $1
`

func (q *Queries) GetMcpServerBySlug(ctx context.Context, slug string) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMcpServerBySlug, slug)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EndpointUrl,
		&i.Enabled,
		&i.ProtocolVersion,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMcpServerCredential = `-- name: GetMcpServerCredential :one
SELECT mcp_server_id, encrypted, expires_at FROM mcp_server_credentials WHERE mcp_server_id = $1
`

func (q *Queries) GetMcpServerCredential(ctx context.Context, mcpServerID uuid.UUID) (McpServerCredential, error) {
	row := q.db.QueryRow(ctx, getMcpServerCredential, mcpServerID)
	var i McpServerCredential
	err := row.Scan(&i.McpServerID, &i.Encrypted, &i.ExpiresAt)
	return i, err
}

const insertMcpServer = `-- name: InsertMcpServer :one
INSERT INTO mcp_servers (slug, name, endpoint_url)
VALUES ($1, $2, $3)
RETURNING id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at
`

type InsertMcpServerParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	EndpointUrl string `json:"endpoint_url"`
}

// registerMcpServer (owner-only). A new server starts disabled + unsynced;
// enableMcpServer + syncMcpServer bring it online. slug is UNIQUE.
func (q *Queries) InsertMcpServer(ctx context.Context, arg InsertMcpServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, insertMcpServer, arg.Slug, arg.Name, arg.EndpointUrl)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EndpointUrl,
		&i.Enabled,
		&i.ProtocolVersion,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledMcpServers = `-- name: ListEnabledMcpServers :many
SELECT id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at FROM mcp_servers WHERE enabled = true ORDER BY created_at
`

func (q *Queries) ListEnabledMcpServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listEnabledMcpServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.EndpointUrl,
			&i.Enabled,
			&i.ProtocolVersion,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpServers = `-- name: ListMcpServers :many
SELECT id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at FROM mcp_servers ORDER BY created_at
`

func (q *Queries) ListMcpServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMcpServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.EndpointUrl,
			&i.Enabled,
			&i.ProtocolVersion,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMcpServerEnabled = `-- name: SetMcpServerEnabled :one
UPDATE mcp_servers SET enabled = $2 WHERE id = $1 RETURNING id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at
`

type SetMcpServerEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

// enableMcpServer (owner-only).
func (q *Queries) SetMcpServerEnabled(ctx context.Context, arg SetMcpServerEnabledParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, setMcpServerEnabled, arg.ID, arg.Enabled)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EndpointUrl,
		&i.Enabled,
		&i.ProtocolVersion,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setMcpServerSyncResult = `-- name: SetMcpServerSyncResult :one
UPDATE mcp_servers
  SET status = $2, protocol_version = $3, last_synced_at = now()
WHERE id = $1
RETURNING id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at
`

type SetMcpServerSyncResultParams struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	ProtocolVersion *string   `json:"protocol_version"`
}

// Records the outcome of a sync attempt (status + negotiated protocol version +
// timestamp).
func (q *Queries) SetMcpServerSyncResult(ctx context.Context, arg SetMcpServerSyncResultParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, setMcpServerSyncResult, arg.ID, arg.Status, arg.ProtocolVersion)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EndpointUrl,
		&i.Enabled,
		&i.ProtocolVersion,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateMcpServerConfig = `-- name: UpdateMcpServerConfig :one
UPDATE mcp_servers
  SET name = $2, endpoint_url = $3
WHERE id = $1
RETURNING id, slug, name, endpoint_url, enabled, protocol_version, status, last_synced_at, created_at
`

type UpdateMcpServerConfigParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	EndpointUrl string    `json:"endpoint_url"`
}

// setMcpServerConfig (owner-only). Updates the display name + endpoint.
func (q *Queries) UpdateMcpServerConfig(ctx context.Context, arg UpdateMcpServerConfigParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMcpServerConfig, arg.ID, arg.Name, arg.EndpointUrl)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EndpointUrl,
		&i.Enabled,
		&i.ProtocolVersion,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMcpServerCredential = `-- name: UpsertMcpServerCredential :exec
INSERT INTO mcp_server_credentials (mcp_server_id, encrypted, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (mcp_server_id) DO UPDATE
  SET encrypted = EXCLUDED.encrypted, expires_at = EXCLUDED.expires_at
`

type UpsertMcpServerCredentialParams struct {
	McpServerID uuid.UUID          `json:"mcp_server_id"`
	Encrypted   []byte             `json:"encrypted"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Seal-at-rest (AES-256-GCM): `encrypted` is crypto.Seal(mcp.Auth JSON).
func (q *Queries) UpsertMcpServerCredential(ctx context.Context, arg UpsertMcpServerCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertMcpServerCredential, arg.McpServerID, arg.Encrypted, arg.ExpiresAt)
	return err
}
