// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AgentStage string

const (
	AgentStageTriage    AgentStage = "triage"
	AgentStageExpansion AgentStage = "expansion"
	AgentStageExecution AgentStage = "execution"
	AgentStageFeedback  AgentStage = "feedback"
)

func (e *AgentStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStage(s)
	case string:
		*e = AgentStage(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStage: %T", src)
	}
	return nil
}

type NullAgentStage struct {
	AgentStage AgentStage `json:"agent_stage"`
	Valid      bool       `json:"valid"` // Valid is true if AgentStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStage) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStage), nil
}

type ChainStage string

const (
	ChainStageCreation   ChainStage = "creation"
	ChainStageTriage     ChainStage = "triage"
	ChainStageExpansion  ChainStage = "expansion"
	ChainStageExecution  ChainStage = "execution"
	ChainStageCompletion ChainStage = "completion"
)

func (e *ChainStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainStage(s)
	case string:
		*e = ChainStage(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainStage: %T", src)
	}
	return nil
}

type NullChainStage struct {
	ChainStage ChainStage `json:"chain_stage"`
	Valid      bool       `json:"valid"` // Valid is true if ChainStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainStage) Scan(value interface{}) error {
	if value == nil {
		ns.ChainStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainStage), nil
}

type ConfigOrigin string

const (
	ConfigOriginCore      ConfigOrigin = "core"
	ConfigOriginCommunity ConfigOrigin = "community"
)

func (e *ConfigOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConfigOrigin(s)
	case string:
		*e = ConfigOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for ConfigOrigin: %T", src)
	}
	return nil
}

type NullConfigOrigin struct {
	ConfigOrigin ConfigOrigin `json:"config_origin"`
	Valid        bool         `json:"valid"` // Valid is true if ConfigOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConfigOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.ConfigOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConfigOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConfigOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConfigOrigin), nil
}

type DecisionKind string

const (
	DecisionKindApprovalRequest   DecisionKind = "approval_request"
	DecisionKindAgentQuestion     DecisionKind = "agent_question"
	DecisionKindPromotionProposal DecisionKind = "promotion_proposal"
	DecisionKindFeedbackRequest   DecisionKind = "feedback_request"
)

func (e *DecisionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DecisionKind(s)
	case string:
		*e = DecisionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DecisionKind: %T", src)
	}
	return nil
}

type NullDecisionKind struct {
	DecisionKind DecisionKind `json:"decision_kind"`
	Valid        bool         `json:"valid"` // Valid is true if DecisionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDecisionKind) Scan(value interface{}) error {
	if value == nil {
		ns.DecisionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DecisionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDecisionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DecisionKind), nil
}

type DevicePlatform string

const (
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformWeb     DevicePlatform = "web"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform `json:"device_platform"`
	Valid          bool           `json:"valid"` // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

type SignalDisposition string

const (
	SignalDispositionForcedTask SignalDisposition = "forced_task"
	SignalDispositionRichEvent  SignalDisposition = "rich_event"
	SignalDispositionLlmJudge   SignalDisposition = "llm_judge"
)

func (e *SignalDisposition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignalDisposition(s)
	case string:
		*e = SignalDisposition(s)
	default:
		return fmt.Errorf("unsupported scan type for SignalDisposition: %T", src)
	}
	return nil
}

type NullSignalDisposition struct {
	SignalDisposition SignalDisposition `json:"signal_disposition"`
	Valid             bool              `json:"valid"` // Valid is true if SignalDisposition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignalDisposition) Scan(value interface{}) error {
	if value == nil {
		ns.SignalDisposition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignalDisposition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignalDisposition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignalDisposition), nil
}

type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityNormal TaskPriority = "normal"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

func (e *TaskPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskPriority(s)
	case string:
		*e = TaskPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskPriority: %T", src)
	}
	return nil
}

type NullTaskPriority struct {
	TaskPriority TaskPriority `json:"task_priority"`
	Valid        bool         `json:"valid"` // Valid is true if TaskPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TaskPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskPriority), nil
}

type TaskRelationKind string

const (
	TaskRelationKindBlocks      TaskRelationKind = "blocks"
	TaskRelationKindSubtaskOf   TaskRelationKind = "subtask_of"
	TaskRelationKindRelated     TaskRelationKind = "related"
	TaskRelationKindDuplicateOf TaskRelationKind = "duplicate_of"
)

func (e *TaskRelationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskRelationKind(s)
	case string:
		*e = TaskRelationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskRelationKind: %T", src)
	}
	return nil
}

type NullTaskRelationKind struct {
	TaskRelationKind TaskRelationKind `json:"task_relation_kind"`
	Valid            bool             `json:"valid"` // Valid is true if TaskRelationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskRelationKind) Scan(value interface{}) error {
	if value == nil {
		ns.TaskRelationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskRelationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskRelationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskRelationKind), nil
}

type TaskState string

const (
	TaskStateProposed  TaskState = "proposed"
	TaskStateAccepted  TaskState = "accepted"
	TaskStateWaiting   TaskState = "waiting"
	TaskStateExecuting TaskState = "executing"
	TaskStateDone      TaskState = "done"
	TaskStateDismissed TaskState = "dismissed"
	TaskStateHalted    TaskState = "halted"
)

func (e *TaskState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskState(s)
	case string:
		*e = TaskState(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskState: %T", src)
	}
	return nil
}

type NullTaskState struct {
	TaskState TaskState `json:"task_state"`
	Valid     bool      `json:"valid"` // Valid is true if TaskState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskState) Scan(value interface{}) error {
	if value == nil {
		ns.TaskState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskState), nil
}

type ToolOutcomeKind string

const (
	ToolOutcomeKindClean          ToolOutcomeKind = "clean"
	ToolOutcomeKindBad            ToolOutcomeKind = "bad"
	ToolOutcomeKindDeniedByScript ToolOutcomeKind = "denied_by_script"
)

func (e *ToolOutcomeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolOutcomeKind(s)
	case string:
		*e = ToolOutcomeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolOutcomeKind: %T", src)
	}
	return nil
}

type NullToolOutcomeKind struct {
	ToolOutcomeKind ToolOutcomeKind `json:"tool_outcome_kind"`
	Valid           bool            `json:"valid"` // Valid is true if ToolOutcomeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolOutcomeKind) Scan(value interface{}) error {
	if value == nil {
		ns.ToolOutcomeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolOutcomeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolOutcomeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolOutcomeKind), nil
}

type AgentAssignment struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	Stage           ChainStage         `json:"stage"`
	FromPrincipal   *string            `json:"from_principal"`
	Ask             string             `json:"ask"`
	GatheredContext json.RawMessage    `json:"gathered_context"`
	CreatedAt       time.Time          `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ToPrincipal     *string            `json:"to_principal"`
}

type AgentConfig struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	Stage         AgentStage      `json:"stage"`
	IsHuman       bool            `json:"is_human"`
	SystemPrompt  *string         `json:"system_prompt"`
	Model         *string         `json:"model"`
	ToolAllowlist json.RawMessage `json:"tool_allowlist"`
	Eligibility   json.RawMessage `json:"eligibility"`
	Origin        ConfigOrigin    `json:"origin"`
	Version       int32           `json:"version"`
}

type AgentGuidance struct {
	ID               uuid.UUID          `json:"id"`
	Note             string             `json:"note"`
	Status           string             `json:"status"`
	Scope            string             `json:"scope"`
	AgentConfigID    pgtype.UUID        `json:"agent_config_id"`
	SourceDecisionID pgtype.UUID        `json:"source_decision_id"`
	SourceTaskID     pgtype.UUID        `json:"source_task_id"`
	CreatedAt        time.Time          `json:"created_at"`
	ActivatedAt      pgtype.Timestamptz `json:"activated_at"`
}

type AuditMessage struct {
	ID            uuid.UUID       `json:"id"`
	TaskID        pgtype.UUID     `json:"task_id"`
	FromPrincipal string          `json:"from_principal"`
	ToPrincipal   *string         `json:"to_principal"`
	InReplyTo     pgtype.UUID     `json:"in_reply_to"`
	Kind          string          `json:"kind"`
	Payload       json.RawMessage `json:"payload"`
	At            time.Time       `json:"at"`
}

type ChainWorkflow struct {
	ID             uuid.UUID          `json:"id"`
	TaskID         uuid.UUID          `json:"task_id"`
	DbosWorkflowID string             `json:"dbos_workflow_id"`
	Status         string             `json:"status"`
	StartedAt      time.Time          `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
}

type ConfigEntry struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type ConnectorConfig struct {
	ID               uuid.UUID       `json:"id"`
	ConnectorType    string          `json:"connector_type"`
	Filter           json.RawMessage `json:"filter"`
	Schedule         *string         `json:"schedule"`
	DispositionRules json.RawMessage `json:"disposition_rules"`
	Enabled          bool            `json:"enabled"`
	CreatedAt        time.Time       `json:"created_at"`
}

type DeviceToken struct {
	Token     string         `json:"token"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	Platform  DevicePlatform `json:"platform"`
	CreatedAt time.Time      `json:"created_at"`
}

type Embedding struct {
	SourceType     string           `json:"source_type"`
	SourceID       uuid.UUID        `json:"source_id"`
	SourceText     string           `json:"source_text"`
	ContentHash    string           `json:"content_hash"`
	EmbeddingBlue  *pgvector.Vector `json:"embedding_blue"`
	EmbeddingGreen *pgvector.Vector `json:"embedding_green"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type EmbeddingVersion struct {
	Version     int32              `json:"version"`
	Slot        string             `json:"slot"`
	Provider    string             `json:"provider"`
	Model       string             `json:"model"`
	Dimension   int32              `json:"dimension"`
	ConfigHash  string             `json:"config_hash"`
	Status      string             `json:"status"`
	WorkflowID  *string            `json:"workflow_id"`
	CreatedAt   time.Time          `json:"created_at"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
}

type FeedbackMessage struct {
	ID         uuid.UUID `json:"id"`
	DecisionID uuid.UUID `json:"decision_id"`
	Role       string    `json:"role"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
}

type GateScript struct {
	ID                  uuid.UUID       `json:"id"`
	ToolID              uuid.UUID       `json:"tool_id"`
	Version             int32           `json:"version"`
	Wasm                []byte          `json:"wasm"`
	Source              *string         `json:"source"`
	Manifest            json.RawMessage `json:"manifest"`
	CreatedAt           time.Time       `json:"created_at"`
	ManifestHash        string          `json:"manifest_hash"`
	Tier                string          `json:"tier"`
	Status              string          `json:"status"`
	AttachedByPrincipal string          `json:"attached_by_principal"`
	AttachedAt          time.Time       `json:"attached_at"`
}

type InboxMessage struct {
	ID           uuid.UUID          `json:"id"`
	SourceTable  *string            `json:"source_table"`
	MessageType  string             `json:"message_type"`
	Recipient    *string            `json:"recipient"`
	TaskID       uuid.UUID          `json:"task_id"`
	CreatedAt    time.Time          `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	SeenAt       pgtype.Timestamptz `json:"seen_at"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	DismissedAt  pgtype.Timestamptz `json:"dismissed_at"`
	SnoozedUntil pgtype.Timestamptz `json:"snoozed_until"`
	Payload      []byte             `json:"payload"`
}

type IntakeSignal struct {
	ID             uuid.UUID          `json:"id"`
	SignalVersion  string             `json:"signal_version"`
	ConnectorID    pgtype.UUID        `json:"connector_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Provenance     json.RawMessage    `json:"provenance"`
	Payload        json.RawMessage    `json:"payload"`
	Disposition    SignalDisposition  `json:"disposition"`
	Confidence     *float64           `json:"confidence"`
	StakesHint     *float64           `json:"stakes_hint"`
	CreatedAt      time.Time          `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

type OwnerRule struct {
	OwnerGlobalUri string    `json:"owner_global_uri"`
	Key            string    `json:"key"`
	Value          string    `json:"value"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type PendingDecision struct {
	ID               uuid.UUID          `json:"id"`
	TaskID           uuid.UUID          `json:"task_id"`
	ToolID           pgtype.UUID        `json:"tool_id"`
	Kind             DecisionKind       `json:"kind"`
	Payload          json.RawMessage    `json:"payload"`
	DisclosureClass  *string            `json:"disclosure_class"`
	CreatedAt        time.Time          `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	Resolution       []byte             `json:"resolution"`
	FrozenPayload    []byte             `json:"frozen_payload"`
	WorkflowID       *string            `json:"workflow_id"`
	DecisionTopic    *string            `json:"decision_topic"`
	NotifyWorkflowID *string            `json:"notify_workflow_id"`
}

type Principal struct {
	ID          uuid.UUID `json:"id"`
	GlobalUri   string    `json:"global_uri"`
	Kind        string    `json:"kind"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	PrincipalID uuid.UUID          `json:"principal_id"`
	TokenHash   []byte             `json:"token_hash"`
	DisplayName string             `json:"display_name"`
	CreatedAt   time.Time          `json:"created_at"`
	LastSeenAt  time.Time          `json:"last_seen_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type SourceCredential struct {
	ConnectorID uuid.UUID          `json:"connector_id"`
	Encrypted   []byte             `json:"encrypted"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type Task struct {
	ID             uuid.UUID          `json:"id"`
	GlobalUri      string             `json:"global_uri"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	State          TaskState          `json:"state"`
	CurrentStage   ChainStage         `json:"current_stage"`
	Provenance     []byte             `json:"provenance"`
	ContextRefs    json.RawMessage    `json:"context_refs"`
	Findings       json.RawMessage    `json:"findings"`
	IntakeSignalID pgtype.UUID        `json:"intake_signal_id"`
	CreatedAt      time.Time          `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	Priority       TaskPriority       `json:"priority"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	ShortID        int64              `json:"short_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	Rank           *float64           `json:"rank"`
}

type TaskCategory struct {
	ID            uuid.UUID       `json:"id"`
	Key           string          `json:"key"`
	ParentID      pgtype.UUID     `json:"parent_id"`
	Label         string          `json:"label"`
	Description   *string         `json:"description"`
	StageBindings json.RawMessage `json:"stage_bindings"`
	Origin        ConfigOrigin    `json:"origin"`
	Version       int32           `json:"version"`
}

type TaskRelation struct {
	ID        uuid.UUID        `json:"id"`
	FromTask  uuid.UUID        `json:"from_task"`
	ToTask    uuid.UUID        `json:"to_task"`
	Kind      TaskRelationKind `json:"kind"`
	CreatedAt time.Time        `json:"created_at"`
}

type Tool struct {
	ID                   uuid.UUID       `json:"id"`
	GlobalUri            string          `json:"global_uri"`
	Name                 string          `json:"name"`
	Rung                 string          `json:"rung"`
	Permissions          json.RawMessage `json:"permissions"`
	OverseerInstructions *string         `json:"overseer_instructions"`
	ActiveScriptVersion  *int32          `json:"active_script_version"`
	TrustScore           float64         `json:"trust_score"`
}

type ToolOutcome struct {
	ID                 uuid.UUID          `json:"id"`
	ToolID             uuid.UUID          `json:"tool_id"`
	TaskID             uuid.UUID          `json:"task_id"`
	Outcome            ToolOutcomeKind    `json:"outcome"`
	At                 time.Time          `json:"at"`
	MaturedAt          pgtype.Timestamptz `json:"matured_at"`
	RoutineFingerprint *string            `json:"routine_fingerprint"`
}

type ToolRoutineGrant struct {
	ID                 uuid.UUID          `json:"id"`
	ToolID             uuid.UUID          `json:"tool_id"`
	RoutineFingerprint string             `json:"routine_fingerprint"`
	Evidence           json.RawMessage    `json:"evidence"`
	GrantedBy          string             `json:"granted_by"`
	GrantedAt          time.Time          `json:"granted_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
}
