// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentStage string

const (
	AgentStageTriage    AgentStage = "triage"
	AgentStageExpansion AgentStage = "expansion"
	AgentStageExecution AgentStage = "execution"
)

func (e *AgentStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStage(s)
	case string:
		*e = AgentStage(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStage: %T", src)
	}
	return nil
}

type NullAgentStage struct {
	AgentStage AgentStage `json:"agent_stage"`
	Valid      bool       `json:"valid"` // Valid is true if AgentStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStage) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStage), nil
}

type ChainStage string

const (
	ChainStageCreation   ChainStage = "creation"
	ChainStageTriage     ChainStage = "triage"
	ChainStageExpansion  ChainStage = "expansion"
	ChainStageExecution  ChainStage = "execution"
	ChainStageCompletion ChainStage = "completion"
)

func (e *ChainStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainStage(s)
	case string:
		*e = ChainStage(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainStage: %T", src)
	}
	return nil
}

type NullChainStage struct {
	ChainStage ChainStage `json:"chain_stage"`
	Valid      bool       `json:"valid"` // Valid is true if ChainStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainStage) Scan(value interface{}) error {
	if value == nil {
		ns.ChainStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainStage), nil
}

type ConfigOrigin string

const (
	ConfigOriginCore      ConfigOrigin = "core"
	ConfigOriginCommunity ConfigOrigin = "community"
)

func (e *ConfigOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConfigOrigin(s)
	case string:
		*e = ConfigOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for ConfigOrigin: %T", src)
	}
	return nil
}

type NullConfigOrigin struct {
	ConfigOrigin ConfigOrigin `json:"config_origin"`
	Valid        bool         `json:"valid"` // Valid is true if ConfigOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConfigOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.ConfigOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConfigOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConfigOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConfigOrigin), nil
}

type DecisionKind string

const (
	DecisionKindApprovalRequest   DecisionKind = "approval_request"
	DecisionKindAgentQuestion     DecisionKind = "agent_question"
	DecisionKindPromotionProposal DecisionKind = "promotion_proposal"
)

func (e *DecisionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DecisionKind(s)
	case string:
		*e = DecisionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DecisionKind: %T", src)
	}
	return nil
}

type NullDecisionKind struct {
	DecisionKind DecisionKind `json:"decision_kind"`
	Valid        bool         `json:"valid"` // Valid is true if DecisionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDecisionKind) Scan(value interface{}) error {
	if value == nil {
		ns.DecisionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DecisionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDecisionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DecisionKind), nil
}

type DevicePlatform string

const (
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformWeb     DevicePlatform = "web"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform `json:"device_platform"`
	Valid          bool           `json:"valid"` // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

type SignalDisposition string

const (
	SignalDispositionForcedTask SignalDisposition = "forced_task"
	SignalDispositionRichEvent  SignalDisposition = "rich_event"
	SignalDispositionLlmJudge   SignalDisposition = "llm_judge"
)

func (e *SignalDisposition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignalDisposition(s)
	case string:
		*e = SignalDisposition(s)
	default:
		return fmt.Errorf("unsupported scan type for SignalDisposition: %T", src)
	}
	return nil
}

type NullSignalDisposition struct {
	SignalDisposition SignalDisposition `json:"signal_disposition"`
	Valid             bool              `json:"valid"` // Valid is true if SignalDisposition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignalDisposition) Scan(value interface{}) error {
	if value == nil {
		ns.SignalDisposition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignalDisposition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignalDisposition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignalDisposition), nil
}

type TaskState string

const (
	TaskStateProposed  TaskState = "proposed"
	TaskStateAccepted  TaskState = "accepted"
	TaskStateEligible  TaskState = "eligible"
	TaskStateExecuting TaskState = "executing"
	TaskStateDone      TaskState = "done"
	TaskStateDismissed TaskState = "dismissed"
	TaskStateHalted    TaskState = "halted"
)

func (e *TaskState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskState(s)
	case string:
		*e = TaskState(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskState: %T", src)
	}
	return nil
}

type NullTaskState struct {
	TaskState TaskState `json:"task_state"`
	Valid     bool      `json:"valid"` // Valid is true if TaskState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskState) Scan(value interface{}) error {
	if value == nil {
		ns.TaskState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskState), nil
}

type ToolOutcomeKind string

const (
	ToolOutcomeKindClean ToolOutcomeKind = "clean"
	ToolOutcomeKindBad   ToolOutcomeKind = "bad"
)

func (e *ToolOutcomeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolOutcomeKind(s)
	case string:
		*e = ToolOutcomeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolOutcomeKind: %T", src)
	}
	return nil
}

type NullToolOutcomeKind struct {
	ToolOutcomeKind ToolOutcomeKind `json:"tool_outcome_kind"`
	Valid           bool            `json:"valid"` // Valid is true if ToolOutcomeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolOutcomeKind) Scan(value interface{}) error {
	if value == nil {
		ns.ToolOutcomeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolOutcomeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolOutcomeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolOutcomeKind), nil
}

type AgentAssignment struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	Stage           ChainStage         `json:"stage"`
	FromPrincipal   *string            `json:"from_principal"`
	Ask             string             `json:"ask"`
	GatheredContext json.RawMessage    `json:"gathered_context"`
	CreatedAt       time.Time          `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

type AgentConfig struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	Stage         AgentStage      `json:"stage"`
	IsHuman       bool            `json:"is_human"`
	SystemPrompt  *string         `json:"system_prompt"`
	Model         *string         `json:"model"`
	ToolAllowlist json.RawMessage `json:"tool_allowlist"`
	Eligibility   json.RawMessage `json:"eligibility"`
	Origin        ConfigOrigin    `json:"origin"`
	Version       int32           `json:"version"`
}

type AuditMessage struct {
	ID            uuid.UUID       `json:"id"`
	TaskID        uuid.UUID       `json:"task_id"`
	FromPrincipal string          `json:"from_principal"`
	ToPrincipal   *string         `json:"to_principal"`
	InReplyTo     pgtype.UUID     `json:"in_reply_to"`
	Kind          string          `json:"kind"`
	Payload       json.RawMessage `json:"payload"`
	At            time.Time       `json:"at"`
}

type ChainWorkflow struct {
	ID             uuid.UUID          `json:"id"`
	TaskID         uuid.UUID          `json:"task_id"`
	DbosWorkflowID string             `json:"dbos_workflow_id"`
	Status         string             `json:"status"`
	StartedAt      time.Time          `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
}

type ConnectorConfig struct {
	ID               uuid.UUID       `json:"id"`
	ConnectorType    string          `json:"connector_type"`
	Filter           json.RawMessage `json:"filter"`
	Schedule         *string         `json:"schedule"`
	DispositionRules json.RawMessage `json:"disposition_rules"`
	Enabled          bool            `json:"enabled"`
	CreatedAt        time.Time       `json:"created_at"`
}

type DeviceToken struct {
	Token     string         `json:"token"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	Platform  DevicePlatform `json:"platform"`
	CreatedAt time.Time      `json:"created_at"`
}

type GateScript struct {
	ID        uuid.UUID       `json:"id"`
	ToolID    uuid.UUID       `json:"tool_id"`
	Version   int32           `json:"version"`
	Wasm      []byte          `json:"wasm"`
	Source    *string         `json:"source"`
	Manifest  json.RawMessage `json:"manifest"`
	CreatedAt time.Time       `json:"created_at"`
}

type IntakeSignal struct {
	ID             uuid.UUID          `json:"id"`
	SignalVersion  string             `json:"signal_version"`
	ConnectorID    pgtype.UUID        `json:"connector_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Provenance     json.RawMessage    `json:"provenance"`
	Payload        json.RawMessage    `json:"payload"`
	Disposition    SignalDisposition  `json:"disposition"`
	Confidence     *float64           `json:"confidence"`
	StakesHint     *float64           `json:"stakes_hint"`
	CreatedAt      time.Time          `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

type PendingDecision struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	ToolID          pgtype.UUID        `json:"tool_id"`
	Kind            DecisionKind       `json:"kind"`
	Payload         json.RawMessage    `json:"payload"`
	DisclosureClass *string            `json:"disclosure_class"`
	CreatedAt       time.Time          `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	Resolution      []byte             `json:"resolution"`
}

type Principal struct {
	ID          uuid.UUID `json:"id"`
	GlobalUri   string    `json:"global_uri"`
	Kind        string    `json:"kind"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

type SourceCredential struct {
	ConnectorID uuid.UUID          `json:"connector_id"`
	Encrypted   []byte             `json:"encrypted"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type Task struct {
	ID             uuid.UUID          `json:"id"`
	GlobalUri      string             `json:"global_uri"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	State          TaskState          `json:"state"`
	CurrentStage   ChainStage         `json:"current_stage"`
	Provenance     []byte             `json:"provenance"`
	ContextRefs    json.RawMessage    `json:"context_refs"`
	Findings       json.RawMessage    `json:"findings"`
	IntakeSignalID pgtype.UUID        `json:"intake_signal_id"`
	CreatedAt      time.Time          `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
}

type Tool struct {
	ID                   uuid.UUID       `json:"id"`
	GlobalUri            string          `json:"global_uri"`
	Name                 string          `json:"name"`
	Rung                 string          `json:"rung"`
	Permissions          json.RawMessage `json:"permissions"`
	OverseerInstructions *string         `json:"overseer_instructions"`
}

type ToolOutcome struct {
	ID        uuid.UUID          `json:"id"`
	ToolID    uuid.UUID          `json:"tool_id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Outcome   ToolOutcomeKind    `json:"outcome"`
	At        time.Time          `json:"at"`
	MaturedAt pgtype.Timestamptz `json:"matured_at"`
}
