// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countToolOutcomesForTask = `-- name: CountToolOutcomesForTask :one
SELECT COUNT(*) AS n
FROM tool_outcomes
WHERE task_id = $1
`

// Used in tests to assert exactly-one-write semantics.
func (q *Queries) CountToolOutcomesForTask(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countToolOutcomesForTask, taskID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const decisionAlreadyDispatched = `-- name: DecisionAlreadyDispatched :one
SELECT EXISTS (
  SELECT 1 FROM audit_messages
  WHERE kind = 'decision_resolved'
    AND payload->>'decision_id' = $1::text
    AND payload->>'approved' = 'true'
) AS dispatched
`

// Idempotency guard for non-idempotent tool dispatch. Reports whether an
// approved decision_resolved audit already exists for this decision — it is
// written in the SAME transaction as the tool outcome, after Execute, so a true
// result means a prior attempt already dispatched and recorded. On a recovery
// re-run the workflow consults this before Execute and skips the dispatch,
// closing the at-least-once window between the outcome commit and the DBOS step
// checkpoint. (The narrower Execute-succeeded-but-tx-uncommitted window is
// irreducible without a provider-side idempotency key.)
func (q *Queries) DecisionAlreadyDispatched(ctx context.Context, decisionID string) (bool, error) {
	row := q.db.QueryRow(ctx, decisionAlreadyDispatched, decisionID)
	var dispatched bool
	err := row.Scan(&dispatched)
	return dispatched, err
}

const insertToolOutcome = `-- name: InsertToolOutcome :one
INSERT INTO tool_outcomes (tool_id, task_id, outcome, matured_at, routine_fingerprint)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tool_id, task_id, outcome, at, matured_at, routine_fingerprint
`

type InsertToolOutcomeParams struct {
	ToolID             uuid.UUID          `json:"tool_id"`
	TaskID             uuid.UUID          `json:"task_id"`
	Outcome            ToolOutcomeKind    `json:"outcome"`
	MaturedAt          pgtype.Timestamptz `json:"matured_at"`
	RoutineFingerprint *string            `json:"routine_fingerprint"`
}

// Phase 3: written once per dispatch attempt by the ToolCallWorkflow.
// Phase 8: matured_at (at + window) and routine_fingerprint are now populated by
// the calibration subsystem on the clean/bad paths. denied_by_script passes NULL
// for both (it never matures, never counts toward promotion).
func (q *Queries) InsertToolOutcome(ctx context.Context, arg InsertToolOutcomeParams) (ToolOutcome, error) {
	row := q.db.QueryRow(ctx, insertToolOutcome,
		arg.ToolID,
		arg.TaskID,
		arg.Outcome,
		arg.MaturedAt,
		arg.RoutineFingerprint,
	)
	var i ToolOutcome
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.TaskID,
		&i.Outcome,
		&i.At,
		&i.MaturedAt,
		&i.RoutineFingerprint,
	)
	return i, err
}

const listToolOutcomesForTask = `-- name: ListToolOutcomesForTask :many
SELECT id, tool_id, task_id, outcome, at, matured_at, routine_fingerprint
FROM tool_outcomes
WHERE task_id = $1
ORDER BY at ASC, id ASC
`

// All tool outcomes recorded under a task, oldest-first. Read by the
// post-completion feedback agent (internal/feedback) to summarize what tools
// ran and whether any were flagged bad.
func (q *Queries) ListToolOutcomesForTask(ctx context.Context, taskID uuid.UUID) ([]ToolOutcome, error) {
	rows, err := q.db.Query(ctx, listToolOutcomesForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolOutcome
	for rows.Next() {
		var i ToolOutcome
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.TaskID,
			&i.Outcome,
			&i.At,
			&i.MaturedAt,
			&i.RoutineFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
