// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countToolOutcomesForTask = `-- name: CountToolOutcomesForTask :one
SELECT COUNT(*) AS n
FROM tool_outcomes
WHERE task_id = $1
`

// Used in tests to assert exactly-one-write semantics.
func (q *Queries) CountToolOutcomesForTask(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countToolOutcomesForTask, taskID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const insertToolOutcome = `-- name: InsertToolOutcome :one
INSERT INTO tool_outcomes (tool_id, task_id, outcome)
VALUES ($1, $2, $3)
RETURNING id, tool_id, task_id, outcome, at, matured_at
`

type InsertToolOutcomeParams struct {
	ToolID  uuid.UUID       `json:"tool_id"`
	TaskID  uuid.UUID       `json:"task_id"`
	Outcome ToolOutcomeKind `json:"outcome"`
}

// Phase 3: written once per dispatch attempt by the ToolCallWorkflow.
// matured_at stays NULL — Phase 8's calibration ratchet sets it.
func (q *Queries) InsertToolOutcome(ctx context.Context, arg InsertToolOutcomeParams) (ToolOutcome, error) {
	row := q.db.QueryRow(ctx, insertToolOutcome, arg.ToolID, arg.TaskID, arg.Outcome)
	var i ToolOutcome
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.TaskID,
		&i.Outcome,
		&i.At,
		&i.MaturedAt,
	)
	return i, err
}
