// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overseer.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countOverseerEvalsForTask = `-- name: CountOverseerEvalsForTask :one
SELECT count(*) AS n
FROM audit_messages
WHERE task_id = $1::uuid
  AND kind = 'overseer_evaluated'
`

// Returns the count of overseer_evaluated audit rows for a task. Used by the
// gateway's per-task fail-closed cap (TENDANT_OVERSEER_MAX_EVAL_PER_TASK).
// Covered by idx_audit_task (task_id, at).
func (q *Queries) CountOverseerEvalsForTask(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOverseerEvalsForTask, taskID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const latestOverseerInstructionsChangedForTool = `-- name: LatestOverseerInstructionsChangedForTool :one
SELECT id
FROM audit_messages
WHERE kind = 'overseer_instructions_changed'
  AND payload->>'tool_id' = $1::text
ORDER BY at DESC, id DESC
LIMIT 1
`

// Returns the most recent overseer_instructions_changed audit row for a tool,
// or pgx.ErrNoRows on first write. Used to chain in_reply_to on subsequent
// updates so the per-tool change history forms a chain.
func (q *Queries) LatestOverseerInstructionsChangedForTool(ctx context.Context, dollar_1 string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, latestOverseerInstructionsChangedForTool, dollar_1)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const latestToolPermissionsChangedForTool = `-- name: LatestToolPermissionsChangedForTool :one
SELECT id
FROM audit_messages
WHERE kind = 'tool_permissions_changed'
  AND payload->>'tool_id' = $1::text
ORDER BY at DESC, id DESC
LIMIT 1
`

// Sibling of LatestOverseerInstructionsChangedForTool for permissions edits.
func (q *Queries) LatestToolPermissionsChangedForTool(ctx context.Context, dollar_1 string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, latestToolPermissionsChangedForTool, dollar_1)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const overseerEvaluatedForDecision = `-- name: OverseerEvaluatedForDecision :one
SELECT id, task_id, from_principal, to_principal, in_reply_to, kind, payload, at
FROM audit_messages
WHERE kind = 'overseer_evaluated'
  AND payload->'evidence'->>'decision_id' = $1::text
ORDER BY at DESC, id DESC
LIMIT 1
`

// Resolves ApprovalRequest.overseerEvaluation: returns the overseer_evaluated
// row whose payload was authored as part of escalating this decision. The
// payload carries the decision id under evidence.decision_id (written by the
// gateway when it escalates from a per-task cap or model verdict). Returns
// pgx.ErrNoRows when the decision was floor-raised (no overseer row).
func (q *Queries) OverseerEvaluatedForDecision(ctx context.Context, dollar_1 string) (AuditMessage, error) {
	row := q.db.QueryRow(ctx, overseerEvaluatedForDecision, dollar_1)
	var i AuditMessage
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromPrincipal,
		&i.ToPrincipal,
		&i.InReplyTo,
		&i.Kind,
		&i.Payload,
		&i.At,
	)
	return i, err
}

const updateToolOverseerInstructions = `-- name: UpdateToolOverseerInstructions :one
UPDATE tools
SET overseer_instructions = $2
WHERE id = $1
RETURNING id, global_uri, name, rung, permissions, overseer_instructions, active_script_version
`

type UpdateToolOverseerInstructionsParams struct {
	ID                   uuid.UUID `json:"id"`
	OverseerInstructions *string   `json:"overseer_instructions"`
}

// Owner-only update; resolver enforces RequireOwner first.
func (q *Queries) UpdateToolOverseerInstructions(ctx context.Context, arg UpdateToolOverseerInstructionsParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateToolOverseerInstructions, arg.ID, arg.OverseerInstructions)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
	)
	return i, err
}

const updateToolOverseerInstructionsIfNull = `-- name: UpdateToolOverseerInstructionsIfNull :one
UPDATE tools
SET overseer_instructions = $2
WHERE global_uri = $1
  AND overseer_instructions IS NULL
RETURNING id, global_uri, name, rung, permissions, overseer_instructions, active_script_version
`

type UpdateToolOverseerInstructionsIfNullParams struct {
	GlobalUri            string  `json:"global_uri"`
	OverseerInstructions *string `json:"overseer_instructions"`
}

// Idempotent Phase-4 seeder helper for send-email. Writes only if the column
// is currently NULL (so an owner-tuned value is never clobbered on boot).
func (q *Queries) UpdateToolOverseerInstructionsIfNull(ctx context.Context, arg UpdateToolOverseerInstructionsIfNullParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateToolOverseerInstructionsIfNull, arg.GlobalUri, arg.OverseerInstructions)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
	)
	return i, err
}

const updateToolPermissions = `-- name: UpdateToolPermissions :one
UPDATE tools
SET permissions = $2
WHERE id = $1
RETURNING id, global_uri, name, rung, permissions, overseer_instructions, active_script_version
`

type UpdateToolPermissionsParams struct {
	ID          uuid.UUID       `json:"id"`
	Permissions json.RawMessage `json:"permissions"`
}

// Owner-only update; resolver enforces RequireOwner first.
func (q *Queries) UpdateToolPermissions(ctx context.Context, arg UpdateToolPermissionsParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateToolPermissions, arg.ID, arg.Permissions)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
		&i.ActiveScriptVersion,
	)
	return i, err
}
