// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner_rules.sql

package db

import (
	"context"
)

const getOwnerRule = `-- name: GetOwnerRule :one
SELECT value
FROM owner_rules
WHERE owner_global_uri = $1 AND key = $2
LIMIT 1
`

type GetOwnerRuleParams struct {
	OwnerGlobalUri string `json:"owner_global_uri"`
	Key            string `json:"key"`
}

// owner.rule(key) host function backing (FR-018). Returns pgx.ErrNoRows when
// no rule is set for the key.
func (q *Queries) GetOwnerRule(ctx context.Context, arg GetOwnerRuleParams) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerRule, arg.OwnerGlobalUri, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertOwnerRule = `-- name: UpsertOwnerRule :one
INSERT INTO owner_rules (owner_global_uri, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (owner_global_uri, key) DO UPDATE
  SET value = EXCLUDED.value, updated_at = now()
RETURNING owner_global_uri, key, value, updated_at
`

type UpsertOwnerRuleParams struct {
	OwnerGlobalUri string `json:"owner_global_uri"`
	Key            string `json:"key"`
	Value          string `json:"value"`
}

// setOwnerRule (FR-018): single-row-per-(owner,key) upsert. updated_at is
// advanced on every write so per-rule lifecycle is observable.
func (q *Queries) UpsertOwnerRule(ctx context.Context, arg UpsertOwnerRuleParams) (OwnerRule, error) {
	row := q.db.QueryRow(ctx, upsertOwnerRule, arg.OwnerGlobalUri, arg.Key, arg.Value)
	var i OwnerRule
	err := row.Scan(
		&i.OwnerGlobalUri,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}
