// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPrincipalByGlobalURI = `-- name: GetPrincipalByGlobalURI :one
SELECT id, global_uri, kind, display_name, created_at
FROM principals
WHERE global_uri = $1
`

func (q *Queries) GetPrincipalByGlobalURI(ctx context.Context, globalUri string) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByGlobalURI, globalUri)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipalByID = `-- name: GetPrincipalByID :one
SELECT id, global_uri, kind, display_name, created_at
FROM principals
WHERE id = $1
`

func (q *Queries) GetPrincipalByID(ctx context.Context, id uuid.UUID) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByID, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getViewer = `-- name: GetViewer :one
SELECT id, global_uri, kind, display_name, created_at
FROM principals
WHERE global_uri = 'local://principal/owner'
`

// Returns the owner Principal (the GraphQL `viewer`).
func (q *Queries) GetViewer(ctx context.Context) (Principal, error) {
	row := q.db.QueryRow(ctx, getViewer)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOwner = `-- name: UpsertOwner :exec
INSERT INTO principals (global_uri, kind, display_name)
VALUES ('local://principal/owner', 'user', 'Owner')
ON CONFLICT (global_uri) DO NOTHING
`

// Seeds the single owner Principal. Idempotent on startup.
func (q *Queries) UpsertOwner(ctx context.Context) error {
	_, err := q.db.Exec(ctx, upsertOwner)
	return err
}
