// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package db

import (
	"context"
)

const getViewer = `-- name: GetViewer :one
SELECT id, global_uri, kind, display_name, created_at
FROM principals
WHERE global_uri = 'local://principal/owner'
`

// Returns the owner Principal (the GraphQL `viewer`).
func (q *Queries) GetViewer(ctx context.Context) (Principal, error) {
	row := q.db.QueryRow(ctx, getViewer)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOwner = `-- name: UpsertOwner :exec
INSERT INTO principals (global_uri, kind, display_name)
VALUES ('local://principal/owner', 'user', 'Owner')
ON CONFLICT (global_uri) DO NOTHING
`

// Seeds the single owner Principal. Idempotent on startup.
func (q *Queries) UpsertOwner(ctx context.Context) error {
	_, err := q.db.Exec(ctx, upsertOwner)
	return err
}
