// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUnmetBlockers = `-- name: CountUnmetBlockers :one
SELECT count(*) FROM task_relations tr
JOIN tasks b ON b.id = tr.from_task
WHERE tr.to_task = $1 AND tr.kind = 'blocks'
  AND b.state NOT IN ('done', 'dismissed', 'halted')
`

// Count of $1's blockers that are not yet resolved. A blocker is "met" once it
// reaches any terminal state (done/dismissed/halted) — counting only
// non-terminal blockers prevents a cancelled prerequisite from deadlocking the
// dependent forever (readiness predicate, FR-019).
func (q *Queries) CountUnmetBlockers(ctx context.Context, toTask uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnmetBlockers, toTask)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTaskRelation = `-- name: DeleteTaskRelation :execrows
DELETE FROM task_relations
WHERE from_task = $1 AND to_task = $2 AND kind = $3::task_relation_kind
`

type DeleteTaskRelationParams struct {
	FromTask uuid.UUID        `json:"from_task"`
	ToTask   uuid.UUID        `json:"to_task"`
	Kind     TaskRelationKind `json:"kind"`
}

// Remove a directed relation. Returns the number of rows deleted so the
// resolver can report whether anything was actually removed.
func (q *Queries) DeleteTaskRelation(ctx context.Context, arg DeleteTaskRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskRelation, arg.FromTask, arg.ToTask, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDuplicateOf = `-- name: GetDuplicateOf :one
SELECT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr ON tr.to_task = t.id
WHERE tr.from_task = $1 AND tr.kind = 'duplicate_of'
LIMIT 1
`

// The canonical task $1 duplicates (to_task of $1's 'duplicate_of' edge).
func (q *Queries) GetDuplicateOf(ctx context.Context, fromTask uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getDuplicateOf, fromTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
		&i.ShortID,
		&i.StartsAt,
		&i.Rank,
	)
	return i, err
}

const getParentTask = `-- name: GetParentTask :one
SELECT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr ON tr.to_task = t.id
WHERE tr.from_task = $1 AND tr.kind = 'subtask_of'
LIMIT 1
`

// The parent of $1, if $1 is a subtask (to_task of $1's 'subtask_of' edge).
func (q *Queries) GetParentTask(ctx context.Context, fromTask uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getParentTask, fromTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
		&i.ShortID,
		&i.StartsAt,
		&i.Rank,
	)
	return i, err
}

const insertTaskRelation = `-- name: InsertTaskRelation :one

INSERT INTO task_relations (from_task, to_task, kind)
VALUES ($1, $2, $3::task_relation_kind)
RETURNING id, from_task, to_task, kind, created_at
`

type InsertTaskRelationParams struct {
	FromTask uuid.UUID        `json:"from_task"`
	ToTask   uuid.UUID        `json:"to_task"`
	Kind     TaskRelationKind `json:"kind"`
}

// Task↔task relation graph (migration 00021). Edges are directed:
// from_task --kind--> to_task. The traversal queries below return full task
// rows (db.Task) so resolvers can map them like any other task.
// Add a directed relation. The UNIQUE(from_task,to_task,kind) constraint and
// the no-self CHECK reject duplicates and self-links at the DB; the partial
// unique indexes reject a second parent / canonical. The resolver pre-checks
// cycles via RelationWouldCycle.
func (q *Queries) InsertTaskRelation(ctx context.Context, arg InsertTaskRelationParams) (TaskRelation, error) {
	row := q.db.QueryRow(ctx, insertTaskRelation, arg.FromTask, arg.ToTask, arg.Kind)
	var i TaskRelation
	err := row.Scan(
		&i.ID,
		&i.FromTask,
		&i.ToTask,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listBlockers = `-- name: ListBlockers :many
SELECT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr ON tr.from_task = t.id
WHERE tr.to_task = $1 AND tr.kind = 'blocks'
ORDER BY t.created_at DESC, t.id DESC
`

// Tasks that must clear before $1 can execute (from_task of a 'blocks' edge to $1).
func (q *Queries) ListBlockers(ctx context.Context, toTask uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listBlockers, toTask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Priority,
			&i.DueAt,
			&i.ShortID,
			&i.StartsAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocking = `-- name: ListBlocking :many
SELECT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr ON tr.to_task = t.id
WHERE tr.from_task = $1 AND tr.kind = 'blocks'
ORDER BY t.created_at DESC, t.id DESC
`

// Tasks that $1 blocks (to_task of a 'blocks' edge from $1).
func (q *Queries) ListBlocking(ctx context.Context, fromTask uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listBlocking, fromTask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Priority,
			&i.DueAt,
			&i.ShortID,
			&i.StartsAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependentTaskIDs = `-- name: ListDependentTaskIDs :many
SELECT tr.to_task AS id
FROM task_relations tr
JOIN tasks t ON t.id = tr.to_task
WHERE tr.from_task = $1 AND tr.kind = 'blocks'
  AND t.state IN ('accepted', 'waiting')
ORDER BY tr.to_task
`

// IDs of still-pending tasks that $1 blocks, so the chain can wake them to
// re-evaluate readiness when $1 reaches a terminal state.
func (q *Queries) ListDependentTaskIDs(ctx context.Context, fromTask uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDependentTaskIDs, fromTask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicates = `-- name: ListDuplicates :many
SELECT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr ON tr.from_task = t.id
WHERE tr.to_task = $1 AND tr.kind = 'duplicate_of'
ORDER BY t.created_at DESC, t.id DESC
`

// Tasks marked as duplicates of $1 (from_task of a 'duplicate_of' edge to $1).
func (q *Queries) ListDuplicates(ctx context.Context, toTask uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listDuplicates, toTask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Priority,
			&i.DueAt,
			&i.ShortID,
			&i.StartsAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedTasks = `-- name: ListRelatedTasks :many
SELECT DISTINCT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr
  ON (tr.to_task = t.id AND tr.from_task = $1)
  OR (tr.from_task = t.id AND tr.to_task = $1)
WHERE tr.kind = 'related'
ORDER BY t.created_at DESC, t.id DESC
`

// Non-blocking related tasks in either direction (kind='related'). DISTINCT
// collapses a task linked in both directions to a single row.
func (q *Queries) ListRelatedTasks(ctx context.Context, fromTask uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listRelatedTasks, fromTask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Priority,
			&i.DueAt,
			&i.ShortID,
			&i.StartsAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT t.id, t.global_uri, t.title, t.description, t.state, t.current_stage, t.provenance, t.context_refs, t.findings, t.intake_signal_id, t.created_at, t.edited_at, t.priority, t.due_at, t.short_id, t.starts_at, t.rank FROM tasks t
JOIN task_relations tr ON tr.from_task = t.id
WHERE tr.to_task = $1 AND tr.kind = 'subtask_of'
ORDER BY t.rank ASC NULLS LAST, t.created_at DESC, t.id DESC
`

// Children of $1 (from_task of a 'subtask_of' edge to $1).
func (q *Queries) ListSubtasks(ctx context.Context, toTask uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSubtasks, toTask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Priority,
			&i.DueAt,
			&i.ShortID,
			&i.StartsAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationWouldCycle = `-- name: RelationWouldCycle :one
WITH RECURSIVE reach AS (
  SELECT to_task AS node
  FROM task_relations
  WHERE from_task = $2::uuid
    AND kind = $3::task_relation_kind
  UNION
  SELECT tr.to_task
  FROM task_relations tr
  JOIN reach r ON tr.from_task = r.node
  WHERE tr.kind = $3::task_relation_kind
)
SELECT EXISTS (SELECT 1 FROM reach WHERE node = $1::uuid) AS cycles
`

type RelationWouldCycleParams struct {
	Target uuid.UUID        `json:"target"`
	Start  uuid.UUID        `json:"start"`
	Kind   TaskRelationKind `json:"kind"`
}

// Reports whether adding from→to of `kind` would close a cycle: true when
// `target` is already reachable from `start` following same-kind edges. The
// resolver calls it with start=to_task, target=from_task before inserting a
// blocks / subtask_of edge.
func (q *Queries) RelationWouldCycle(ctx context.Context, arg RelationWouldCycleParams) (bool, error) {
	row := q.db.QueryRow(ctx, relationWouldCycle, arg.Target, arg.Start, arg.Kind)
	var cycles bool
	err := row.Scan(&cycles)
	return cycles, err
}
