// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, principal_id, token_hash, display_name, created_at, last_seen_at, revoked_at
FROM sessions
WHERE token_hash = $1 AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, principal_id, token_hash, display_name, created_at, last_seen_at, revoked_at
FROM sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const issueSession = `-- name: IssueSession :one
INSERT INTO sessions (principal_id, token_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, principal_id, token_hash, display_name, created_at, last_seen_at, revoked_at
`

type IssueSessionParams struct {
	PrincipalID uuid.UUID `json:"principal_id"`
	TokenHash   []byte    `json:"token_hash"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) IssueSession(ctx context.Context, arg IssueSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, issueSession, arg.PrincipalID, arg.TokenHash, arg.DisplayName)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessionsForPrincipal = `-- name: ListActiveSessionsForPrincipal :many
SELECT id, principal_id, token_hash, display_name, created_at, last_seen_at, revoked_at
FROM sessions
WHERE principal_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.TokenHash,
			&i.DisplayName,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, principal_id, token_hash, display_name, created_at, last_seen_at, revoked_at
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSessionLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastSeen, id)
	return err
}
