// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, global_uri, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, global_uri, title, description, state, current_stage,
          provenance, context_refs, findings, intake_signal_id,
          created_at, edited_at
`

type CreateTaskParams struct {
	ID          uuid.UUID `json:"id"`
	GlobalUri   string    `json:"global_uri"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
}

// The app generates id + global_uri (local://task/<uuid>) and passes both.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.GlobalUri,
		arg.Title,
		arg.Description,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, global_uri, title, description, state, current_stage,
       provenance, context_refs, findings, intake_signal_id,
       created_at, edited_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, global_uri, title, description, state, current_stage,
       provenance, context_refs, findings, intake_signal_id,
       created_at, edited_at
FROM tasks
WHERE ($1::task_state IS NULL OR state = $1::task_state)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListTasksParams struct {
	StateFilter    *TaskState         `json:"state_filter"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	Lim            int32              `json:"lim"`
}

// Keyset pagination, ordered by created_at DESC, id DESC. Caller fetches
// limit+1 to detect hasNextPage; optional state filter; optional cursor
// (after_created_at, after_id) encoded by the resolver.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.StateFilter,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
