// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIntakeTask = `-- name: CreateIntakeTask :one
INSERT INTO tasks (id, global_uri, title, description, state, current_stage, provenance, intake_signal_id)
VALUES ($1, $2, $3, $4, $6::task_state, $7::chain_stage,
        $5, $8::uuid)
RETURNING id, global_uri, title, description, state, current_stage,
          provenance, context_refs, findings, intake_signal_id,
          created_at, edited_at, priority, due_at
`

type CreateIntakeTaskParams struct {
	ID             uuid.UUID  `json:"id"`
	GlobalUri      string     `json:"global_uri"`
	Title          string     `json:"title"`
	Description    *string    `json:"description"`
	Provenance     []byte     `json:"provenance"`
	State          TaskState  `json:"state"`
	CurrentStage   ChainStage `json:"current_stage"`
	IntakeSignalID uuid.UUID  `json:"intake_signal_id"`
}

// Intake-origin task (Phase 7): carries provenance (copied from the signal) and
// intake_signal_id (the back-link AND the marker that a task is intake-origin).
// priority/due_at take column defaults ('normal' / NULL) — intake tasks are not
// owner-composed, so the owner sets these later if at all.
func (q *Queries) CreateIntakeTask(ctx context.Context, arg CreateIntakeTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createIntakeTask,
		arg.ID,
		arg.GlobalUri,
		arg.Title,
		arg.Description,
		arg.Provenance,
		arg.State,
		arg.CurrentStage,
		arg.IntakeSignalID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, global_uri, title, description, state, current_stage, priority, due_at)
VALUES ($1, $2, $3, $4, $5::task_state, $6::chain_stage,
        $7::task_priority, $8::timestamptz)
RETURNING id, global_uri, title, description, state, current_stage,
          provenance, context_refs, findings, intake_signal_id,
          created_at, edited_at, priority, due_at
`

type CreateTaskParams struct {
	ID           uuid.UUID          `json:"id"`
	GlobalUri    string             `json:"global_uri"`
	Title        string             `json:"title"`
	Description  *string            `json:"description"`
	State        TaskState          `json:"state"`
	CurrentStage ChainStage         `json:"current_stage"`
	Priority     TaskPriority       `json:"priority"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
}

// The app generates id + global_uri (local://task/<uuid>) and passes both,
// plus the explicit state + current_stage so the owner-authored path can
// write 'accepted','creation' regardless of column defaults. priority defaults
// to 'normal' (owner-set at compose time); due_at is an optional deadline.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.GlobalUri,
		arg.Title,
		arg.Description,
		arg.State,
		arg.CurrentStage,
		arg.Priority,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, global_uri, title, description, state, current_stage,
       provenance, context_refs, findings, intake_signal_id,
       created_at, edited_at, priority, due_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const getTaskByIntakeSignal = `-- name: GetTaskByIntakeSignal :one
SELECT id, global_uri, title, description, state, current_stage,
       provenance, context_refs, findings, intake_signal_id,
       created_at, edited_at, priority, due_at
FROM tasks
WHERE intake_signal_id = $1
LIMIT 1
`

// Idempotency guard for the poll's dispose step: returns the task already
// created for a signal (if any), so a crash between task-create and
// mark-processed never yields a duplicate task on replay.
func (q *Queries) GetTaskByIntakeSignal(ctx context.Context, intakeSignalID pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIntakeSignal, intakeSignalID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, global_uri, title, description, state, current_stage,
       provenance, context_refs, findings, intake_signal_id,
       created_at, edited_at, priority, due_at
FROM tasks
WHERE id = $1
FOR UPDATE
`

// Row-locks the task for an in-tx transition. Callers MUST have opened a tx.
func (q *Queries) GetTaskForUpdate(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUpdate, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, global_uri, title, description, state, current_stage,
       provenance, context_refs, findings, intake_signal_id,
       created_at, edited_at, priority, due_at
FROM tasks
WHERE ($1::task_state IS NULL OR state = $1::task_state)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListTasksParams struct {
	StateFilter    *TaskState         `json:"state_filter"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	Lim            int32              `json:"lim"`
}

// Keyset pagination, ordered by created_at DESC, id DESC. Caller fetches
// limit+1 to detect hasNextPage; optional state filter; optional cursor
// (after_created_at, after_id) encoded by the resolver.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.StateFilter,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CurrentStage,
			&i.Provenance,
			&i.ContextRefs,
			&i.Findings,
			&i.IntakeSignalID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.Priority,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskMetadata = `-- name: UpdateTaskMetadata :one
UPDATE tasks
SET priority = $1::task_priority,
    due_at = $2::timestamptz,
    edited_at = now()
WHERE id = $3::uuid
RETURNING id, global_uri, title, description, state, current_stage,
          provenance, context_refs, findings, intake_signal_id,
          created_at, edited_at, priority, due_at
`

type UpdateTaskMetadataParams struct {
	Priority TaskPriority       `json:"priority"`
	DueAt    pgtype.Timestamptz `json:"due_at"`
	ID       uuid.UUID          `json:"id"`
}

// Replace the owner-set metadata (priority + due date) and bump edited_at.
// "Replace" semantics: priority always has a value; a NULL due_at clears any
// existing deadline (the edit form sends the desired final state).
func (q *Queries) UpdateTaskMetadata(ctx context.Context, arg UpdateTaskMetadataParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskMetadata, arg.Priority, arg.DueAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const updateTaskStage = `-- name: UpdateTaskStage :one
UPDATE tasks
SET current_stage = $1::chain_stage,
    edited_at = now()
WHERE id = $2::uuid
RETURNING id, global_uri, title, description, state, current_stage,
          provenance, context_refs, findings, intake_signal_id,
          created_at, edited_at, priority, due_at
`

type UpdateTaskStageParams struct {
	CurrentStage ChainStage `json:"current_stage"`
	ID           uuid.UUID  `json:"id"`
}

// Set the task's current_stage + edited_at. Returns the updated row.
func (q *Queries) UpdateTaskStage(ctx context.Context, arg UpdateTaskStageParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStage, arg.CurrentStage, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}

const updateTaskState = `-- name: UpdateTaskState :one
UPDATE tasks
SET state = $1::task_state,
    edited_at = now()
WHERE id = $2::uuid
RETURNING id, global_uri, title, description, state, current_stage,
          provenance, context_refs, findings, intake_signal_id,
          created_at, edited_at, priority, due_at
`

type UpdateTaskStateParams struct {
	State TaskState `json:"state"`
	ID    uuid.UUID `json:"id"`
}

// Set the task's state + edited_at. Returns the updated row.
func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskState, arg.State, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CurrentStage,
		&i.Provenance,
		&i.ContextRefs,
		&i.Findings,
		&i.IntakeSignalID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.Priority,
		&i.DueAt,
	)
	return i, err
}
