// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_categories.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTaskCategoryByKey = `-- name: DeleteTaskCategoryByKey :exec
DELETE FROM task_categories
WHERE key = $1
`

func (q *Queries) DeleteTaskCategoryByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteTaskCategoryByKey, key)
	return err
}

const getTaskCategoryByKey = `-- name: GetTaskCategoryByKey :one
SELECT id, key, parent_id, label, description, stage_bindings, origin, version
FROM task_categories
WHERE key = $1
`

func (q *Queries) GetTaskCategoryByKey(ctx context.Context, key string) (TaskCategory, error) {
	row := q.db.QueryRow(ctx, getTaskCategoryByKey, key)
	var i TaskCategory
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ParentID,
		&i.Label,
		&i.Description,
		&i.StageBindings,
		&i.Origin,
		&i.Version,
	)
	return i, err
}

const insertTaskCategory = `-- name: InsertTaskCategory :one
INSERT INTO task_categories (key, parent_id, label, description, stage_bindings, origin, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key, parent_id, label, description, stage_bindings, origin, version
`

type InsertTaskCategoryParams struct {
	Key           string          `json:"key"`
	ParentID      pgtype.UUID     `json:"parent_id"`
	Label         string          `json:"label"`
	Description   *string         `json:"description"`
	StageBindings json.RawMessage `json:"stage_bindings"`
	Origin        ConfigOrigin    `json:"origin"`
	Version       int32           `json:"version"`
}

func (q *Queries) InsertTaskCategory(ctx context.Context, arg InsertTaskCategoryParams) (TaskCategory, error) {
	row := q.db.QueryRow(ctx, insertTaskCategory,
		arg.Key,
		arg.ParentID,
		arg.Label,
		arg.Description,
		arg.StageBindings,
		arg.Origin,
		arg.Version,
	)
	var i TaskCategory
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ParentID,
		&i.Label,
		&i.Description,
		&i.StageBindings,
		&i.Origin,
		&i.Version,
	)
	return i, err
}

const listTaskCategories = `-- name: ListTaskCategories :many
SELECT id, key, parent_id, label, description, stage_bindings, origin, version
FROM task_categories
ORDER BY key
`

func (q *Queries) ListTaskCategories(ctx context.Context) ([]TaskCategory, error) {
	rows, err := q.db.Query(ctx, listTaskCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCategory
	for rows.Next() {
		var i TaskCategory
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ParentID,
			&i.Label,
			&i.Description,
			&i.StageBindings,
			&i.Origin,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskCategoryByKey = `-- name: UpdateTaskCategoryByKey :one
UPDATE task_categories
SET parent_id      = $1,
    label          = $2,
    description    = $3,
    stage_bindings = $4,
    version        = version + 1
WHERE key = $5
RETURNING id, key, parent_id, label, description, stage_bindings, origin, version
`

type UpdateTaskCategoryByKeyParams struct {
	ParentID      pgtype.UUID     `json:"parent_id"`
	Label         string          `json:"label"`
	Description   *string         `json:"description"`
	StageBindings json.RawMessage `json:"stage_bindings"`
	Key           string          `json:"key"`
}

// Applies an override to an existing category row. Bumps version so the change
// is observable, mirroring UpdateAgentConfigByNameAndStage.
func (q *Queries) UpdateTaskCategoryByKey(ctx context.Context, arg UpdateTaskCategoryByKeyParams) (TaskCategory, error) {
	row := q.db.QueryRow(ctx, updateTaskCategoryByKey,
		arg.ParentID,
		arg.Label,
		arg.Description,
		arg.StageBindings,
		arg.Key,
	)
	var i TaskCategory
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ParentID,
		&i.Label,
		&i.Description,
		&i.StageBindings,
		&i.Origin,
		&i.Version,
	)
	return i, err
}
