// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getToolByGlobalURI = `-- name: GetToolByGlobalURI :one
SELECT id, global_uri, name, rung, permissions, overseer_instructions
FROM tools
WHERE global_uri = $1
LIMIT 1
`

func (q *Queries) GetToolByGlobalURI(ctx context.Context, globalUri string) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByGlobalURI, globalUri)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
	)
	return i, err
}

const getToolByID = `-- name: GetToolByID :one
SELECT id, global_uri, name, rung, permissions, overseer_instructions
FROM tools
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetToolByID(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByID, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
	)
	return i, err
}

const listTools = `-- name: ListTools :many
SELECT id, global_uri, name, rung, permissions, overseer_instructions
FROM tools
ORDER BY name ASC
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.GlobalUri,
			&i.Name,
			&i.Rung,
			&i.Permissions,
			&i.OverseerInstructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTool = `-- name: UpsertTool :one
INSERT INTO tools (global_uri, name, rung, permissions, overseer_instructions)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (global_uri) DO UPDATE
  SET name                  = EXCLUDED.name,
      rung                  = EXCLUDED.rung,
      permissions           = EXCLUDED.permissions,
      overseer_instructions = EXCLUDED.overseer_instructions
RETURNING id, global_uri, name, rung, permissions, overseer_instructions
`

type UpsertToolParams struct {
	GlobalUri            string          `json:"global_uri"`
	Name                 string          `json:"name"`
	Rung                 string          `json:"rung"`
	Permissions          json.RawMessage `json:"permissions"`
	OverseerInstructions *string         `json:"overseer_instructions"`
}

// Idempotent: callers can re-run on boot to keep the tool row in sync with
// the in-process tool registry. global_uri is the natural key.
func (q *Queries) UpsertTool(ctx context.Context, arg UpsertToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, upsertTool,
		arg.GlobalUri,
		arg.Name,
		arg.Rung,
		arg.Permissions,
		arg.OverseerInstructions,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.GlobalUri,
		&i.Name,
		&i.Rung,
		&i.Permissions,
		&i.OverseerInstructions,
	)
	return i, err
}
