// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Principal interface {
	IsPrincipal()
	GetID() string
	GetGlobalURI() string
	GetDisplayName() string
}

type AgentAssignment struct {
	ID              string         `json:"id"`
	Task            *Task          `json:"task"`
	Stage           ChainStage     `json:"stage"`
	FromAgent       Principal      `json:"fromAgent,omitempty"`
	Ask             string         `json:"ask"`
	GatheredContext map[string]any `json:"gatheredContext,omitempty"`
	CreatedAt       time.Time      `json:"createdAt"`
	ResolvedAt      *time.Time     `json:"resolvedAt,omitempty"`
}

type Bot struct {
	ID          string `json:"id"`
	GlobalURI   string `json:"globalUri"`
	DisplayName string `json:"displayName"`
}

func (Bot) IsPrincipal()                {}
func (this Bot) GetID() string          { return this.ID }
func (this Bot) GetGlobalURI() string   { return this.GlobalURI }
func (this Bot) GetDisplayName() string { return this.DisplayName }

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Task struct {
	ID             string           `json:"id"`
	GlobalURI      string           `json:"globalUri"`
	Title          string           `json:"title"`
	Description    *string          `json:"description,omitempty"`
	State          TaskState        `json:"state"`
	CurrentStage   ChainStage       `json:"currentStage"`
	Autonomy       AutonomyLevel    `json:"autonomy"`
	Provenance     map[string]any   `json:"provenance,omitempty"`
	ContextRefs    map[string]any   `json:"contextRefs,omitempty"`
	Findings       map[string]any   `json:"findings,omitempty"`
	Workflow       *WorkflowRef     `json:"workflow,omitempty"`
	OpenAssignment *AgentAssignment `json:"openAssignment,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
	EditedAt       *time.Time       `json:"editedAt,omitempty"`
}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type User struct {
	ID          string `json:"id"`
	GlobalURI   string `json:"globalUri"`
	DisplayName string `json:"displayName"`
}

func (User) IsPrincipal()                {}
func (this User) GetID() string          { return this.ID }
func (this User) GetGlobalURI() string   { return this.GlobalURI }
func (this User) GetDisplayName() string { return this.DisplayName }

type WorkflowRef struct {
	ID        string    `json:"id"`
	StartedAt time.Time `json:"startedAt"`
}

type AutonomyLevel string

const (
	AutonomyLevelNone         AutonomyLevel = "NONE"
	AutonomyLevelEnrichOnly   AutonomyLevel = "ENRICH_ONLY"
	AutonomyLevelPropose      AutonomyLevel = "PROPOSE"
	AutonomyLevelExecuteGated AutonomyLevel = "EXECUTE_GATED"
	AutonomyLevelExecuteAuto  AutonomyLevel = "EXECUTE_AUTO"
)

var AllAutonomyLevel = []AutonomyLevel{
	AutonomyLevelNone,
	AutonomyLevelEnrichOnly,
	AutonomyLevelPropose,
	AutonomyLevelExecuteGated,
	AutonomyLevelExecuteAuto,
}

func (e AutonomyLevel) IsValid() bool {
	switch e {
	case AutonomyLevelNone, AutonomyLevelEnrichOnly, AutonomyLevelPropose, AutonomyLevelExecuteGated, AutonomyLevelExecuteAuto:
		return true
	}
	return false
}

func (e AutonomyLevel) String() string {
	return string(e)
}

func (e *AutonomyLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AutonomyLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AutonomyLevel", str)
	}
	return nil
}

func (e AutonomyLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AutonomyLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AutonomyLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ChainStage string

const (
	ChainStageCreation   ChainStage = "CREATION"
	ChainStageTriage     ChainStage = "TRIAGE"
	ChainStageExpansion  ChainStage = "EXPANSION"
	ChainStageExecution  ChainStage = "EXECUTION"
	ChainStageCompletion ChainStage = "COMPLETION"
)

var AllChainStage = []ChainStage{
	ChainStageCreation,
	ChainStageTriage,
	ChainStageExpansion,
	ChainStageExecution,
	ChainStageCompletion,
}

func (e ChainStage) IsValid() bool {
	switch e {
	case ChainStageCreation, ChainStageTriage, ChainStageExpansion, ChainStageExecution, ChainStageCompletion:
		return true
	}
	return false
}

func (e ChainStage) String() string {
	return string(e)
}

func (e *ChainStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChainStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChainStage", str)
	}
	return nil
}

func (e ChainStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChainStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChainStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskState string

const (
	TaskStateProposed  TaskState = "PROPOSED"
	TaskStateAccepted  TaskState = "ACCEPTED"
	TaskStateWaiting   TaskState = "WAITING"
	TaskStateExecuting TaskState = "EXECUTING"
	TaskStateDone      TaskState = "DONE"
	TaskStateDismissed TaskState = "DISMISSED"
	TaskStateHalted    TaskState = "HALTED"
)

var AllTaskState = []TaskState{
	TaskStateProposed,
	TaskStateAccepted,
	TaskStateWaiting,
	TaskStateExecuting,
	TaskStateDone,
	TaskStateDismissed,
	TaskStateHalted,
}

func (e TaskState) IsValid() bool {
	switch e {
	case TaskStateProposed, TaskStateAccepted, TaskStateWaiting, TaskStateExecuting, TaskStateDone, TaskStateDismissed, TaskStateHalted:
		return true
	}
	return false
}

func (e TaskState) String() string {
	return string(e)
}

func (e *TaskState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskState", str)
	}
	return nil
}

func (e TaskState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
