// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ApprovalPayload interface {
	IsApprovalPayload()
}

type InboxItem interface {
	IsInboxItem()
}

type PendingDecision interface {
	IsPendingDecision()
	GetID() string
	GetTask() *Task
	GetCreatedAt() time.Time
}

type Principal interface {
	IsPrincipal()
	GetID() string
	GetGlobalURI() string
	GetDisplayName() string
}

type AgentAssignment struct {
	ID              string         `json:"id"`
	Task            *Task          `json:"task"`
	Stage           ChainStage     `json:"stage"`
	FromAgent       Principal      `json:"fromAgent,omitempty"`
	Ask             string         `json:"ask"`
	GatheredContext map[string]any `json:"gatheredContext,omitempty"`
	CreatedAt       time.Time      `json:"createdAt"`
	ResolvedAt      *time.Time     `json:"resolvedAt,omitempty"`
}

func (AgentAssignment) IsInboxItem() {}

type AgentQuestion struct {
	ID              string    `json:"id"`
	Task            *Task     `json:"task"`
	CreatedAt       time.Time `json:"createdAt"`
	Asker           Principal `json:"asker"`
	Question        string    `json:"question"`
	DisclosureClass *string   `json:"disclosureClass,omitempty"`
}

func (AgentQuestion) IsPendingDecision()           {}
func (this AgentQuestion) GetID() string           { return this.ID }
func (this AgentQuestion) GetTask() *Task          { return this.Task }
func (this AgentQuestion) GetCreatedAt() time.Time { return this.CreatedAt }

func (AgentQuestion) IsInboxItem() {}

type ApprovalRequest struct {
	ID                 string              `json:"id"`
	Task               *Task               `json:"task"`
	CreatedAt          time.Time           `json:"createdAt"`
	Tool               *Tool               `json:"tool"`
	Payload            ApprovalPayload     `json:"payload"`
	OverseerEvaluation *OverseerEvaluation `json:"overseerEvaluation,omitempty"`
}

func (ApprovalRequest) IsPendingDecision()           {}
func (this ApprovalRequest) GetID() string           { return this.ID }
func (this ApprovalRequest) GetTask() *Task          { return this.Task }
func (this ApprovalRequest) GetCreatedAt() time.Time { return this.CreatedAt }

func (ApprovalRequest) IsInboxItem() {}

type Artifact struct {
	Kind      string         `json:"kind"`
	Content   map[string]any `json:"content"`
	Recipient *string        `json:"recipient,omitempty"`
}

func (Artifact) IsApprovalPayload() {}

type Bot struct {
	ID          string `json:"id"`
	GlobalURI   string `json:"globalUri"`
	DisplayName string `json:"displayName"`
}

func (Bot) IsPrincipal()                {}
func (this Bot) GetID() string          { return this.ID }
func (this Bot) GetGlobalURI() string   { return this.GlobalURI }
func (this Bot) GetDisplayName() string { return this.DisplayName }

type Mandate struct {
	Goal        string         `json:"goal"`
	Constraints map[string]any `json:"constraints"`
	Guardrails  map[string]any `json:"guardrails"`
}

func (Mandate) IsApprovalPayload() {}

type Mutation struct {
}

type Notification struct {
	ID        string    `json:"id"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"createdAt"`
	TaskID    *string   `json:"taskId,omitempty"`
}

type OverseerEvaluation struct {
	Verdict          string    `json:"verdict"`
	Summary          string    `json:"summary"`
	ConsideredFields []string  `json:"consideredFields"`
	ModelID          string    `json:"modelId"`
	Provider         string    `json:"provider"`
	TokensIn         int       `json:"tokensIn"`
	TokensOut        int       `json:"tokensOut"`
	EstimatedCostUsd float64   `json:"estimatedCostUsd"`
	At               time.Time `json:"at"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PromotionProposal struct {
	ID        string         `json:"id"`
	Task      *Task          `json:"task"`
	CreatedAt time.Time      `json:"createdAt"`
	Tool      *Tool          `json:"tool"`
	FromLevel AutonomyLevel  `json:"fromLevel"`
	ToLevel   AutonomyLevel  `json:"toLevel"`
	Evidence  map[string]any `json:"evidence"`
}

func (PromotionProposal) IsPendingDecision()           {}
func (this PromotionProposal) GetID() string           { return this.ID }
func (this PromotionProposal) GetTask() *Task          { return this.Task }
func (this PromotionProposal) GetCreatedAt() time.Time { return this.CreatedAt }

func (PromotionProposal) IsInboxItem() {}

type Query struct {
}

type Session struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
	LastSeenAt  time.Time `json:"lastSeenAt"`
}

type SessionMintResult struct {
	Session *Session `json:"session"`
	Token   string   `json:"token"`
}

type Subscription struct {
}

type Task struct {
	ID             string           `json:"id"`
	GlobalURI      string           `json:"globalUri"`
	Title          string           `json:"title"`
	Description    *string          `json:"description,omitempty"`
	State          TaskState        `json:"state"`
	CurrentStage   ChainStage       `json:"currentStage"`
	Autonomy       AutonomyLevel    `json:"autonomy"`
	Provenance     map[string]any   `json:"provenance,omitempty"`
	ContextRefs    map[string]any   `json:"contextRefs,omitempty"`
	Findings       map[string]any   `json:"findings,omitempty"`
	Workflow       *WorkflowRef     `json:"workflow,omitempty"`
	OpenAssignment *AgentAssignment `json:"openAssignment,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
	EditedAt       *time.Time       `json:"editedAt,omitempty"`
}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type Tool struct {
	ID                   string         `json:"id"`
	GlobalURI            string         `json:"globalUri"`
	Name                 string         `json:"name"`
	Rung                 AutonomyLevel  `json:"rung"`
	Permissions          map[string]any `json:"permissions"`
	OverseerInstructions *string        `json:"overseerInstructions,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	GlobalURI   string `json:"globalUri"`
	DisplayName string `json:"displayName"`
}

func (User) IsPrincipal()                {}
func (this User) GetID() string          { return this.ID }
func (this User) GetGlobalURI() string   { return this.GlobalURI }
func (this User) GetDisplayName() string { return this.DisplayName }

type WorkflowRef struct {
	ID        string    `json:"id"`
	StartedAt time.Time `json:"startedAt"`
}

type AutonomyLevel string

const (
	AutonomyLevelNone         AutonomyLevel = "NONE"
	AutonomyLevelEnrichOnly   AutonomyLevel = "ENRICH_ONLY"
	AutonomyLevelPropose      AutonomyLevel = "PROPOSE"
	AutonomyLevelExecuteGated AutonomyLevel = "EXECUTE_GATED"
	AutonomyLevelExecuteAuto  AutonomyLevel = "EXECUTE_AUTO"
)

var AllAutonomyLevel = []AutonomyLevel{
	AutonomyLevelNone,
	AutonomyLevelEnrichOnly,
	AutonomyLevelPropose,
	AutonomyLevelExecuteGated,
	AutonomyLevelExecuteAuto,
}

func (e AutonomyLevel) IsValid() bool {
	switch e {
	case AutonomyLevelNone, AutonomyLevelEnrichOnly, AutonomyLevelPropose, AutonomyLevelExecuteGated, AutonomyLevelExecuteAuto:
		return true
	}
	return false
}

func (e AutonomyLevel) String() string {
	return string(e)
}

func (e *AutonomyLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AutonomyLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AutonomyLevel", str)
	}
	return nil
}

func (e AutonomyLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AutonomyLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AutonomyLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ChainStage string

const (
	ChainStageCreation   ChainStage = "CREATION"
	ChainStageTriage     ChainStage = "TRIAGE"
	ChainStageExpansion  ChainStage = "EXPANSION"
	ChainStageExecution  ChainStage = "EXECUTION"
	ChainStageCompletion ChainStage = "COMPLETION"
)

var AllChainStage = []ChainStage{
	ChainStageCreation,
	ChainStageTriage,
	ChainStageExpansion,
	ChainStageExecution,
	ChainStageCompletion,
}

func (e ChainStage) IsValid() bool {
	switch e {
	case ChainStageCreation, ChainStageTriage, ChainStageExpansion, ChainStageExecution, ChainStageCompletion:
		return true
	}
	return false
}

func (e ChainStage) String() string {
	return string(e)
}

func (e *ChainStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChainStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChainStage", str)
	}
	return nil
}

func (e ChainStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChainStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChainStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DevicePlatform string

const (
	DevicePlatformIos     DevicePlatform = "IOS"
	DevicePlatformAndroid DevicePlatform = "ANDROID"
	DevicePlatformWeb     DevicePlatform = "WEB"
)

var AllDevicePlatform = []DevicePlatform{
	DevicePlatformIos,
	DevicePlatformAndroid,
	DevicePlatformWeb,
}

func (e DevicePlatform) IsValid() bool {
	switch e {
	case DevicePlatformIos, DevicePlatformAndroid, DevicePlatformWeb:
		return true
	}
	return false
}

func (e DevicePlatform) String() string {
	return string(e)
}

func (e *DevicePlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DevicePlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DevicePlatform", str)
	}
	return nil
}

func (e DevicePlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DevicePlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DevicePlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskState string

const (
	TaskStateProposed  TaskState = "PROPOSED"
	TaskStateAccepted  TaskState = "ACCEPTED"
	TaskStateWaiting   TaskState = "WAITING"
	TaskStateExecuting TaskState = "EXECUTING"
	TaskStateDone      TaskState = "DONE"
	TaskStateDismissed TaskState = "DISMISSED"
	TaskStateHalted    TaskState = "HALTED"
)

var AllTaskState = []TaskState{
	TaskStateProposed,
	TaskStateAccepted,
	TaskStateWaiting,
	TaskStateExecuting,
	TaskStateDone,
	TaskStateDismissed,
	TaskStateHalted,
}

func (e TaskState) IsValid() bool {
	switch e {
	case TaskStateProposed, TaskStateAccepted, TaskStateWaiting, TaskStateExecuting, TaskStateDone, TaskStateDismissed, TaskStateHalted:
		return true
	}
	return false
}

func (e TaskState) String() string {
	return string(e)
}

func (e *TaskState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskState", str)
	}
	return nil
}

func (e TaskState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
