// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ApprovalPayload interface {
	IsApprovalPayload()
}

type InboxItem interface {
	IsInboxItem()
}

type PendingDecision interface {
	IsPendingDecision()
	GetID() string
	GetTask() *Task
	GetCreatedAt() time.Time
}

type Principal interface {
	IsPrincipal()
	GetID() string
	GetGlobalURI() string
	GetDisplayName() string
}

type ActionableTask struct {
	ID        string    `json:"id"`
	Task      *Task     `json:"task"`
	CreatedAt time.Time `json:"createdAt"`
}

func (ActionableTask) IsInboxItem() {}

type ActivityEvent struct {
	ID        string         `json:"id"`
	Kind      string         `json:"kind"`
	At        time.Time      `json:"at"`
	Actor     string         `json:"actor"`
	InReplyTo *string        `json:"inReplyTo,omitempty"`
	Detail    map[string]any `json:"detail,omitempty"`
}

type AgentAssignment struct {
	ID              string         `json:"id"`
	Task            *Task          `json:"task"`
	Stage           ChainStage     `json:"stage"`
	FromAgent       Principal      `json:"fromAgent,omitempty"`
	Ask             string         `json:"ask"`
	GatheredContext map[string]any `json:"gatheredContext,omitempty"`
	CreatedAt       time.Time      `json:"createdAt"`
	ResolvedAt      *time.Time     `json:"resolvedAt,omitempty"`
}

func (AgentAssignment) IsInboxItem() {}

type AgentConfigSummary struct {
	ID      string     `json:"id"`
	Name    string     `json:"name"`
	Stage   AgentStage `json:"stage"`
	IsHuman bool       `json:"isHuman"`
	Model   *string    `json:"model,omitempty"`
	Origin  string     `json:"origin"`
	Version int        `json:"version"`
}

type AgentGuidance struct {
	ID            string        `json:"id"`
	Note          string        `json:"note"`
	Scope         GuidanceScope `json:"scope"`
	AgentConfigID *string       `json:"agentConfigId,omitempty"`
	CreatedAt     time.Time     `json:"createdAt"`
}

type AgentQuestion struct {
	ID              string    `json:"id"`
	Task            *Task     `json:"task"`
	CreatedAt       time.Time `json:"createdAt"`
	Asker           Principal `json:"asker"`
	Question        string    `json:"question"`
	DisclosureClass *string   `json:"disclosureClass,omitempty"`
}

func (AgentQuestion) IsPendingDecision()           {}
func (this AgentQuestion) GetID() string           { return this.ID }
func (this AgentQuestion) GetTask() *Task          { return this.Task }
func (this AgentQuestion) GetCreatedAt() time.Time { return this.CreatedAt }

func (AgentQuestion) IsInboxItem() {}

type ApprovalRequest struct {
	ID                   string                `json:"id"`
	Task                 *Task                 `json:"task"`
	CreatedAt            time.Time             `json:"createdAt"`
	Tool                 *Tool                 `json:"tool"`
	Payload              ApprovalPayload       `json:"payload"`
	OverseerEvaluation   *OverseerEvaluation   `json:"overseerEvaluation,omitempty"`
	GateScriptEvaluation *GateScriptEvaluation `json:"gateScriptEvaluation,omitempty"`
}

func (ApprovalRequest) IsPendingDecision()           {}
func (this ApprovalRequest) GetID() string           { return this.ID }
func (this ApprovalRequest) GetTask() *Task          { return this.Task }
func (this ApprovalRequest) GetCreatedAt() time.Time { return this.CreatedAt }

func (ApprovalRequest) IsInboxItem() {}

type Artifact struct {
	Kind      string         `json:"kind"`
	Content   map[string]any `json:"content"`
	Recipient *string        `json:"recipient,omitempty"`
}

func (Artifact) IsApprovalPayload() {}

type Bot struct {
	ID          string `json:"id"`
	GlobalURI   string `json:"globalUri"`
	DisplayName string `json:"displayName"`
}

func (Bot) IsPrincipal()                {}
func (this Bot) GetID() string          { return this.ID }
func (this Bot) GetGlobalURI() string   { return this.GlobalURI }
func (this Bot) GetDisplayName() string { return this.DisplayName }

type ConfigKey struct {
	Key            string  `json:"key"`
	Type           string  `json:"type"`
	Description    string  `json:"description"`
	Reload         string  `json:"reload"`
	Sensitive      bool    `json:"sensitive"`
	DbConfigurable bool    `json:"dbConfigurable"`
	HotReloadable  bool    `json:"hotReloadable"`
	ReadonlyReason *string `json:"readonlyReason,omitempty"`
	DefaultValue   *string `json:"defaultValue,omitempty"`
	EffectiveValue *string `json:"effectiveValue,omitempty"`
	Overridden     bool    `json:"overridden"`
}

type Connector struct {
	ID            string         `json:"id"`
	ConnectorType string         `json:"connectorType"`
	Enabled       bool           `json:"enabled"`
	Config        map[string]any `json:"config"`
}

type FeedbackContext struct {
	ToolsRun            int      `json:"toolsRun"`
	ToolsFlagged        int      `json:"toolsFlagged"`
	AgentStages         []string `json:"agentStages"`
	HandoffReason       *string  `json:"handoffReason,omitempty"`
	ActiveGuidanceCount int      `json:"activeGuidanceCount"`
	Consulted           []string `json:"consulted"`
	Summary             string   `json:"summary"`
}

type FeedbackMessage struct {
	ID        string    `json:"id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type FeedbackRequest struct {
	ID            string             `json:"id"`
	Task          *Task              `json:"task"`
	CreatedAt     time.Time          `json:"createdAt"`
	Messages      []*FeedbackMessage `json:"messages"`
	DraftGuidance *string            `json:"draftGuidance,omitempty"`
	Context       *FeedbackContext   `json:"context,omitempty"`
}

func (FeedbackRequest) IsPendingDecision()           {}
func (this FeedbackRequest) GetID() string           { return this.ID }
func (this FeedbackRequest) GetTask() *Task          { return this.Task }
func (this FeedbackRequest) GetCreatedAt() time.Time { return this.CreatedAt }

func (FeedbackRequest) IsInboxItem() {}

type GateScript struct {
	ID                  string           `json:"id"`
	Tool                *Tool            `json:"tool"`
	Version             int              `json:"version"`
	Manifest            map[string]any   `json:"manifest"`
	ManifestHash        string           `json:"manifestHash"`
	Tier                GateScriptTier   `json:"tier"`
	Status              GateScriptStatus `json:"status"`
	AttachedByPrincipal string           `json:"attachedByPrincipal"`
	AttachedAt          time.Time        `json:"attachedAt"`
	Wasm                Bytes            `json:"wasm,omitempty"`
	Source              *string          `json:"source,omitempty"`
}

type GateScriptEvaluation struct {
	Verdict          string    `json:"verdict"`
	Summary          string    `json:"summary"`
	ConsideredFields []string  `json:"consideredFields"`
	HostcallTrace    []string  `json:"hostcallTrace"`
	ScriptID         string    `json:"scriptId"`
	ScriptVersion    int       `json:"scriptVersion"`
	ManifestHash     string    `json:"manifestHash"`
	At               time.Time `json:"at"`
}

type InboxEntry struct {
	ID          string     `json:"id"`
	Kind        string     `json:"kind"`
	MessageType string     `json:"messageType"`
	CreatedAt   time.Time  `json:"createdAt"`
	Urgency     float64    `json:"urgency"`
	ReadAt      *time.Time `json:"readAt,omitempty"`
	DismissedAt *time.Time `json:"dismissedAt,omitempty"`
	Item        InboxItem  `json:"item"`
}

type InboxFeedPage struct {
	Entries    []*InboxEntry `json:"entries"`
	NextCursor *string       `json:"nextCursor,omitempty"`
}

type InboxMessageState struct {
	ID          string     `json:"id"`
	SeenAt      *time.Time `json:"seenAt,omitempty"`
	ReadAt      *time.Time `json:"readAt,omitempty"`
	DismissedAt *time.Time `json:"dismissedAt,omitempty"`
}

type Mandate struct {
	Goal        string         `json:"goal"`
	Constraints map[string]any `json:"constraints"`
	Guardrails  map[string]any `json:"guardrails"`
}

func (Mandate) IsApprovalPayload() {}

type Mutation struct {
}

type Notification struct {
	ID        string    `json:"id"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"createdAt"`
	TaskID    *string   `json:"taskId,omitempty"`
}

type OverseerEvaluation struct {
	Verdict          string    `json:"verdict"`
	Summary          string    `json:"summary"`
	ConsideredFields []string  `json:"consideredFields"`
	ModelID          string    `json:"modelId"`
	Provider         string    `json:"provider"`
	TokensIn         int       `json:"tokensIn"`
	TokensOut        int       `json:"tokensOut"`
	EstimatedCostUsd float64   `json:"estimatedCostUsd"`
	At               time.Time `json:"at"`
}

type OwnerRule struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PromotionProposal struct {
	ID        string         `json:"id"`
	Task      *Task          `json:"task"`
	CreatedAt time.Time      `json:"createdAt"`
	Tool      *Tool          `json:"tool"`
	FromLevel AutonomyLevel  `json:"fromLevel"`
	ToLevel   AutonomyLevel  `json:"toLevel"`
	Evidence  map[string]any `json:"evidence"`
}

func (PromotionProposal) IsPendingDecision()           {}
func (this PromotionProposal) GetID() string           { return this.ID }
func (this PromotionProposal) GetTask() *Task          { return this.Task }
func (this PromotionProposal) GetCreatedAt() time.Time { return this.CreatedAt }

func (PromotionProposal) IsInboxItem() {}

type Query struct {
}

type RoutingDecision struct {
	Stage       AgentStage            `json:"stage"`
	EligibleSet []*AgentConfigSummary `json:"eligibleSet"`
	Picked      *AgentConfigSummary   `json:"picked,omitempty"`
	PickedHuman bool                  `json:"pickedHuman"`
}

type Session struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
	LastSeenAt  time.Time `json:"lastSeenAt"`
}

type SessionMintResult struct {
	Session *Session `json:"session"`
	Token   string   `json:"token"`
}

type SetTaskCategoryInput struct {
	Key           string         `json:"key"`
	Label         *string        `json:"label,omitempty"`
	Description   *string        `json:"description,omitempty"`
	Parent        *string        `json:"parent,omitempty"`
	StageBindings map[string]any `json:"stageBindings,omitempty"`
}

type StageSlot struct {
	Stage    AgentStage          `json:"stage"`
	Occupant *AgentConfigSummary `json:"occupant,omitempty"`
	IsHuman  bool                `json:"isHuman"`
}

type Subscription struct {
}

type Task struct {
	ID             string           `json:"id"`
	GlobalURI      string           `json:"globalUri"`
	ShortID        int              `json:"shortId"`
	Title          string           `json:"title"`
	Description    *string          `json:"description,omitempty"`
	State          TaskState        `json:"state"`
	CurrentStage   ChainStage       `json:"currentStage"`
	Autonomy       AutonomyLevel    `json:"autonomy"`
	Priority       TaskPriority     `json:"priority"`
	DueAt          *time.Time       `json:"dueAt,omitempty"`
	Provenance     map[string]any   `json:"provenance,omitempty"`
	ContextRefs    map[string]any   `json:"contextRefs,omitempty"`
	Findings       map[string]any   `json:"findings,omitempty"`
	Workflow       *WorkflowRef     `json:"workflow,omitempty"`
	OpenAssignment *AgentAssignment `json:"openAssignment,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
	EditedAt       *time.Time       `json:"editedAt,omitempty"`
	Category       *TaskCategory    `json:"category,omitempty"`
	StageSlots     []*StageSlot     `json:"stageSlots"`
	Activity       []*ActivityEvent `json:"activity"`
}

type TaskCategory struct {
	Key           string          `json:"key"`
	Label         string          `json:"label"`
	Description   *string         `json:"description,omitempty"`
	Parent        *TaskCategory   `json:"parent,omitempty"`
	Children      []*TaskCategory `json:"children"`
	StageBindings map[string]any  `json:"stageBindings"`
}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type Tool struct {
	ID                   string         `json:"id"`
	GlobalURI            string         `json:"globalUri"`
	Name                 string         `json:"name"`
	Rung                 AutonomyLevel  `json:"rung"`
	Permissions          map[string]any `json:"permissions"`
	OverseerInstructions *string        `json:"overseerInstructions,omitempty"`
	ActiveGateScript     *GateScript    `json:"activeGateScript,omitempty"`
	GateScripts          []*GateScript  `json:"gateScripts"`
}

type User struct {
	ID          string `json:"id"`
	GlobalURI   string `json:"globalUri"`
	DisplayName string `json:"displayName"`
}

func (User) IsPrincipal()                {}
func (this User) GetID() string          { return this.ID }
func (this User) GetGlobalURI() string   { return this.GlobalURI }
func (this User) GetDisplayName() string { return this.DisplayName }

type WorkflowRef struct {
	ID        string    `json:"id"`
	StartedAt time.Time `json:"startedAt"`
}

type AgentStage string

const (
	AgentStageTriage    AgentStage = "TRIAGE"
	AgentStageExpansion AgentStage = "EXPANSION"
	AgentStageExecution AgentStage = "EXECUTION"
)

var AllAgentStage = []AgentStage{
	AgentStageTriage,
	AgentStageExpansion,
	AgentStageExecution,
}

func (e AgentStage) IsValid() bool {
	switch e {
	case AgentStageTriage, AgentStageExpansion, AgentStageExecution:
		return true
	}
	return false
}

func (e AgentStage) String() string {
	return string(e)
}

func (e *AgentStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentStage", str)
	}
	return nil
}

func (e AgentStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AutonomyLevel string

const (
	AutonomyLevelNone         AutonomyLevel = "NONE"
	AutonomyLevelEnrichOnly   AutonomyLevel = "ENRICH_ONLY"
	AutonomyLevelPropose      AutonomyLevel = "PROPOSE"
	AutonomyLevelExecuteGated AutonomyLevel = "EXECUTE_GATED"
	AutonomyLevelExecuteAuto  AutonomyLevel = "EXECUTE_AUTO"
)

var AllAutonomyLevel = []AutonomyLevel{
	AutonomyLevelNone,
	AutonomyLevelEnrichOnly,
	AutonomyLevelPropose,
	AutonomyLevelExecuteGated,
	AutonomyLevelExecuteAuto,
}

func (e AutonomyLevel) IsValid() bool {
	switch e {
	case AutonomyLevelNone, AutonomyLevelEnrichOnly, AutonomyLevelPropose, AutonomyLevelExecuteGated, AutonomyLevelExecuteAuto:
		return true
	}
	return false
}

func (e AutonomyLevel) String() string {
	return string(e)
}

func (e *AutonomyLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AutonomyLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AutonomyLevel", str)
	}
	return nil
}

func (e AutonomyLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AutonomyLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AutonomyLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ChainStage string

const (
	ChainStageCreation   ChainStage = "CREATION"
	ChainStageTriage     ChainStage = "TRIAGE"
	ChainStageExpansion  ChainStage = "EXPANSION"
	ChainStageExecution  ChainStage = "EXECUTION"
	ChainStageCompletion ChainStage = "COMPLETION"
)

var AllChainStage = []ChainStage{
	ChainStageCreation,
	ChainStageTriage,
	ChainStageExpansion,
	ChainStageExecution,
	ChainStageCompletion,
}

func (e ChainStage) IsValid() bool {
	switch e {
	case ChainStageCreation, ChainStageTriage, ChainStageExpansion, ChainStageExecution, ChainStageCompletion:
		return true
	}
	return false
}

func (e ChainStage) String() string {
	return string(e)
}

func (e *ChainStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChainStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChainStage", str)
	}
	return nil
}

func (e ChainStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChainStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChainStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DevicePlatform string

const (
	DevicePlatformIos     DevicePlatform = "IOS"
	DevicePlatformAndroid DevicePlatform = "ANDROID"
	DevicePlatformWeb     DevicePlatform = "WEB"
)

var AllDevicePlatform = []DevicePlatform{
	DevicePlatformIos,
	DevicePlatformAndroid,
	DevicePlatformWeb,
}

func (e DevicePlatform) IsValid() bool {
	switch e {
	case DevicePlatformIos, DevicePlatformAndroid, DevicePlatformWeb:
		return true
	}
	return false
}

func (e DevicePlatform) String() string {
	return string(e)
}

func (e *DevicePlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DevicePlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DevicePlatform", str)
	}
	return nil
}

func (e DevicePlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DevicePlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DevicePlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GateScriptStatus string

const (
	GateScriptStatusActive   GateScriptStatus = "ACTIVE"
	GateScriptStatusDisabled GateScriptStatus = "DISABLED"
)

var AllGateScriptStatus = []GateScriptStatus{
	GateScriptStatusActive,
	GateScriptStatusDisabled,
}

func (e GateScriptStatus) IsValid() bool {
	switch e {
	case GateScriptStatusActive, GateScriptStatusDisabled:
		return true
	}
	return false
}

func (e GateScriptStatus) String() string {
	return string(e)
}

func (e *GateScriptStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GateScriptStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GateScriptStatus", str)
	}
	return nil
}

func (e GateScriptStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GateScriptStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GateScriptStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GateScriptTier string

const (
	GateScriptTierAssemblyscriptInApp GateScriptTier = "ASSEMBLYSCRIPT_IN_APP"
	GateScriptTierByoWasm             GateScriptTier = "BYO_WASM"
)

var AllGateScriptTier = []GateScriptTier{
	GateScriptTierAssemblyscriptInApp,
	GateScriptTierByoWasm,
}

func (e GateScriptTier) IsValid() bool {
	switch e {
	case GateScriptTierAssemblyscriptInApp, GateScriptTierByoWasm:
		return true
	}
	return false
}

func (e GateScriptTier) String() string {
	return string(e)
}

func (e *GateScriptTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GateScriptTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GateScriptTier", str)
	}
	return nil
}

func (e GateScriptTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GateScriptTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GateScriptTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GuidanceScope string

const (
	GuidanceScopeGlobal GuidanceScope = "GLOBAL"
	GuidanceScopeAgent  GuidanceScope = "AGENT"
)

var AllGuidanceScope = []GuidanceScope{
	GuidanceScopeGlobal,
	GuidanceScopeAgent,
}

func (e GuidanceScope) IsValid() bool {
	switch e {
	case GuidanceScopeGlobal, GuidanceScopeAgent:
		return true
	}
	return false
}

func (e GuidanceScope) String() string {
	return string(e)
}

func (e *GuidanceScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GuidanceScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GuidanceScope", str)
	}
	return nil
}

func (e GuidanceScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GuidanceScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GuidanceScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "LOW"
	TaskPriorityNormal TaskPriority = "NORMAL"
	TaskPriorityHigh   TaskPriority = "HIGH"
	TaskPriorityUrgent TaskPriority = "URGENT"
)

var AllTaskPriority = []TaskPriority{
	TaskPriorityLow,
	TaskPriorityNormal,
	TaskPriorityHigh,
	TaskPriorityUrgent,
}

func (e TaskPriority) IsValid() bool {
	switch e {
	case TaskPriorityLow, TaskPriorityNormal, TaskPriorityHigh, TaskPriorityUrgent:
		return true
	}
	return false
}

func (e TaskPriority) String() string {
	return string(e)
}

func (e *TaskPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskPriority", str)
	}
	return nil
}

func (e TaskPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskState string

const (
	TaskStateProposed  TaskState = "PROPOSED"
	TaskStateAccepted  TaskState = "ACCEPTED"
	TaskStateWaiting   TaskState = "WAITING"
	TaskStateExecuting TaskState = "EXECUTING"
	TaskStateDone      TaskState = "DONE"
	TaskStateDismissed TaskState = "DISMISSED"
	TaskStateHalted    TaskState = "HALTED"
)

var AllTaskState = []TaskState{
	TaskStateProposed,
	TaskStateAccepted,
	TaskStateWaiting,
	TaskStateExecuting,
	TaskStateDone,
	TaskStateDismissed,
	TaskStateHalted,
}

func (e TaskState) IsValid() bool {
	switch e {
	case TaskStateProposed, TaskStateAccepted, TaskStateWaiting, TaskStateExecuting, TaskStateDone, TaskStateDismissed, TaskStateHalted:
		return true
	}
	return false
}

func (e TaskState) String() string {
	return string(e)
}

func (e *TaskState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskState", str)
	}
	return nil
}

func (e TaskState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
