include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/**/__generated__/**"
    - "lib/**/*.gql.dart"
    - "lib/**/*.g.dart"

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
