package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/bcnelson/tendant/services/api/graph/model"
	"github.com/google/uuid"
)

// SetTaskCategory is the resolver for the setTaskCategory field. Owner-only
// (auth.RequireOwner enforced FIRST in the impl).
func (r *mutationResolver) SetTaskCategory(ctx context.Context, input model.SetTaskCategoryInput) (*model.TaskCategory, error) {
	return r.setTaskCategoryImpl(ctx, input)
}

// DeleteTaskCategory is the resolver for the deleteTaskCategory field. Owner-only.
func (r *mutationResolver) DeleteTaskCategory(ctx context.Context, key string) (bool, error) {
	return r.deleteTaskCategoryImpl(ctx, key)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.TaskCategory, error) {
	return r.categoriesImpl(ctx)
}

// Category is the resolver for the category field.
func (r *taskResolver) Category(ctx context.Context, obj *model.Task) (*model.TaskCategory, error) {
	taskID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, err
	}
	return r.taskCategoryImpl(ctx, taskID)
}

// Parent is the resolver for the parent field.
func (r *taskCategoryResolver) Parent(ctx context.Context, obj *model.TaskCategory) (*model.TaskCategory, error) {
	return r.categoryParentImpl(ctx, obj.Key)
}

// Children is the resolver for the children field.
func (r *taskCategoryResolver) Children(ctx context.Context, obj *model.TaskCategory) ([]*model.TaskCategory, error) {
	return r.categoryChildrenImpl(ctx, obj.Key)
}

// TaskCategory returns TaskCategoryResolver implementation.
func (r *Resolver) TaskCategory() TaskCategoryResolver { return &taskCategoryResolver{r} }

type taskCategoryResolver struct{ *Resolver }
