package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/bcnelson/tendant/services/api/graph/model"
)

// SetConfigEntry is the resolver for the setConfigEntry field.
func (r *mutationResolver) SetConfigEntry(ctx context.Context, key string, value string) (*model.ConfigKey, error) {
	return r.setConfigEntryImpl(ctx, key, value)
}

// DeleteConfigEntry is the resolver for the deleteConfigEntry field.
func (r *mutationResolver) DeleteConfigEntry(ctx context.Context, key string) (bool, error) {
	return r.deleteConfigEntryImpl(ctx, key)
}

// ConfigKeys is the resolver for the configKeys field.
func (r *queryResolver) ConfigKeys(ctx context.Context) ([]*model.ConfigKey, error) {
	return r.configKeysImpl(ctx)
}
