package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/bcnelson/tendant/services/api/graph/model"
	"github.com/bcnelson/tendant/services/api/internal/auth"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// SetConnectorConfig is the resolver for the setConnectorConfig field.
//
// Owner-only (auth.RequireOwner FIRST — before any DB read/write, SC-007).
// Validates connector_type against the registry (SC-008) and upserts the
// config. Enable/disable is the separate enableConnector mutation.
func (r *mutationResolver) SetConnectorConfig(ctx context.Context, connectorID string, config map[string]any) (*model.Connector, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	if !r.Connectors.configured() {
		return nil, gqlerror.Errorf("connector wiring not configured")
	}
	id, err := uuid.Parse(connectorID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid connectorId: %s", err)
	}
	return r.setConnectorConfigImpl(ctx, id, config)
}

// EnableConnector is the resolver for the enableConnector field.
//
// Owner-only. Enabling requires a valid cron schedule and creates the
// per-connector DBOS schedule; disabling deletes it.
func (r *mutationResolver) EnableConnector(ctx context.Context, connectorID string, enabled bool) (*model.Connector, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	if !r.Connectors.configured() {
		return nil, gqlerror.Errorf("connector wiring not configured")
	}
	id, err := uuid.Parse(connectorID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid connectorId: %s", err)
	}
	return r.enableConnectorImpl(ctx, id, enabled)
}

// Connectors is the resolver for the connectors field.
//
// Owner-only — the list reveals which sources are connected.
func (r *queryResolver) Connectors(ctx context.Context) ([]*model.Connector, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	rows, err := r.Queries.ListConnectorConfigs(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Connector, 0, len(rows))
	for i := range rows {
		out = append(out, mapConnector(&rows[i]))
	}
	return out, nil
}
