package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/bcnelson/tendant/services/api/graph/model"
)

// GateScriptEvaluation is the resolver for the gateScriptEvaluation field.
func (r *approvalRequestResolver) GateScriptEvaluation(ctx context.Context, obj *model.ApprovalRequest) (*model.GateScriptEvaluation, error) {
	return r.gateScriptEvaluationImpl(ctx, obj)
}

// AttachGateScript is the resolver for the attachGateScript field.
func (r *mutationResolver) AttachGateScript(ctx context.Context, toolID string, wasm model.Bytes, manifest map[string]any) (*model.GateScript, error) {
	return r.attachGateScriptImpl(ctx, toolID, []byte(wasm), manifest, nil)
}

// CompileAndAttachGateScript is the resolver for the compileAndAttachGateScript field.
func (r *mutationResolver) CompileAndAttachGateScript(ctx context.Context, toolID string, source string, manifest map[string]any) (*model.GateScript, error) {
	return r.compileAndAttachGateScriptImpl(ctx, toolID, source, manifest)
}

// DisableGateScript is the resolver for the disableGateScript field.
func (r *mutationResolver) DisableGateScript(ctx context.Context, toolID string) (*model.Tool, error) {
	return r.disableGateScriptImpl(ctx, toolID)
}

// SetOwnerRule is the resolver for the setOwnerRule field.
func (r *mutationResolver) SetOwnerRule(ctx context.Context, key string, value string) (*model.OwnerRule, error) {
	return r.setOwnerRuleImpl(ctx, key, value)
}

// ActiveGateScript is the resolver for the activeGateScript field.
func (r *toolResolver) ActiveGateScript(ctx context.Context, obj *model.Tool) (*model.GateScript, error) {
	return r.toolActiveGateScriptImpl(ctx, obj)
}

// GateScripts is the resolver for the gateScripts field.
func (r *toolResolver) GateScripts(ctx context.Context, obj *model.Tool, limit *int, offset *int) ([]*model.GateScript, error) {
	return r.toolGateScriptsImpl(ctx, obj, limit, offset)
}
