package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/bcnelson/tendant/services/api/graph/model"
	"github.com/bcnelson/tendant/services/api/internal/auth"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// RegisterMcpServer is the resolver for the registerMcpServer field.
//
// Owner-only (auth.RequireOwner FIRST — before any DB read/write). Registers a
// disabled server; enableMcpServer brings it online + runs the first sync.
func (r *mutationResolver) RegisterMcpServer(ctx context.Context, slug string, name string, endpointURL string, authConfig map[string]any) (*model.McpServer, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	if !r.Mcp.configured() {
		return nil, gqlerror.Errorf("mcp wiring not configured")
	}
	return r.registerMcpServerImpl(ctx, slug, name, endpointURL, authConfig)
}

// SetMcpServerConfig is the resolver for the setMcpServerConfig field.
//
// Owner-only. Updates name / endpoint / auth and invalidates the cached client.
func (r *mutationResolver) SetMcpServerConfig(ctx context.Context, serverID string, name *string, endpointURL *string, authConfig map[string]any) (*model.McpServer, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	if !r.Mcp.configured() {
		return nil, gqlerror.Errorf("mcp wiring not configured")
	}
	id, err := uuid.Parse(serverID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid serverId: %s", err)
	}
	return r.setMcpServerConfigImpl(ctx, id, name, endpointURL, authConfig)
}

// EnableMcpServer is the resolver for the enableMcpServer field.
//
// Owner-only. Enabling runs the first sync; disabling retires the server's tools.
func (r *mutationResolver) EnableMcpServer(ctx context.Context, serverID string, enabled bool) (*model.McpServer, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	if !r.Mcp.configured() {
		return nil, gqlerror.Errorf("mcp wiring not configured")
	}
	id, err := uuid.Parse(serverID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid serverId: %s", err)
	}
	return r.enableMcpServerImpl(ctx, id, enabled)
}

// SyncMcpServer is the resolver for the syncMcpServer field.
//
// Owner-only. Re-discovers an enabled server's tools (owner-tuned permissions
// are preserved).
func (r *mutationResolver) SyncMcpServer(ctx context.Context, serverID string) (*model.McpServer, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	if !r.Mcp.configured() {
		return nil, gqlerror.Errorf("mcp wiring not configured")
	}
	id, err := uuid.Parse(serverID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid serverId: %s", err)
	}
	return r.syncMcpServerImpl(ctx, id)
}

// RemoveMcpServer is the resolver for the removeMcpServer field.
//
// Owner-only. Retires the server's tools (kept for history) and deletes the
// registration + sealed credentials.
func (r *mutationResolver) RemoveMcpServer(ctx context.Context, serverID string) (bool, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return false, permissionDeniedError(ctx)
	}
	if !r.Mcp.configured() {
		return false, gqlerror.Errorf("mcp wiring not configured")
	}
	id, err := uuid.Parse(serverID)
	if err != nil {
		return false, gqlerror.Errorf("invalid serverId: %s", err)
	}
	return r.removeMcpServerImpl(ctx, id)
}

// McpServers is the resolver for the mcpServers field.
//
// Owner-only — the list reveals which integrations are connected.
func (r *queryResolver) McpServers(ctx context.Context) ([]*model.McpServer, error) {
	if _, err := auth.RequireOwner(ctx); err != nil {
		return nil, permissionDeniedError(ctx)
	}
	return r.mcpServersImpl(ctx)
}
