package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/bcnelson/tendant/services/api/graph/model"
	"github.com/bcnelson/tendant/services/api/internal/chain"
	"github.com/bcnelson/tendant/services/api/internal/db"
	"github.com/google/uuid"
)

// AddTaskRelation is the resolver for the addTaskRelation field.
func (r *mutationResolver) AddTaskRelation(ctx context.Context, fromTaskID string, toTaskID string, kind model.TaskRelationKind) (*model.TaskRelation, error) {
	fromID, err := uuid.Parse(fromTaskID)
	if err != nil {
		return nil, fmt.Errorf("invalid fromTaskId: %w", err)
	}
	toID, err := uuid.Parse(toTaskID)
	if err != nil {
		return nil, fmt.Errorf("invalid toTaskId: %w", err)
	}
	if fromID == toID {
		return nil, fmt.Errorf("a task cannot relate to itself")
	}
	dbKind := lowerTaskRelationKind(kind)

	// Cycle guard for the two acyclic kinds: adding from→to closes a cycle when
	// `to` can already reach `from` along same-kind edges.
	if dbKind == db.TaskRelationKindBlocks || dbKind == db.TaskRelationKindSubtaskOf {
		cycles, cerr := r.Queries.RelationWouldCycle(ctx, db.RelationWouldCycleParams{
			Start:  toID,
			Target: fromID,
			Kind:   dbKind,
		})
		if cerr != nil {
			return nil, fmt.Errorf("cycle check: %w", cerr)
		}
		if cycles {
			return nil, fmt.Errorf("relation would create a cycle")
		}
	}

	rel, err := r.Queries.InsertTaskRelation(ctx, db.InsertTaskRelationParams{
		FromTask: fromID,
		ToTask:   toID,
		Kind:     dbKind,
	})
	if err != nil {
		if isUniqueViolation(err) {
			switch dbKind {
			case db.TaskRelationKindSubtaskOf:
				return nil, fmt.Errorf("task already has a parent (remove it first)")
			case db.TaskRelationKindDuplicateOf:
				return nil, fmt.Errorf("task is already marked a duplicate (remove it first)")
			default:
				return nil, fmt.Errorf("relation already exists")
			}
		}
		return nil, fmt.Errorf("insert relation: %w", err)
	}

	// Eagerly load both endpoints so the TaskRelation is fully populated.
	fromTask, err := r.Queries.GetTask(ctx, fromID)
	if err != nil {
		return nil, fmt.Errorf("load from task: %w", err)
	}
	toTask, err := r.Queries.GetTask(ctx, toID)
	if err != nil {
		return nil, fmt.Errorf("load to task: %w", err)
	}
	fromModel, err := mapTask(&fromTask)
	if err != nil {
		return nil, err
	}
	toModel, err := mapTask(&toTask)
	if err != nil {
		return nil, err
	}
	return &model.TaskRelation{
		ID:        rel.ID.String(),
		Kind:      kind,
		From:      fromModel,
		To:        toModel,
		CreatedAt: rel.CreatedAt,
	}, nil
}

// RemoveTaskRelation is the resolver for the removeTaskRelation field.
func (r *mutationResolver) RemoveTaskRelation(ctx context.Context, fromTaskID string, toTaskID string, kind model.TaskRelationKind) (bool, error) {
	fromID, err := uuid.Parse(fromTaskID)
	if err != nil {
		return false, fmt.Errorf("invalid fromTaskId: %w", err)
	}
	toID, err := uuid.Parse(toTaskID)
	if err != nil {
		return false, fmt.Errorf("invalid toTaskId: %w", err)
	}
	dbKind := lowerTaskRelationKind(kind)
	n, err := r.Queries.DeleteTaskRelation(ctx, db.DeleteTaskRelationParams{
		FromTask: fromID,
		ToTask:   toID,
		Kind:     dbKind,
	})
	if err != nil {
		return false, fmt.Errorf("delete relation: %w", err)
	}
	// Removing a blocker may have made the dependent (the to-task) eligible —
	// wake its readiness gate so it re-evaluates instead of waiting for the
	// periodic heartbeat.
	if n > 0 && dbKind == db.TaskRelationKindBlocks {
		if werr := chain.WakeTask(r.DBOS, toID); werr != nil {
			return false, fmt.Errorf("wake dependent: %w", werr)
		}
	}
	return n > 0, nil
}

// Blocked is the resolver for the blocked field.
func (r *taskResolver) Blocked(ctx context.Context, obj *model.Task) (bool, error) {
	id, err := uuid.Parse(obj.ID)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	unmet, err := r.Queries.CountUnmetBlockers(ctx, id)
	if err != nil {
		return false, fmt.Errorf("count unmet blockers: %w", err)
	}
	if unmet > 0 {
		return true, nil
	}
	// A future start date also makes a task not-yet-eligible.
	return obj.StartsAt != nil && obj.StartsAt.After(time.Now()), nil
}

// BlockedBy is the resolver for the blockedBy field.
func (r *taskResolver) BlockedBy(ctx context.Context, obj *model.Task) ([]*model.Task, error) {
	return r.relatedTasks(ctx, obj.ID, r.Queries.ListBlockers)
}

// Blocks is the resolver for the blocks field.
func (r *taskResolver) Blocks(ctx context.Context, obj *model.Task) ([]*model.Task, error) {
	return r.relatedTasks(ctx, obj.ID, r.Queries.ListBlocking)
}

// Parent is the resolver for the parent field.
func (r *taskResolver) Parent(ctx context.Context, obj *model.Task) (*model.Task, error) {
	return r.optionalRelatedTask(ctx, obj.ID, r.Queries.GetParentTask)
}

// Subtasks is the resolver for the subtasks field.
func (r *taskResolver) Subtasks(ctx context.Context, obj *model.Task) ([]*model.Task, error) {
	return r.relatedTasks(ctx, obj.ID, r.Queries.ListSubtasks)
}

// Related is the resolver for the related field.
func (r *taskResolver) Related(ctx context.Context, obj *model.Task) ([]*model.Task, error) {
	return r.relatedTasks(ctx, obj.ID, r.Queries.ListRelatedTasks)
}

// DuplicateOf is the resolver for the duplicateOf field.
func (r *taskResolver) DuplicateOf(ctx context.Context, obj *model.Task) (*model.Task, error) {
	return r.optionalRelatedTask(ctx, obj.ID, r.Queries.GetDuplicateOf)
}

// Duplicates is the resolver for the duplicates field.
func (r *taskResolver) Duplicates(ctx context.Context, obj *model.Task) ([]*model.Task, error) {
	return r.relatedTasks(ctx, obj.ID, r.Queries.ListDuplicates)
}
