package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/bcnelson/tendant/services/api/graph/model"
	"github.com/bcnelson/tendant/services/api/internal/auth"
	"github.com/bcnelson/tendant/services/api/internal/chain"
	"github.com/bcnelson/tendant/services/api/internal/core"
	"github.com/bcnelson/tendant/services/api/internal/db"
	"github.com/bcnelson/tendant/services/api/internal/inbox"
	"github.com/bcnelson/tendant/services/api/internal/lifecycle"
	"github.com/bcnelson/tendant/services/api/internal/realtime"
	"github.com/dbos-inc/dbos-transact-golang/dbos"
	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Task is the resolver for the task field.
func (r *agentAssignmentResolver) Task(ctx context.Context, obj *model.AgentAssignment) (*model.Task, error) {
	id, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid assignment id: %w", err)
	}
	// Look up the task by joining via the assignment row.
	var taskID uuid.UUID
	if err := r.Pool.QueryRow(ctx, `SELECT task_id FROM agent_assignments WHERE id = $1`, id).Scan(&taskID); err != nil {
		return nil, fmt.Errorf("find task for assignment: %w", err)
	}
	t, err := r.Queries.GetTask(ctx, taskID)
	if err != nil {
		return nil, fmt.Errorf("get task: %w", err)
	}
	return mapTask(&t)
}

// FromAgent is the resolver for the fromAgent field. Phase 1: always nil
// because owner-authored tasks have no upstream agent (from_principal is
// NULL). Phase 6 populates the principal from the row.
func (r *agentAssignmentResolver) FromAgent(ctx context.Context, obj *model.AgentAssignment) (model.Principal, error) {
	id, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid assignment id: %w", err)
	}
	var fromPrincipal *string
	if err := r.Pool.QueryRow(ctx, `SELECT from_principal FROM agent_assignments WHERE id = $1`, id).Scan(&fromPrincipal); err != nil {
		return nil, fmt.Errorf("find from_principal: %w", err)
	}
	if fromPrincipal == nil {
		return nil, nil
	}
	// Phase 1 has no real agents on the principal side; resolve by globalUri.
	var (
		pID         uuid.UUID
		gURI, kind  string
		displayName string
	)
	if err := r.Pool.QueryRow(ctx,
		`SELECT id, global_uri, kind, display_name FROM principals WHERE global_uri = $1`,
		*fromPrincipal,
	).Scan(&pID, &gURI, &kind, &displayName); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get principal: %w", err)
	}
	if kind == "bot" {
		return &model.Bot{ID: pID.String(), GlobalURI: gURI, DisplayName: displayName}, nil
	}
	return &model.User{ID: pID.String(), GlobalURI: gURI, DisplayName: displayName}, nil
}

// Task is the resolver for the task field.
func (r *agentQuestionResolver) Task(ctx context.Context, obj *model.AgentQuestion) (*model.Task, error) {
	return r.loadDecisionTask(ctx, obj.ID)
}

// Asker is the resolver for the asker field.
func (r *agentQuestionResolver) Asker(ctx context.Context, obj *model.AgentQuestion) (model.Principal, error) {
	// Phase 2 has exactly one owner; questions opened from the chain layer
	// list the owner as the asker fallback.
	owner, err := r.Queries.GetViewer(ctx)
	if err != nil {
		return nil, err
	}
	return mapUser(&owner), nil
}

// Task is the resolver for the task field.
func (r *approvalRequestResolver) Task(ctx context.Context, obj *model.ApprovalRequest) (*model.Task, error) {
	return r.loadDecisionTask(ctx, obj.ID)
}

// Tool is the resolver for the tool field. Phase 3: loads the real tool
// row via pending_decisions.tool_id.
func (r *approvalRequestResolver) Tool(ctx context.Context, obj *model.ApprovalRequest) (*model.Tool, error) {
	return r.loadDecisionTool(ctx, obj.ID)
}

// Payload is the resolver for the payload field. Phase 3: decodes the
// ApprovalPayload envelope from pending_decisions.payload.
func (r *approvalRequestResolver) Payload(ctx context.Context, obj *model.ApprovalRequest) (model.ApprovalPayload, error) {
	return r.loadDecisionPayload(ctx, obj.ID)
}

// OverseerEvaluation is the resolver for the overseerEvaluation field.
// Phase 4: joins audit_messages on the overseer_evaluated row whose
// evidence.decision_id matches this approval. Returns nil for floor-raised
// approvals (no overseer row) — the UI hides the card in that case.
func (r *approvalRequestResolver) OverseerEvaluation(ctx context.Context, obj *model.ApprovalRequest) (*model.OverseerEvaluation, error) {
	return r.loadOverseerEvaluation(ctx, obj.ID)
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string, description *string) (*model.Task, error) {
	if r.DBOS == nil {
		return nil, fmt.Errorf("chain workflow not available — DBOS context is nil")
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	created, err := core.CreateTask(ctx, r.Pool, r.DBOS, title, desc)
	if err != nil {
		return nil, fmt.Errorf("create task: %w", err)
	}
	t, err := r.Queries.GetTask(ctx, created.ID)
	if err != nil {
		return nil, fmt.Errorf("get created task: %w", err)
	}
	return mapTask(&t)
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, taskID string, result map[string]any) (*model.Task, error) {
	if r.DBOS == nil {
		return nil, fmt.Errorf("chain workflow not available — DBOS context is nil")
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	t, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("task not found")
		}
		return nil, fmt.Errorf("get task: %w", err)
	}
	if lifecycle.IsTerminal(t.State) {
		return nil, taskAlreadyTerminalError(ctx, t.State)
	}
	open, err := r.Queries.FindOpenAssignmentForTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("no open assignment for task")
		}
		return nil, fmt.Errorf("find open assignment: %w", err)
	}
	resultBytes, err := encodeResult(result)
	if err != nil {
		return nil, err
	}
	if err := chain.Resolve(r.DBOS, chain.ChainWorkflowID(tid), chain.TopicForStage(open.Stage), resultBytes); err != nil {
		return nil, fmt.Errorf("resolve chain wait: %w", err)
	}
	// Re-fetch task; the workflow's next step may not have committed yet, but
	// the returned shape reflects the post-Send state we currently observe.
	t2, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		return nil, fmt.Errorf("re-read task: %w", err)
	}
	return mapTask(&t2)
}

// CancelTask is the resolver for the cancelTask field. Performs cleanup
// directly (state → HALTED, audit, EndChainWorkflow) so the workflow's
// blocked Recv doesn't need to participate. Then cancels the DBOS workflow
// (status → Cancelled in DB) and Sends a cancel-sentinel to the current
// stage's topic so the workflow exits cleanly.
func (r *mutationResolver) CancelTask(ctx context.Context, taskID string) (*model.Task, error) {
	if r.DBOS == nil {
		return nil, fmt.Errorf("chain workflow not available — DBOS context is nil")
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	t, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("task not found")
		}
		return nil, fmt.Errorf("get task: %w", err)
	}
	if lifecycle.IsTerminal(t.State) {
		return nil, taskAlreadyTerminalError(ctx, t.State)
	}

	// Cleanup writes (state → HALTED, audit, ended_at).
	if err := chain.HandleCancelCleanup(ctx, r.Pool, tid); err != nil {
		return nil, fmt.Errorf("cancel cleanup: %w", err)
	}

	// Phase 8: reflexive demotion of every tool that acted under the cancelled
	// task (revokes all of each tool's grants). Automatic — no proposal/approval.
	if r.Calibrator != nil {
		if derr := r.Calibrator.DemoteForCancel(ctx, tid); derr != nil {
			return nil, fmt.Errorf("cancel demotion: %w", derr)
		}
	}

	// Mark the DBOS workflow Cancelled. Ignore "not found" — the workflow
	// may have already self-completed in a race with cancellation cleanup.
	live, err := r.Queries.GetLiveWorkflowForTask(ctx, tid)
	switch {
	case err == nil:
		if cerr := dbos.CancelWorkflow(r.DBOS, live.DbosWorkflowID); cerr != nil {
			// Already-cancelled or non-existent — log via err but continue.
			// The cleanup writes above are the source of truth for owner-visible state.
			_ = cerr
		}
		// Unblock the workflow's Recv so the goroutine returns instead of
		// sitting on its stage topic until the DBOS context shuts down.
		_ = chain.Resolve(r.DBOS, live.DbosWorkflowID, chain.TopicForStage(t.CurrentStage), chain.CancelSentinel())
	case errors.Is(err, pgx.ErrNoRows):
		// No live workflow row — nothing to cancel on the DBOS side.
	default:
		return nil, fmt.Errorf("find live workflow: %w", err)
	}

	t2, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		return nil, fmt.Errorf("re-read task: %w", err)
	}
	return mapTask(&t2)
}

// AcceptProposedTask is the resolver for the acceptProposedTask field.
func (r *mutationResolver) AcceptProposedTask(ctx context.Context, taskID string) (*model.Task, error) {
	if r.DBOS == nil {
		return nil, fmt.Errorf("chain workflow not available — DBOS context is nil")
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	if err := pgx.BeginFunc(ctx, r.Pool, func(tx pgx.Tx) error {
		q := db.New(tx)
		t, err := q.GetTaskForUpdate(ctx, tid)
		if err != nil {
			return fmt.Errorf("lock task: %w", err)
		}
		if t.State != lifecycle.StateProposed {
			return fmt.Errorf("task is not PROPOSED (current: %s)", t.State)
		}
		if _, err := lifecycle.Transition(ctx, tx, tid, lifecycle.StateProposed, lifecycle.StateAccepted, "owner accepted", t.CurrentStage); err != nil {
			return err
		}
		return nil
	}); err != nil {
		return nil, err
	}
	if err := core.AttachChainWorkflow(ctx, r.Pool, r.DBOS, tid); err != nil {
		return nil, fmt.Errorf("attach chain: %w", err)
	}
	t2, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		return nil, err
	}
	return mapTask(&t2)
}

// DismissProposedTask is the resolver for the dismissProposedTask field.
func (r *mutationResolver) DismissProposedTask(ctx context.Context, taskID string, reason *string) (*model.Task, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	reasonStr := ""
	if reason != nil {
		reasonStr = *reason
	}
	if err := pgx.BeginFunc(ctx, r.Pool, func(tx pgx.Tx) error {
		q := db.New(tx)
		t, err := q.GetTaskForUpdate(ctx, tid)
		if err != nil {
			return fmt.Errorf("lock task: %w", err)
		}
		intakeOrigin := t.IntakeSignalID.Valid
		switch {
		case t.State == lifecycle.StateProposed:
			if _, err := lifecycle.Transition(ctx, tx, tid, lifecycle.StateProposed, lifecycle.StateDismissed, reasonStr, t.CurrentStage); err != nil {
				return err
			}
		case t.State == lifecycle.StateAccepted && intakeOrigin:
			// Auto-accepted enrich-only intake task: dismissible via the relaxed
			// intake-origin edge (research R4 / D5). Records the reason on the
			// same calibration path Phase 8 reads.
			if _, err := lifecycle.TransitionIntake(ctx, tx, tid, lifecycle.StateAccepted, lifecycle.StateDismissed, reasonStr, t.CurrentStage); err != nil {
				return err
			}
		default:
			return fmt.Errorf("task is not dismissible (state: %s, intake_origin: %v)", t.State, intakeOrigin)
		}
		return nil
	}); err != nil {
		return nil, err
	}
	t2, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		return nil, err
	}
	return mapTask(&t2)
}

// PairDevice is the resolver for the pairDevice field. Validates the presented
// value against the static auth password (reusable), mints a session for the
// seeded owner, and returns the session row + raw token.
func (r *mutationResolver) PairDevice(ctx context.Context, password string, displayName string) (*model.SessionMintResult, error) {
	if r.Password == nil {
		return nil, gqlerror.Errorf("pairing not configured")
	}
	if len(strings.TrimSpace(displayName)) == 0 {
		return nil, gqlerror.Errorf("displayName must not be empty")
	}
	if len(displayName) > 200 {
		return nil, gqlerror.Errorf("displayName must be <= 200 chars")
	}
	if err := r.Password.Verify(password); err != nil {
		return nil, &gqlerror.Error{
			Message:    err.Error(),
			Path:       graphql.GetPath(ctx),
			Extensions: map[string]any{"code": "BAD_PASSWORD"},
		}
	}

	owner, err := r.Queries.GetViewer(ctx)
	if err != nil {
		return nil, fmt.Errorf("seed owner missing: %w", err)
	}

	var sess db.Session
	var raw string
	if err := pgx.BeginFunc(ctx, r.Pool, func(tx pgx.Tx) error {
		q := db.New(tx)
		var ierr error
		sess, raw, ierr = auth.IssueSession(ctx, q, owner.ID, displayName)
		if ierr != nil {
			return ierr
		}
		// audit_messages.task_id is NOT NULL — but we have no task to
		// attach session audit rows to. For Phase 2 we silently skip
		// writing the audit row (the rule's spirit is "tracking session
		// lifecycle on the audit DAG"; Phase 3+ promotes this to a
		// dedicated session_events table). Don't even ATTEMPT the insert,
		// because a FK violation aborts the open transaction and the
		// commit will fail.
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.SessionMintResult{
		Session: &model.Session{
			ID:          sess.ID.String(),
			DisplayName: sess.DisplayName,
			CreatedAt:   sess.CreatedAt,
			LastSeenAt:  sess.LastSeenAt,
		},
		Token: raw,
	}, nil
}

// RevokeSession is the resolver for the revokeSession field. Phase 2
// owner-only: any authenticated principal can revoke any session belonging
// to the seeded owner.
func (r *mutationResolver) RevokeSession(ctx context.Context, sessionID string) (*model.Session, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	sid, err := uuid.Parse(sessionID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid session id: %s", err)
	}
	if !auth.Can(ctx, p, "revoke_session", auth.SessionRef{ID: sid}) {
		return nil, unauthorizedError(ctx)
	}
	row, err := r.Queries.RevokeSession(ctx, sid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerror.Errorf("session not found or already revoked")
		}
		return nil, fmt.Errorf("revoke session: %w", err)
	}
	return &model.Session{
		ID:          row.ID.String(),
		DisplayName: row.DisplayName,
		CreatedAt:   row.CreatedAt,
		LastSeenAt:  row.LastSeenAt,
	}, nil
}

// RegisterDeviceToken is the resolver for the registerDeviceToken field.
func (r *mutationResolver) RegisterDeviceToken(ctx context.Context, token string, platform model.DevicePlatform) (bool, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return false, unauthorizedError(ctx)
	}
	if strings.TrimSpace(token) == "" {
		return false, gqlerror.Errorf("token must not be empty")
	}
	dbPlatform, err := devicePlatformGraphToDB(platform)
	if err != nil {
		return false, err
	}
	if _, err := r.Queries.UpsertDeviceToken(ctx, db.UpsertDeviceTokenParams{
		Token:    token,
		OwnerID:  p.ID,
		Platform: dbPlatform,
	}); err != nil {
		return false, fmt.Errorf("upsert device token: %w", err)
	}
	return true, nil
}

// UnregisterDeviceToken is the resolver for the unregisterDeviceToken field.
func (r *mutationResolver) UnregisterDeviceToken(ctx context.Context, token string) (bool, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return false, unauthorizedError(ctx)
	}
	if err := r.Queries.DeleteDeviceToken(ctx, db.DeleteDeviceTokenParams{
		Token:   token,
		OwnerID: p.ID,
	}); err != nil {
		return false, fmt.Errorf("delete device token: %w", err)
	}
	return true, nil
}

// ApproveArtifact is the resolver for the approveArtifact field. Phase 3:
// marks the decision resolved and wakes the ToolCallWorkflow. Idempotent:
// repeated calls on a resolved decision are a no-op that returns the
// already-resolved decision.
func (r *mutationResolver) ApproveArtifact(ctx context.Context, decisionID string) (model.PendingDecision, error) {
	return r.resolveDecisionMutation(ctx, decisionID, true, "")
}

// RejectApproval is the resolver for the rejectApproval field. Phase 3:
// marks the decision resolved (rejected) and wakes the ToolCallWorkflow
// so it can record audit. No tool dispatch.
func (r *mutationResolver) RejectApproval(ctx context.Context, decisionID string, reason *string) (model.PendingDecision, error) {
	reasonStr := ""
	if reason != nil {
		reasonStr = *reason
	}
	return r.resolveDecisionMutation(ctx, decisionID, false, reasonStr)
}

// AnswerQuestion is the resolver for the answerQuestion field.
func (r *mutationResolver) AnswerQuestion(ctx context.Context, decisionID string, answer string) (model.PendingDecision, error) {
	return nil, notYetAvailable(ctx, "answerQuestion")
}

// DecidePromotion is the resolver for the decidePromotion field.
func (r *mutationResolver) DecidePromotion(ctx context.Context, decisionID string, accept bool) (model.PendingDecision, error) {
	return nil, notYetAvailable(ctx, "decidePromotion")
}

// ProposeToolCall is the resolver for the proposeToolCall field. Phase 3:
// composes a tool call, runs the gate, on RequestDecision writes an
// ApprovalRequest row and starts the durable ToolCallWorkflow that awaits
// resolution. See specs/004-universal-gate-floor/spec.md.
func (r *mutationResolver) ProposeToolCall(ctx context.Context, taskID string, toolGlobalURI string, payload map[string]any) (*model.ApprovalRequest, error) {
	return r.proposeToolCallImpl(ctx, taskID, toolGlobalURI, payload)
}

// SetToolPermissions is the resolver for the setToolPermissions field.
// Phase 4 owner-only: rejects any viewer whose Kind != "user" BEFORE any
// DB write, then validates against the floor's schema. On success writes
// the row and a tool_permissions_changed audit message (no task — uses
// the optional audit shape).
func (r *mutationResolver) SetToolPermissions(ctx context.Context, toolID string, permissions map[string]any) (*model.Tool, error) {
	return r.setToolPermissionsImpl(ctx, toolID, permissions)
}

// SetToolOverseerInstructions is the resolver for the
// setToolOverseerInstructions field. Phase 4 owner-only; same structure
// as SetToolPermissions but writes only the instructions hash + length
// to audit (the canonical text lives in tools.overseer_instructions).
func (r *mutationResolver) SetToolOverseerInstructions(ctx context.Context, toolID string, instructions string) (*model.Tool, error) {
	return r.setToolOverseerInstructionsImpl(ctx, toolID, instructions)
}

// RespondToPromotion is the resolver for the respondToPromotion field. Phase 8
// owner-only: the SINGLE path that raises a tool's autonomy. auth.RequireOwner
// is enforced FIRST (in the impl) before any DB write.
func (r *mutationResolver) RespondToPromotion(ctx context.Context, proposalID string, accept bool) (*model.Tool, error) {
	return r.respondToPromotionImpl(ctx, proposalID, accept)
}

// FlagOutcome is the resolver for the flagOutcome field. Phase 8 owner-only:
// records a bad outcome + reflexively demotes in one operation.
func (r *mutationResolver) FlagOutcome(ctx context.Context, taskID string, toolID string, reason *string) (*model.Tool, error) {
	return r.flagOutcomeImpl(ctx, taskID, toolID, reason)
}

// Task is the resolver for the task field.
func (r *promotionProposalResolver) Task(ctx context.Context, obj *model.PromotionProposal) (*model.Task, error) {
	return r.loadDecisionTask(ctx, obj.ID)
}

// Tool is the resolver for the tool field. Phase 8: resolves the real tool row
// being promoted via pending_decisions.tool_id.
func (r *promotionProposalResolver) Tool(ctx context.Context, obj *model.PromotionProposal) (*model.Tool, error) {
	return r.loadDecisionTool(ctx, obj.ID)
}

// Viewer is the resolver for the viewer field. Returns the authenticated
// principal; nil for unauthenticated requests (the field is nullable in
// the SDL, so this is the canonical "not logged in" shape — exercised by
// TestRevokeSessionInvalidatesBearer).
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	principal, ok := auth.FromContext(ctx)
	if !ok {
		return nil, nil
	}
	p, err := r.Queries.GetPrincipalByID(ctx, principal.ID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get viewer: %w", err)
	}
	return mapUser(&p), nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	t, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get task: %w", err)
	}
	return mapTaskWithAutonomy(&t, deriveTaskAutonomy(ctx, r.Queries, &t))
}

// Tasks is the resolver for the tasks field. Keyset pagination over
// (created_at DESC, id DESC); fetches first+1 to determine hasNextPage.
func (r *queryResolver) Tasks(ctx context.Context, first *int, after *string, state *model.TaskState) (*model.TaskConnection, error) {
	limit := defaultPageSize
	if first != nil {
		if *first <= 0 {
			return nil, fmt.Errorf("first must be > 0")
		}
		limit = *first
	}

	params := db.ListTasksParams{
		StateFilter: lowerTaskStateFilter(state),
		Lim:         int32(limit + 1),
	}
	if after != nil && *after != "" {
		ts, id, err := decodeCursor(*after)
		if err != nil {
			return nil, err
		}
		params.AfterCreatedAt = pgtype.Timestamptz{Time: ts, Valid: true}
		params.AfterID = pgtype.UUID{Bytes: id, Valid: true}
	}

	rows, err := r.Queries.ListTasks(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("list tasks: %w", err)
	}

	hasNextPage := len(rows) > limit
	if hasNextPage {
		rows = rows[:limit]
	}

	conn := &model.TaskConnection{
		Edges:    make([]*model.TaskEdge, 0, len(rows)),
		PageInfo: &model.PageInfo{HasNextPage: hasNextPage},
	}
	for i := range rows {
		t := &rows[i]
		node, err := mapTask(t)
		if err != nil {
			return nil, err
		}
		cursor := encodeCursor(t.CreatedAt, t.ID)
		conn.Edges = append(conn.Edges, &model.TaskEdge{
			Node:   node,
			Cursor: cursor,
		})
	}
	if n := len(conn.Edges); n > 0 {
		c := conn.Edges[n-1].Cursor
		conn.PageInfo.EndCursor = &c
	}
	return conn, nil
}

// Inbox is the resolver for the inbox field. Viewer-scoped (FR-031) — the
// SQL filter restricts agent_assignments to to_principal = viewer.globalUri.
func (r *queryResolver) Inbox(ctx context.Context, first *int, after *string) ([]model.InboxItem, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	limit := int32(inbox.DefaultLimit)
	if first != nil {
		limit = int32(*first)
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	items, _, err := inbox.List(ctx, r.Queries, p.GlobalURI, cursor, limit)
	if err != nil {
		return nil, fmt.Errorf("list inbox: %w", err)
	}
	assembled, err := inbox.Assemble(ctx, r.Queries, items)
	if err != nil {
		return nil, err
	}
	out := make([]model.InboxItem, 0, len(assembled))
	for _, it := range assembled {
		gql, mapErr := mapInboxItem(it)
		if mapErr != nil {
			return nil, mapErr
		}
		if gql == nil {
			continue
		}
		out = append(out, gql)
	}
	return out, nil
}

// PendingDecision is the resolver for the pendingDecision field.
func (r *queryResolver) PendingDecision(ctx context.Context, id string) (model.PendingDecision, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	pid, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlerror.Errorf("invalid decision id: %s", err)
	}
	row, err := r.Queries.GetPendingDecisionByID(ctx, pid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get pending decision: %w", err)
	}
	if !auth.Can(ctx, p, "view", &row) {
		return nil, nil
	}
	d, err := mapPendingDecisionRow(&row)
	if err != nil {
		return nil, err
	}
	return d, nil
}

// AgentAssignment is the resolver for the agentAssignment field.
func (r *queryResolver) AgentAssignment(ctx context.Context, id string) (*model.AgentAssignment, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	aid, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlerror.Errorf("invalid assignment id: %s", err)
	}
	row, err := r.Queries.GetAgentAssignmentByID(ctx, aid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get assignment: %w", err)
	}
	if !auth.Can(ctx, p, "view", &row) {
		return nil, nil
	}
	return mapAssignment(&row)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context) ([]*model.Session, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	rows, err := r.Queries.ListActiveSessionsForPrincipal(ctx, p.ID)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	out := make([]*model.Session, 0, len(rows))
	for _, s := range rows {
		out = append(out, &model.Session{
			ID:          s.ID.String(),
			DisplayName: s.DisplayName,
			CreatedAt:   s.CreatedAt,
			LastSeenAt:  s.LastSeenAt,
		})
	}
	return out, nil
}

// AgentConfigs is the resolver for the agentConfigs field.
func (r *queryResolver) AgentConfigs(ctx context.Context, stage *model.AgentStage) ([]*model.AgentConfigSummary, error) {
	var configs []db.AgentConfig
	var err error

	if stage != nil {
		dbStage := db.AgentStage(strings.ToLower(string(*stage)))
		configs, err = r.Queries.ListAgentConfigsByStage(ctx, dbStage)
	} else {
		configs, err = r.Queries.ListAllAgentConfigs(ctx)
	}
	if err != nil {
		return nil, err
	}

	out := make([]*model.AgentConfigSummary, 0, len(configs))
	for _, cfg := range configs {
		out = append(out, mapAgentConfigSummary(cfg))
	}
	return out, nil
}

// InboxItemArrived is the resolver for the inboxItemArrived field.
func (r *subscriptionResolver) InboxItemArrived(ctx context.Context) (<-chan model.InboxItem, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	if r.Dispatcher == nil {
		return nil, gqlerror.Errorf("realtime dispatcher unavailable")
	}
	sub := realtime.NewInboxSubscriber(p)
	out := make(chan model.InboxItem, realtime.DefaultSubscriberCapacity)
	dereg := r.Dispatcher.Register(sub)
	go r.streamInboxEvents(ctx, sub, out, dereg)
	return out, nil
}

// TaskChanged is the resolver for the taskChanged field.
func (r *subscriptionResolver) TaskChanged(ctx context.Context, taskID *string) (<-chan *model.Task, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	if r.Dispatcher == nil {
		return nil, gqlerror.Errorf("realtime dispatcher unavailable")
	}
	sub := realtime.NewTaskChangedSubscriber(p, taskID)
	out := make(chan *model.Task, realtime.DefaultSubscriberCapacity)
	dereg := r.Dispatcher.Register(sub)
	go r.streamTaskEvents(ctx, sub, out, dereg)
	return out, nil
}

// NotificationReceived is the resolver for the notificationReceived field.
// Phase 2 emits no notifications; the channel stays open without firing.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *model.Notification, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, unauthorizedError(ctx)
	}
	if r.Dispatcher == nil {
		return nil, gqlerror.Errorf("realtime dispatcher unavailable")
	}
	sub := realtime.NewNotificationSubscriber(p)
	out := make(chan *model.Notification, realtime.DefaultSubscriberCapacity)
	dereg := r.Dispatcher.Register(sub)
	go r.streamNotificationEvents(ctx, sub, out, dereg)
	return out, nil
}

// Workflow is the resolver for the workflow field.
func (r *taskResolver) Workflow(ctx context.Context, obj *model.Task) (*model.WorkflowRef, error) {
	tid, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid task id: %w", err)
	}
	wf, err := r.Queries.GetLiveWorkflowForTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// No live workflow row — also check terminated rows for completeness.
			return loadAnyWorkflow(ctx, r.Pool, tid)
		}
		return nil, fmt.Errorf("get live workflow: %w", err)
	}
	return &model.WorkflowRef{ID: wf.DbosWorkflowID, StartedAt: wf.StartedAt}, nil
}

// OpenAssignment is the resolver for the openAssignment field.
func (r *taskResolver) OpenAssignment(ctx context.Context, obj *model.Task) (*model.AgentAssignment, error) {
	tid, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid task id: %w", err)
	}
	row, err := r.Queries.FindOpenAssignmentForTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("find open assignment: %w", err)
	}
	return mapAssignment(&row)
}

// AgentAssignment returns AgentAssignmentResolver implementation.
func (r *Resolver) AgentAssignment() AgentAssignmentResolver { return &agentAssignmentResolver{r} }

// AgentQuestion returns AgentQuestionResolver implementation.
func (r *Resolver) AgentQuestion() AgentQuestionResolver { return &agentQuestionResolver{r} }

// ApprovalRequest returns ApprovalRequestResolver implementation.
func (r *Resolver) ApprovalRequest() ApprovalRequestResolver { return &approvalRequestResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PromotionProposal returns PromotionProposalResolver implementation.
func (r *Resolver) PromotionProposal() PromotionProposalResolver {
	return &promotionProposalResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

// Tool returns ToolResolver implementation.
func (r *Resolver) Tool() ToolResolver { return &toolResolver{r} }

type agentAssignmentResolver struct{ *Resolver }
type agentQuestionResolver struct{ *Resolver }
type approvalRequestResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type promotionProposalResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
type toolResolver struct{ *Resolver }
