package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/bcnelson/tendant/services/api/graph/model"
	"github.com/bcnelson/tendant/services/api/internal/db"
	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	p, err := r.Queries.GetViewer(ctx)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get viewer: %w", err)
	}
	return mapUser(&p), nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	t, err := r.Queries.GetTask(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get task: %w", err)
	}
	return mapTask(&t)
}

// Tasks is the resolver for the tasks field. Keyset pagination over
// (created_at DESC, id DESC); fetches first+1 to determine hasNextPage.
func (r *queryResolver) Tasks(ctx context.Context, first *int, after *string, state *model.TaskState) (*model.TaskConnection, error) {
	limit := defaultPageSize
	if first != nil {
		if *first <= 0 {
			return nil, fmt.Errorf("first must be > 0")
		}
		limit = *first
	}

	params := db.ListTasksParams{
		StateFilter: lowerTaskStateFilter(state),
		Lim:         int32(limit + 1),
	}
	if after != nil && *after != "" {
		ts, id, err := decodeCursor(*after)
		if err != nil {
			return nil, err
		}
		params.AfterCreatedAt = pgtype.Timestamptz{Time: ts, Valid: true}
		params.AfterID = pgtype.UUID{Bytes: id, Valid: true}
	}

	rows, err := r.Queries.ListTasks(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("list tasks: %w", err)
	}

	hasNextPage := len(rows) > limit
	if hasNextPage {
		rows = rows[:limit]
	}

	conn := &model.TaskConnection{
		Edges:    make([]*model.TaskEdge, 0, len(rows)),
		PageInfo: &model.PageInfo{HasNextPage: hasNextPage},
	}
	for i := range rows {
		t := &rows[i]
		node, err := mapTask(t)
		if err != nil {
			return nil, err
		}
		cursor := encodeCursor(t.CreatedAt, t.ID)
		conn.Edges = append(conn.Edges, &model.TaskEdge{
			Node:   node,
			Cursor: cursor,
		})
	}
	if n := len(conn.Edges); n > 0 {
		c := conn.Edges[n-1].Cursor
		conn.PageInfo.EndCursor = &c
	}
	return conn, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
